/**
 * Static snapshot of the ZIP index, used ONLY when the live fetch from
 * github.com/zcash/zips fails (network outage, GitHub 5xx, malformed
 * upstream). Under normal conditions this file is never read by the
 * page — it just keeps the UX from breaking on rare upstream failures.
 *
 * Snapshot date: 2026-05 (post-NU6.1).
 */

import type { Zip, ZipStatus } from "../types";

type ZipTuple = [number, string, ZipStatus, string[]];

const RAW: ZipTuple[] = [
  [0, "ZIP Process", "Active", ["process"]],
  [32, "Shielded Hierarchical Deterministic Wallets", "Final", ["wallet"]],
  [48, "Transparent Multisig Wallets", "Draft", ["wallet"]],
  [68, "Relative lock-time using consensus-enforced sequence numbers", "Draft", ["consensus"]],
  [76, "Transaction Signature Validation before Overwinter", "Reserved", ["consensus"]],
  [112, "CHECKSEQUENCEVERIFY", "Draft", ["consensus"]],
  [113, "Median Time Past as endpoint for lock-time calculations", "Draft", ["consensus"]],
  [129, "Zcash Transparent Multisig Setup", "Reserved", ["wallet"]],
  [143, "Transaction Signature Validation for Overwinter", "Final", ["consensus"]],
  [155, "addrv2 message", "Proposed", ["network"]],
  [173, "Bech32 Format", "Final", ["wallet"]],
  [200, "Network Upgrade Mechanism", "Final", ["consensus", "network"]],
  [201, "Network Peer Management for Overwinter", "Final", ["network"]],
  [202, "Version 3 Transaction Format for Overwinter", "Final", ["consensus"]],
  [203, "Transaction Expiry", "Final", ["consensus"]],
  [204, "Zcash P2P Network Protocol", "Draft", ["network"]],
  [205, "Deployment of the Sapling Network Upgrade", "Final", ["consensus", "upgrade"]],
  [206, "Deployment of the Blossom Network Upgrade", "Final", ["consensus", "upgrade"]],
  [207, "Funding Streams", "Final", ["funding"]],
  [208, "Shorter Block Target Spacing", "Final", ["consensus"]],
  [209, "Prohibit Negative Shielded Chain Value Pool Balances", "Final", ["consensus"]],
  [210, "Sapling Anchor Deduplication within Transactions", "Withdrawn", ["consensus"]],
  [211, "Disabling Addition of New Value to the Sprout Chain Value Pool", "Final", ["consensus"]],
  [212, "Allow Recipient to Derive Ephemeral Secret from Note Plaintext", "Final", ["consensus", "wallet"]],
  [213, "Shielded Coinbase", "Final", ["consensus"]],
  [214, "Consensus rules for a Zcash Development Fund", "Proposed", ["funding", "consensus"]],
  [215, "Explicitly Defining and Modifying Ed25519 Validation Rules", "Final", ["consensus"]],
  [216, "Require Canonical Jubjub Point Encodings", "Final", ["consensus"]],
  [217, "Aggregate Signatures", "Reserved", ["consensus"]],
  [219, "Disabling Addition of New Value to the Sapling Chain Value Pool", "Reserved", ["consensus"]],
  [220, "Zcash Shielded Assets", "Withdrawn", ["consensus"]],
  [221, "FlyClient - Consensus-Layer Changes", "Final", ["consensus"]],
  [222, "Transparent Zcash Extensions", "Draft", ["consensus"]],
  [224, "Orchard Shielded Protocol", "Final", ["consensus"]],
  [225, "Version 5 Transaction Format", "Final", ["consensus"]],
  [226, "Transfer and Burn of Zcash Shielded Assets", "Draft", ["nu7", "consensus"]],
  [227, "Issuance of Zcash Shielded Assets", "Draft", ["nu7", "consensus"]],
  [228, "Asset Swaps for Zcash Shielded Assets", "Reserved", ["consensus"]],
  [230, "Version 6 Transaction Format", "Draft", ["nu7", "consensus"]],
  [231, "Memo Bundles", "Draft", ["nu7", "consensus"]],
  [233, "Network Sustainability Mechanism: Removing Funds From Circulation", "Draft", ["nu7", "funding"]],
  [234, "Network Sustainability Mechanism: Issuance Smoothing", "Draft", ["nu7", "funding"]],
  [235, "Remove 60% of Transaction Fees From Circulation", "Draft", ["nu7", "funding"]],
  [236, "Blocks should balance exactly", "Final", ["consensus"]],
  [239, "Relay of Version 5 Transactions", "Final", ["network"]],
  [240, "Standard Transaction Rules", "Reserved", ["consensus"]],
  [243, "Transaction Signature Validation for Sapling", "Final", ["consensus"]],
  [244, "Transaction Identifier Non-Malleability", "Final", ["consensus"]],
  [245, "Transaction Identifier Digests & Signature Validation for Transparent Zcash Extensions", "Draft", ["consensus"]],
  [246, "Digests for the Version 6 Transaction Format", "Draft", ["nu7", "consensus"]],
  [250, "Deployment of the Heartwood Network Upgrade", "Final", ["consensus", "upgrade"]],
  [251, "Deployment of the Canopy Network Upgrade", "Final", ["consensus", "upgrade"]],
  [252, "Deployment of the NU5 Network Upgrade", "Final", ["consensus", "upgrade"]],
  [253, "Deployment of the NU6 Network Upgrade", "Final", ["consensus", "upgrade"]],
  [254, "Deployment of the NU7 Network Upgrade (Withdrawn)", "Withdrawn", ["consensus", "upgrade"]],
  [255, "Deployment of the NU6.1 Network Upgrade", "Proposed", ["consensus", "upgrade"]],
  [260, "Extending Block Messages with Additional Authentication Data", "Reserved", ["consensus"]],
  [270, "Key Rotation for Tracked Signing Keys", "Reserved", ["wallet"]],
  [271, "Dev Fund Extension and One-Time Disbursement", "Proposed", ["funding"]],
  [300, "Cross-chain Atomic Transactions", "Proposed", ["consensus", "network"]],
  [301, "Zcash Stratum Protocol", "Active", ["network", "mining"]],
  [302, "Standardized Memo Field Format", "Draft", ["wallet"]],
  [303, "Sprout Payment Disclosure", "Reserved", ["wallet"]],
  [304, "Sapling Address Signatures", "Draft", ["wallet"]],
  [305, "Best Practices for Hardware Wallets supporting Sapling", "Reserved", ["wallet"]],
  [306, "Security Considerations for Anchor Selection", "Reserved", ["wallet"]],
  [307, "Light Client Protocol for Payment Detection", "Draft", ["network", "wallet"]],
  [308, "Sprout to Sapling Migration", "Active", ["wallet"]],
  [309, "Blind Off-chain Lightweight Transactions (BOLT)", "Reserved", ["network"]],
  [310, "Security Properties of Sapling Viewing Keys", "Draft", ["wallet"]],
  [311, "Zcash Payment Disclosures", "Draft", ["wallet"]],
  [312, "FROST for Spend Authorization Multisignatures", "Draft", ["wallet"]],
  [313, "Reduce Conventional Transaction Fee to 1000 zatoshis", "Obsolete", ["consensus"]],
  [314, "Privacy upgrades to the Zcash light client protocol", "Reserved", ["network"]],
  [315, "Best Practices for Wallet Implementations", "Draft", ["wallet"]],
  [316, "Unified Addresses and Unified Viewing Keys", "Active", ["wallet"]],
  [317, "Proportional Transfer Fee Mechanism", "Active", ["consensus"]],
  [318, "Associated Payload Encryption", "Reserved", ["consensus"]],
  [319, "Options for Shielded Pool Retirement", "Reserved", ["consensus"]],
  [320, "Defining an Address Type to which funds can only be sent from Transparent Addresses", "Active", ["wallet"]],
  [321, "Payment Request URIs", "Active", ["wallet"]],
  [322, "Generic Signed Message Format", "Reserved", ["wallet"]],
  [323, "Specification of getblocktemplate for Zcash", "Reserved", ["mining"]],
  [324, "URI-Encapsulated Payments", "Draft", ["wallet"]],
  [325, "Account Metadata Keys", "Draft", ["wallet"]],
  [332, "Wallet Recovery from zcashd HD Seeds", "Reserved", ["wallet"]],
  [339, "Wallet Recovery Words", "Reserved", ["wallet"]],
  [350, "Bech32m", "Reserved", ["wallet"]],
  [400, "Wallet.dat format", "Draft", ["wallet"]],
  [401, "Addressing Mempool Denial-of-Service", "Active", ["consensus", "network"]],
  [402, "New Wallet Database Format", "Reserved", ["wallet"]],
  [403, "Verification Behaviour of zcashd", "Reserved", ["consensus"]],
  [416, "Support for Unified Addresses in zcashd", "Reserved", ["wallet"]],
  [1001, "Keep the Block Distribution as Initially Defined — 90% to Miners", "Obsolete", ["funding"]],
  [1002, "Opt-in Donation Feature", "Obsolete", ["funding"]],
  [1003, "20% Split Evenly Between the ECC and the Zcash Foundation, and a Voting System Mandate", "Obsolete", ["funding"]],
  [1004, "Miner-Directed Dev Fund", "Obsolete", ["funding"]],
  [1005, "Zcash Community Funding System", "Obsolete", ["funding"]],
  [1006, "Development Fund of 10% to a 2-of-3 Multisig with Community-Involved Third Entity", "Obsolete", ["funding"]],
  [1007, "Enforce Development Fund Commitments with a Legal Charter", "Obsolete", ["funding"]],
  [1008, "Fund ECC for Two More Years", "Obsolete", ["funding"]],
  [1009, "Five-Entity Strategic Council", "Obsolete", ["funding"]],
  [1010, "Compromise Dev Fund Proposal With Diverse Funding Streams", "Obsolete", ["funding"]],
  [1011, "Decentralize the Dev Fee", "Obsolete", ["funding"]],
  [1012, "Dev Fund to ECC + ZF + Major Grants", "Obsolete", ["funding"]],
  [1013, "Keep It Simple, Zcashers: 10% to ECC, 10% to ZF", "Obsolete", ["funding"]],
  [1014, "Establishing a Dev Fund for ECC, ZF, and Major Grants", "Active", ["funding"]],
  [1015, "Block Subsidy Allocation for Non-Direct Development Funding", "Final", ["funding"]],
  [1016, "Community and Coinholder Funding Model", "Proposed", ["funding"]],
  [2001, "Lockbox Funding Streams", "Final", ["funding", "consensus"]],
  [2002, "Explicit Fees", "Draft", ["nu7", "consensus"]],
  [2003, "Disallow version 4 transactions", "Draft", ["nu7", "consensus"]],
  [2004, "Remove the dependency of consensus on note encryption", "Draft", ["consensus"]],
  [2005, "Orchard Quantum Recoverability", "Draft", ["consensus"]],
];

export const FALLBACK_ZIPS: Zip[] = RAW.map(([num, title, status, tags]) => ({
  num,
  title,
  status,
  tags,
  summary: null,
}));
