export const ambassadorProjects = [
  {
    name: "Zcash Korea",
    twitter: "https://x.com/zcashkorea",
    description: "Zcash community and advocacy in Korea",
    projectSite: null,
    image: "/zcashkorea.jpg",
  },
  {
    name: "ruZcash",
    twitter: "https://x.com/ruZCASH",
    description: "Zcash community and advocacy in Russia",
    projectSite: null,
    image: "/Zcashcard.png",
    blog: "https://pro.zcash.ru/",
  },
  {
    name: "Zcash Arabia",
    twitter: "https://x.com/ZcashArabia",
    description: "Zcash community and advocacy in Arabic-speaking regions",
    projectSite: null,
    image: "/zcashArabia.jpg",
  },
  {
    name: "Zcash Brazil",
    twitter: "https://x.com/zcashbrazil",
    description: "Zcash community and advocacy in Brazil",
    projectSite: null,
    image: "/zcashBrazil.jpg",
  },
  {
    name: "Zcash Ghana",
    twitter: "https://x.com/ZcashGH",
    description: "Zcash community and advocacy in Ghana",
    projectSite: null,
    image: "/zcashGhana.jpg",
  },
  {
    name: "Zcash Español",
    twitter: "https://x.com/zcashesp",
    description: "Zcash community and advocacy in Spanish-speaking regions",
    projectSite: null,
    image: "/zcashEspanol.jpg",
    blog: "https://privacidad.me/@zcashesp",
  },
  {
    name: "Zcash Nigeria",
    twitter: "https://x.com/ZcashNigeria",
    description: "Zcash community and advocacy in Nigeria",
    projectSite: null,
    image: "/zcashNigeria.jpg",
  },
  {
    name: "Zcash Ukraine",
    twitter: "https://x.com/Zcash_ua",
    description: "Zcash community and advocacy in Ukraine",
    projectSite: null,
    image: "/zcashUkraine.jpg",
  },
  {
    name: "Zcash Turkey",
    twitter: "https://x.com/ZcashTR",
    description: "Zcash community and advocacy in Turkey",
    projectSite: null,
    image: "/zcashTurkey.jpg",
  },
    {
    name: "Zcash Kenya",
    twitter: "https://x.com/ZcashKenya",
    description: "Zcash community and advocacy in Kenya",
    projectSite: null,
    image: "/zcashKenya.jpg",
  },
];
