export const ambassadorProjects = [
  {
    name: "Zcash Korea",
    flag: "🇰🇷",
    twitter: "https://x.com/zcashkorea",
    description: "Zcash community and advocacy in Korea",
    projectSite: null,
    image: "/zcashkorea.jpg",
    blog: null,
  },
  {
    name: "Zcash Russia",
    flag: "🇷🇺",
    twitter: "https://x.com/ZcashRussia?s=20",
    description: "Zcash community and advocacy in Russia",
    projectSite: null,
    image:
      "https://pbs.twimg.com/profile_images/1678862190051246080/GAloqOL9_400x400.jpg",
    blog: "https://pro.zcash.ru/",
  },
  {
    name: "Zcash Arabia",
    flag: "🇸🇦",
    twitter: "https://x.com/ZcashArabia",
    description: "Zcash community and advocacy in Arabic-speaking regions",
    projectSite: null,
    image: "/zcashArabia.jpg",
    blog: null,
  },
  {
    name: "Zcash Brazil",
    flag: "🇧🇷",
    twitter: "https://x.com/zcashbrazil",
    description: "Zcash community and advocacy in Brazil",
    projectSite: null,
    image:
      "https://pbs.twimg.com/profile_images/2022785112505552896/GtMH0QZr_400x400.jpg",
    blog: null,
  },
  {
    name: "Zcash Ghana",
    flag: "🇬🇭",
    twitter: "https://x.com/ZcashGH",
    description: "Zcash community and advocacy in Ghana",
    projectSite: null,
    image: "/zcashGhana.jpg",
    blog: null,
  },
  {
    name: "Zcash Español",
    flag: "🇪🇸",
    twitter: "https://x.com/zcashesp",
    description: "Zcash community and advocacy in Spanish-speaking regions",
    projectSite: null,
    image:
      "https://pbs.twimg.com/profile_images/2009020983043117056/P33Vac7s_400x400.jpg",
    blog: "https://privacidad.me/@zcashesp",
  },
  {
    name: "Zcash Nigeria",
    flag: "🇳🇬",
    twitter: "https://x.com/ZcashNigeria",
    description: "Zcash community and advocacy in Nigeria",
    projectSite: null,
    image: "/zcashNigeria.jpg",
    blog: null,
  },
  {
    name: "Zcash Ukraine",
    flag: "🇺🇦",
    twitter: "https://x.com/Zcash_ua",
    description: "Zcash community and advocacy in Ukraine",
    projectSite: null,
    image: "/zcashUkraine.jpg",
    blog: null,
  },
  {
    name: "Zcash Turkey",
    flag: "🇹🇷",
    twitter: "https://x.com/ZcashTR",
    description: "Zcash community and advocacy in Turkey",
    projectSite: null,
    image: "/zcashTurkey.jpg",
    blog: null,
  },
  {
    name: "Zcash Kenya",
    flag: "🇰🇪",
    twitter: "https://x.com/ZcashKenya",
    description: "Zcash community and advocacy in Kenya",
    projectSite: null,
    image: "/zcashKenya.jpg",
    blog: null,
  },
  {
    name: "Zcash India",
    flag: "🇮🇳",
    twitter: "https://x.com/ZcashIndia",
    description: "Zcash community and advocacy in India",
    projectSite: "https://zcashindia.org",
    image:
      "https://pbs.twimg.com/profile_images/1982399854014758912/syEzQvXo_400x400.jpg",
    blog: "https://zcashindia.org/blog",
  },
];
