import type { Exchange } from "./exchange";

const exchangesIt: Exchange[] = [
  {
    name: "Binance",
    url: "https://binance.com",
    pairs: "ALL/ZEC",
    support: "Transparent (deposito su indirizzo TEX)",
    depositTime: "20 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    // logo: "/content-images/_unavailable.svg",
    logo: "/content-images/Binance-Icon-Logo.wine-b047212223.svg",
    altText: "Binance Logo",
  },
  {
    name: "Bitfinex",
    url: "https://bitfinex.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "25 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "https://upload.wikimedia.org/wikipedia/en/4/41/Bitfinex_Logo_light.svg",
    altText: "Bitfinex Logo",
  },
  {
    name: "Coinbase",
    url: "https://coinbase.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "150 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "/content-images/coinbase-8643659341.webp",
    altText: "Coinbase Logo",
  },
  {
    name: "Gemini",
    url: "https://gemini.com",
    pairs: "ALL/ZEC",
    support: "Transparent | Prelievo Shielded",
    depositTime: "50 minuti",
    ironwood: "Prelievi schermati supportati, pool non dichiarato",
    logo: "/content-images/Gemini-Symbol-ddd31ee98b.webp",
    altText: "Gemini Custodian Exchange Logo",
  },
  {
    name: "HTX (former Huobi)",
    url: "https://htx.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "35 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c1/HTX_logo.png",
    altText: "HTX Logo",
  },
  {
    name: "Kraken",
    url: "https://kraken.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "60 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "/content-images/kraken-logo-7407ab477f.webp",
    altText: "Kraken Logo",
  },
  {
    name: "KuCoin",
    url: "https://kucoin.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "20 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "/content-images/kucoin-ee0c21f9fd.svg",
    altText: "KuCoin Logo",
  },
  {
    name: "OKEx",
    url: "https://okex.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "25 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/89/Official_logo_of_OKEx.png",
    altText: "OKEx Logo",
  },
  {
    name: "CoinEx",
    url: "https://www.coinex.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "15 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "/content-images/coinex9788-d638d69e3b.webp",
    altText: "CoinEx Logo",
  },
  {
    name: "Bybit",
    url: "https://www.bybit.com",
    pairs: "ALL/ZEC",
    support: "Transparent",
    depositTime: "30 minuti",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "/content-images/t_bybit5549-0c17d6b645.webp",
    altText: "Bybit Logo",
  },
  {
    name: "Robinhood",
    url: "https://robinhood.com",
    pairs: "USD/ZEC | EUR/ZEC",
    support: "Prelievi solo verso indirizzi trasparenti t. I depositi ZEC non sono supportati",
    depositTime: "Depositi non supportati",
    ironwood: "Non applicabile, solo indirizzi trasparenti",
    logo: "/content-images/IMG-5725-7f964c1fdb.webp",
    altText: "Robinhood Logo",
  },
  {
    name: "Backpack",
    url: "https://backpack.exchange",
    pairs: "ZEC/USDC | ZEC-PERP",
    support: "Depositi e prelievi attivi. Tipi di indirizzo non dichiarati",
    depositTime: "Non dichiarato",
    ironwood: "Non dichiarato",
    logo: "/content-images/_unavailable.svg",
    altText: "Backpack Logo",
  },
];

export default exchangesIt;
