export const exploreFolders = [ 
    {
        img: '/Start-02.png',
        description: '',
        name: 'Start_Here',
        url: '/site/Start_Here/Developer_Resources',
    },
    {
        img: '/Tutorials.png',
        description: '',
        name: 'Tutorials',
        url: '/site/tutorials/Buy_ZEC_in_Gemini',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Using_Zcash',
        url: '/site/Using_Zcash/Buying_ZEC',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Guides',
        url: '/site/guides/Free2z_Live',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Zcash_Tech',
        url: '/site/Zcash_Tech/Blockchain_Explorers',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Zcash_Organizations',
        url: '/site/Zcash_Organizations/Electric_Coin_Company',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Zcash_Community',
        url: '/site/Zcash_Community/Arborist_Calls',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'ZFAV_Club',
        url: '/site/ZFAV_Club/AV_Club_Background',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Zcash_Social_Media',
        url: '/site/Zcash_Social_Media/Podcasts',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Privacy_Tools',
        url: '/site/Privacy_Tools/2FA_Hardware_Devices',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Research',
        url: '/site/Research/Social_Media_Data_Collection',
    },
    {
        img: '/getZec.png',
        description: '',
        name: `Glossary_and_FAQs`,
        url: '/site/Glossary_and_FAQs/FAQ',
    },
    {
        img: '/getZec.png',
        description: '',
        name: 'Contribute',
        url: '/site/contribute/Help_build_ZecHub',
    },
]
