// AUTO-GENERATED — ar page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `ar` locale. Regenerate with
// scratchpad/gen_page_titles_loc.py after adding/retitling translated pages.
export const pageTitlesAr: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "الأسئلة الشائعة",
  "site/Glossary_and_FAQs/Gallery": "معرض خلفيات Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "مكتبة Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "أجهزة 2FA المادية",
  "site/Privacy_Tools/Arti_Tor": "Arti: عميل Tor من الجيل التالي بلغة Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "بروتوكول Namada",
  "site/Privacy_Tools/PGP_Encryption": "الخصوصية الجيدة جدًا (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "تطبيقات المراسلة الآمنة",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "لماذا تُعدّ الخصوصية مهمة",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN و dVPN",
  "site/Privacy_Tools/Web_Browsers": "متصفحات الويب",
  "site/Research/Dash_Zcash_Orchard_Integration": "دمج Dash لـ Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "أفضل ممارسات الخصوصية في Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "كشف الجانب المظلم: خوض ملحمة العملة الرقمية للبنك المركزي (CBDC) وسط ظلال المال",
  "site/Research/Social_Media_Data_Collection": "جمع بيانات وسائل التواصل الاجتماعي",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "تتبّع الإشارات المبكرة على السلسلة والاجتماعية لـ Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "منصات الأصول القائمة على المعرفة الصفرية",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "كيف تعمل معاملة Zcash المحمية فعليًا",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "الحقول المنتهية: نظام الأعداد الذي تعيش فيه التشفيريات",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "المنحنيات الإهليلجية: حيث تولد مفاتيح Zcash والالتزامات الخاصة بها",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "التجزئة والالتزامات: الظرف السحري المختوم",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "أشجار Merkle: كيف تتذكر البلوكشين كل ملاحظة",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "براهين المعرفة الصفرية: إثبات أنك على حق من دون أن تقول لماذا",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "البروتوكول المُدرَّع، من البداية إلى النهاية",
  "site/Start_Here/Developer_Resources": "موارد المطورين",
  "site/Start_Here/Development_Fund": "صندوق تطوير Zcash",
  "site/Start_Here/Network_Upgrades": "ترقيات شبكة Zcash",
  "site/Start_Here/New_User_Guide": "دليل المستخدم الجديد لـ Zcash",
  "site/Start_Here/Using_This_Wiki": "استخدام هذا الويكي",
  "site/Start_Here/What_is_ZEC_and_Zcash": "أساسيات Zcash",
  "site/Start_Here/What_is_ZecHub": "ما هو ZecHub؟",
  "site/Start_Here/ZEC_Use_Cases": "أساسيات Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "أساسيات Zcash",
  "site/Start_Here/Zcash_Resources": "موارد Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "مستكشفات البلوكشين",
  "site/Using_Zcash/Buying_ZEC": "الحصول على Zcash",
  "site/Using_Zcash/Creators_and_Tips": "أدوات Zcash لمنشئي المحتوى: منصات الإكراميات والملفات الشخصية",
  "site/Using_Zcash/Custodial_Exchanges": "منصات التداول الوصائية",
  "site/Using_Zcash/Encifher_Swaps": "مبادلة خاصة من SOL/USDC إلى ZEC باستخدام Encrypt.trade",
  "site/Using_Zcash/Faucets": "الصنابير",
  "site/Using_Zcash/Memos": "المذكرات",
  "site/Using_Zcash/Metamask_Snap": "دليل دمج MetaMask Zcash Snap",
  "site/Using_Zcash/Mobile_Top_Ups": "شحن رصيد الهاتف المحمول باستخدام Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "البورصات غير الاحتجازية",
  "site/Using_Zcash/Payment_Processors": "معالجو مدفوعات Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "معرّفات URI لطلب الدفع في Zcash",
  "site/Using_Zcash/Recovering_Funds": "استرداد أموال محفظة Zcash",
  "site/Using_Zcash/Shielded_Pools": "مجمّعات القيمة في Zcash",
  "site/Using_Zcash/Solswap": "كيفية مبادلة ZEC في محفظة Phantom",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "أماكن لإنفاق ZEC",
  "site/Using_Zcash/Testnet": "شبكة الاختبار لـ Zcash",
  "site/Using_Zcash/Transactions": "المعاملات",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "ما هي عناوين Zcash TEX؟",
  "site/Using_Zcash/Zcash_Mining_Guide": "دليل تعدين Zcash: الانضمام إلى مجمّع تعدين باستخدام أجهزة شخصية",
  "site/Using_Zcash/Zcash_Mining_Pools": "مجمّعات تعدين Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "أدلة للمبدعين",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "أدوات الذكاء الاصطناعي: توليد النصوص والصور والفيديو والصوت (عبر الإنترنت)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "أدوات الذكاء الاصطناعي (محلية، دون اتصال)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "البث المجتمعي باستخدام VDO.Ninja و OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "البداية السريعة: إنشاء مقتطفات Zcon",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "مشاركة الملفات من نظير إلى نظير باستخدام IPFS ومتصفح Brave",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "إعداد البث المباشر",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "نشر موقع على IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "استضافة مستودع GitHub باستخدام IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "إنشاء وترجمة ترجمات الفيديو",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "مدونات المجتمع",
  "site/Zcash_Community/Community_Links": "روابط مجتمع Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "اللجنة الاستشارية لمجتمع Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "خدمة مستودع Github باستخدام IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "نشر موقع ويب على IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "أمان منظومة Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "سفراء Zcash العالميون",
  "site/Zcash_Community/Zcash_Governance": "نظرة عامة على تمويل وحوكمة Zcash",
  "site/Zcash_Community/Zcash_Media": "وسائط Zcash",
  "site/Zcash_Community/Zcash_Podcasts": "البودكاست",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "المنح الاسترجاعية الموجّهة من حاملي العملات",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (الغروب)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "مؤسسة الخصوصية المالية (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/ZKAV": "نادي ZKAV",
  "site/Zcash_Organizations/ZODL": "ZODL (مختبر Zcash للتطوير المفتوح)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "منح مجتمع Zcash",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "من الصفر إلى المعرفة الصفرية: بروتوكول CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "من الصفر إلى المعرفة الصفرية: دوال Hash",
  "site/Zcash_Social_Media/Lelantus": "من الصفر إلى المعرفة الصفرية: بروتوكول Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "من الصفر إلى المعرفة الصفرية: عبارات البذور التذكّرية",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ملخصات حلقات بودكاست ZK",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "بودكاست المعاملات المحمية من Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "بودكاست المعرفة الصفرية",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "بودكاست Zcash على Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "بودكاست Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "بودكاست Zcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "بودكاست PGP للعملات المشفرة",
  "site/Zcash_Social_Media/TEEs": "من الصفر إلى المعرفة الصفرية: بيئات التنفيذ الموثوقة (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "من الصفر إلى المعرفة الصفرية: المعاملات الشفافة مقابل المحمية والعناوين الموحّدة",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "من الصفر إلى المعرفة الصفرية | سلسلة تعليمية",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "العُقد الكاملة",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "عقد Lightwallet في Zcash",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "الأمان ما بعد الكم في Zcash",
  "site/Zcash_Tech/Viewing_Keys": "مفاتيح العرض",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "بروتوكول المصادقة ZAP1",
  "site/Zcash_Tech/Zaino": "مفهرس Zaino",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "الأصول المحمية في Zcash",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "مزامنة محفظة Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "متطلبات النظام وتهيئة الشبكة لـ Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP و ZK-SNARKs",
  "site/Zcash_Use_Cases/About": "استخدام Zcash في العالم الحقيقي",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "قبول المدفوعات كتاجر باستخدام Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "إعداد الخصوصية للمستقلين باستخدام Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "إعداد الخصوصية للصحفيين باستخدام Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "الاحتفاظ بالسجلات باستخدام ZEC المحمي",
  "site/Zcash_Use_Cases/Private_Community_treasury": "شغّل خزينة مجتمعية خاصة باستخدام Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "استقبل التبرعات بشكل خاص باستخدام Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "أرسل الأموال دون ربط هويتك",
  "site/contribute/Community_Infrastructure": "إطار البنية التحتية لمجتمع ZecHub",
  "site/contribute/Contributing_Guide": "المساهمة في ZecHub",
  "site/contribute/Help_build_ZecHub": "ساعد في بناء ZecHub",
  "site/contribute/Style_Guide": "دليل أسلوب ZecHub",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "نشرة ZecWeekly الإخبارية",
  "site/guides/Akash_Network_Zcashd": "نشر zcashd على Akash عبر Console",
  "site/guides/Akash_Network_Zebra": "كيفية تشغيل Zebra على Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server مع دعم Zcash: دليل كامل للتثبيت والتكامل",
  "site/guides/Blockchain_Explorers": "مستكشفات البلوكشين",
  "site/guides/Brave_Wallet_Guide": "كيفية إرسال واستلام Zcash المحمي (ZEC) باستخدام Brave Wallet: دليل خصوصية خطوة بخطوة",
  "site/guides/Free2Z_Livestreaming": "البث المباشر على Free2Z",
  "site/guides/Free2z_Live": "Free2z: إعداد الحساب + دليل البث المباشر",
  "site/guides/Hardened_Zebrad": "عقدة Zebra الكاملة المُحصّنة",
  "site/guides/Keystone_Zashi": "دليل مستخدم Keystone Zashi",
  "site/guides/Maya_Protocol": "منصة Maya للتبادل اللامركزي",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "دليل الترحيل: من zcashd إلى Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "كتابي التدريبي الأول عن Zcash",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: دليل عقدة كاملة zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd مع Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "دليل Raspberry Pi 4 لتشغيل Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift و Zcash: تداول لامركزي يضع الخصوصية أولاً",
  "site/guides/Using_ZEC_Privately": "استخدام ZEC بشكل خاص",
  "site/guides/Using_ZEC_in_DeFi": "استخدام Zcash في DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "تصوّر عناوين Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "تصوّر شبكة Zcash",
  "site/guides/Ywallet_FROST_Demo": "عرض توضيحي لـ Ywallet وFROST",
  "site/guides/Zcash_Devtool": "أداة Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "مقترحات تحسين Zcash",
  "site/guides/Zenith_Installation": "تثبيت محفظة Zenith GUI ذات العقدة الكاملة",
  "site/guides/Zero-Knowledge_vs_Decoys": "المعرفة الصفرية مقابل الأنظمة القائمة على الطُعم",
  "site/guides/Zgo_Payment_Processor": "معالج الدفع ZGo: قبول Zcash دون وصاية",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "دليل Zkool للمعاملات متعددة التوقيع",
  "site/guides/coinholder_log_parser/help": "تصفية سجل الانتخابات",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "عرض Ywallet التوضيحي لـ FROST",
  "site/guides/multisigdemo/MultiSigDemo": "عرض توضيحي لـ MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "يوم الورشة 3",
  "site/tutorials/Exchanges": "منصات تداول Zcash",
  "site/tutorials/Full_Node_Tutorials": "دروس العقدة الكاملة",
  "site/tutorials/Using_Zcash": "دروس تعليمية لاستخدام Zcash",
  "site/tutorials/Wallet_Tutorials": "دروس تعليمية لمحافظ Zcash",
  "site/tutorials/shieldedNewsletter/readme": "النشرات الإخبارية المحمية",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
