// AUTO-GENERATED — ko page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesKo: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "자주 묻는 질문",
  "site/Glossary_and_FAQs/Gallery": "Zcash 벽지 갤러리",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash 라이브러리",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA 하드웨어 장치",
  "site/Privacy_Tools/Arti_Tor": "아르티: Rust로 작성된 차세대 Tor 클라이언트",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada 프로토콜",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "펜룸브라",
  "site/Privacy_Tools/Secure_Messengers": "보안 메신저 앱",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "왜 프라이버시가 중요한가",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN 및 dVPN",
  "site/Privacy_Tools/Web_Browsers": "웹 브라우저",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash의 Zcash Orchard 통합",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada 프라이버시 최고 실천 가이드",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "어둠의 편에서 드러나다: 금융의 그림자 속 CBDC(중앙은행 디지털 통화) 여정을 탐색하다",
  "site/Research/Social_Media_Data_Collection": "소셜 미디어 데이터 수집",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "초기 블록체인 및 소셜 신호 추적을 통한 Zcash(ZEC) 분석",
  "site/Research/ZK_Shielded_Asset_Platforms": "제로 지식 자산 플랫폼",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Shielded Zcash 트랜잭션이 실제로 작동하는 방식",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "유한체: 암호학이 살아가는 수 체계",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "타원 곡선: Zcash의 키와 커밋먼트가 태어나는 곳",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "해싱과 커밋먼트: 마법 같은 봉인된 편지",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "머클 트리: 블록체인은 어떻게 모든 노트를 기억하는가?",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "영지식 증명: 이유를 말하지 않고도 자신이 옳다는 것을 증명하기",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "쉴드 프로토콜, 엔드 투 엔드",
  "site/Start_Here/Developer_Resources": "개발자 자료",
  "site/Start_Here/Development_Fund": "Zcash 개발 기금",
  "site/Start_Here/Network_Upgrades": "Zcash 네트워크 업그레이드",
  "site/Start_Here/New_User_Guide": "Zcash 신규 사용자 가이드",
  "site/Start_Here/Using_This_Wiki": "이 위키 사용법",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash 기초",
  "site/Start_Here/What_is_ZecHub": "ZecHub이란 무엇인가요?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash 기초",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash 기초",
  "site/Start_Here/Zcash_Resources": "Zcash 자원",
  "site/Using_Zcash/Blockchain_Explorers": "블록체인 탐색기",
  "site/Using_Zcash/Buying_ZEC": "Zcash 구매 방법",
  "site/Using_Zcash/Creators_and_Tips": "Zcash 크리에이터 도구: 팁 & 프로필 플랫폼",
  "site/Using_Zcash/Custodial_Exchanges": "보관형 거래소",
  "site/Using_Zcash/Encifher_Swaps": "암호화된 SOL/USDC -> ZEC 스왑 사용법: Encrypt.trade",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "메모",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap 통합 가이드",
  "site/Using_Zcash/Mobile_Top_Ups": "Zcash를 사용한 모바일 충전",
  "site/Using_Zcash/Non-Custodial_Exchanges": "비선점형 거래소",
  "site/Using_Zcash/Payment_Processors": "Zcash 결제 처리기",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash 결제 요청 URI",
  "site/Using_Zcash/Recovering_Funds": "Zcash 지갑 자금 복구",
  "site/Using_Zcash/Shielded_Pools": "Zcash 가치 풀",
  "site/Using_Zcash/Solswap": "Phantom 지갑에서 ZEC 교환 방법",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "ZEC를 사용할 수 있는 곳",
  "site/Using_Zcash/Testnet": "Zcash 테스트넷",
  "site/Using_Zcash/Transactions": "거래",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Zcash의 TEX 주소란 무엇인가요?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash 채굴 가이드: 개인 장비로 마이닝 풀에 참여하기",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash 채굴 풀",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "창작자 가이드",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI 도구: 텍스트, 이미지, 영상, 오디오 생성 (온라인)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI 도구 (로컬, 오프라인)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "VDO.Ninja와 OBS Studio를 이용한 커뮤니티 라이브 방송",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "빠른 시작: Zcon 하이라이트 만들기",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "IPFS와 브레이브 브라우저를 이용한 P2P 파일 공유",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "라이브 스트리밍 설정",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "IPFS에 사이트 게시",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "IPFS를 사용하여 GitHub 저장소 제공",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "영상 자막 생성 및 번역",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "커뮤니티 블로그",
  "site/Zcash_Community/Community_Links": "Zcash 커뮤니티 링크",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash 커뮤니티 자문 패널",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "IPFS를 사용하여 Github 저장소 제공",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "IPFS 상에 웹사이트 게시",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash 생태계 보안",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash 글로벌 대사",
  "site/Zcash_Community/Zcash_Governance": "Zcash 자금 조달 및 거버넌스 개요",
  "site/Zcash_Community/Zcash_Media": "Zcash 미디어",
  "site/Zcash_Community/Zcash_Podcasts": "팟캐스트",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "코인홀더 주도 후향성 보조금 프로그램",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "재정 프라이버시 펀데이션 (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV 클럽",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "제로에서 제로 지식: 크립토노트 프로토콜",
  "site/Zcash_Social_Media/Hash_Functions": "제로에서 제로 지식: 해시 함수",
  "site/Zcash_Social_Media/Lelantus": "제로에서 제로 지식으로: Lelantus 프로토콜",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "제로에서 제로 지식: Mnemonic Seed Phrases (암호구문)",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK 팟캐스트 에피소드 요약",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Forsight Institute의 Shielded Transactions 팟캐스트",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "제로 커널 팟캐스트",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "디지털 현금 네트워크의 Zcash 팟캐스트",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z 팟캐스트",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast 팟캐스트",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "암호화폐를 위한 PGP 팟캐스트",
  "site/Zcash_Social_Media/TEEs": "제로에서 제로 지식: 신뢰 실행 환경(TEE)",
  "site/Zcash_Social_Media/Zcash_Addresses": "제로에서 제로 지식: 투명한 거래 vs 암호화된 거래 및 통합 주소",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero to Zero Knowledge | 교육 시리즈",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "전체 노드",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash 라이트월릿 노드",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - 페퍼 싱크",
  "site/Zcash_Tech/Post_Quantum_Security": "양자 컴퓨터에 대한 Zcash의 보안",
  "site/Zcash_Tech/Viewing_Keys": "조회 키",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 인증 프로토콜",
  "site/Zcash_Tech/Zaino": "Zaino 인덱서",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash 지갑 동기화",
  "site/Zcash_Tech/Zebra_Full_Node": "Zebra 시스템 요구 사항 및 네트워크 구성",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "현실 세계에서 Zcash 사용하기",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "상인으로서 Zcash를 사용해 결제 수락하기",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "프리랜서의 개인정보 보호 설정 방법 (Zcash 사용)",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "기자의 프라이버시 설정 방법: Zcash 사용",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "shielded ZEC을 사용한 기록 보관",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Zcash를 사용하여 비공개 커뮤니티 펀드 운영",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Zcash를 사용하여 기부금을 비공개로 수령하기",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "신분을 드러내지 않고 돈 보내기",
  "site/contribute/Community_Infrastructure": "ZecHub 커뮤니티 인프라 프레임워크",
  "site/contribute/Contributing_Guide": "ZecHub에 기여하기",
  "site/contribute/Help_build_ZecHub": "ZecHub 기여하기",
  "site/contribute/Style_Guide": "ZecHub 스타일 가이드",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly 뉴스레터",
  "site/guides/Akash_Network_Zcashd": "Akash를 통해 zcashd 배포하기 (콘솔을 이용한 방법)",
  "site/guides/Akash_Network_Zebra": "Akash 네트워크에서 Zebra 실행 방법",
  "site/guides/Avalanche_RedBridge": "Zcash 애발랑스 레드브리지",
  "site/guides/BTCPayServer_Zcash_Plugin": "Zcash 지원 BTCPay Server: 전체 설치 및 통합 가이드",
  "site/guides/Blockchain_Explorers": "블록체인 탐색기",
  "site/guides/Brave_Wallet_Guide": "Brave Wallet으로 Shielded Zcash (ZEC) 보내고 받기: 단계별 프라이버시 가이드",
  "site/guides/Free2Z_Livestreaming": "Free2Z에서 라이브 스트리밍하기",
  "site/guides/Free2z_Live": "Free2Z: 계정 설정 + 라이브 스트리밍 튜토리얼",
  "site/guides/Hardened_Zebrad": "강화된 Zebra 전체 노드",
  "site/guides/Keystone_Zashi": "키스톤 Zashi 사용자 가이드",
  "site/guides/Maya_Protocol": "Maya 탈중앙화 거래소",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "마이그레이션 가이드: zcashd에서 Zebrad/Zallet로",
  "site/guides/My_First_Zcash_Workbook": "나의 첫 Zcash 워크북",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "라즈베리 파이 4: zcashd 전체 노드 가이드",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd with Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4에서 Zebra 실행 가이드",
  "site/guides/ShapeShift_Zcash": "ShapeShift와 Zcash: 프라이버시 중심의 분산형 거래",
  "site/guides/Using_ZEC_Privately": "ZEC을 비공개로 사용하는 방법",
  "site/guides/Using_ZEC_in_DeFi": "Zcash을 DeFi에서 사용하는 방법",
  "site/guides/Visualizing_Zcash_Addresses": "Zcash 주소 시각화하기",
  "site/guides/Visualizing_the_Zcash_Network": "Zcash 네트워크 시각화",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST 데모",
  "site/guides/Zcash_Devtool": "Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Zcash 개선 제안",
  "site/guides/Zenith_Installation": "Zenith GUI 전체 노드 지갑 설치",
  "site/guides/Zero-Knowledge_vs_Decoys": "제로 지식 증명 vs 유인자 기반 시스템",
  "site/guides/Zgo_Payment_Processor": "ZGo 결제 처리기: 보관 없이 Zcash 수락하기",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool 멀티시그 가이드",
  "site/guides/coinholder_log_parser/help": "선거 로그 필터",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST 데모",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig 예제",
  "site/guides/workshops/zcashContributorWorkshopDay3": "워크숍 3일차",
  "site/tutorials/Exchanges": "Zcash 거래소",
  "site/tutorials/Full_Node_Tutorials": "전체 노드 튜토리얼",
  "site/tutorials/Using_Zcash": "Zcash 사용법 튜토리얼",
  "site/tutorials/Wallet_Tutorials": "Zcash 지갑 튜토리얼",
  "site/tutorials/shieldedNewsletter/readme": "Shielded 뉴스레터",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 베타",
};
