// AUTO-GENERATED — uk page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesUk: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Часті запитання",
  "site/Glossary_and_FAQs/Gallery": "Галерея шпалер Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Бібліотека Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Апаратні пристрої 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti: Tor-клієнт нового покоління на Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Протокол Namada",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Безпечні месенджери",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Чому конфіденційність важлива",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN і dVPN",
  "site/Privacy_Tools/Web_Browsers": "Веббраузери",
  "site/Research/Dash_Zcash_Orchard_Integration": "Інтеграція Dash із Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Найкращі практики приватності в Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Розкриваючи темний бік: подорож одіссеєю цифрової валюти центрального банку (CBDC) серед фінансових тіней",
  "site/Research/Social_Media_Data_Collection": "Збір даних у соціальних мережах",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Відстеження ранніх ончейн- та соціальних сигналів для Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Платформи активів з нульовим розголошенням",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Як насправді працює захищена транзакція Zcash",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Скінченні поля: числова система, у якій живе криптографія",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Еліптичні криві: де народжуються ключі та commitments Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Хешування і комітменти: магічний запечатаний конверт",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Дерева Меркла: як блокчейн пам’ятає кожну ноту",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Докази з нульовим розголошенням: довести, що ти маєш рацію, не кажучи чому",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Shielded Protocol від початку до кінця",
  "site/Start_Here/Developer_Resources": "Ресурси для розробників",
  "site/Start_Here/Development_Fund": "Фонд розвитку Zcash",
  "site/Start_Here/Network_Upgrades": "Оновлення мережі Zcash",
  "site/Start_Here/New_User_Guide": "Посібник для нового користувача Zcash",
  "site/Start_Here/Using_This_Wiki": "Як користуватися цією вікі",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Основи Zcash",
  "site/Start_Here/What_is_ZecHub": "Що таке ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Основи Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Основи Zcash",
  "site/Start_Here/Zcash_Resources": "Ресурси Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Оглядачі блокчейну",
  "site/Using_Zcash/Buying_ZEC": "Отримання Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Інструменти Zcash для творців: чайові та профільні платформи",
  "site/Using_Zcash/Custodial_Exchanges": "Кастодіальні біржі",
  "site/Using_Zcash/Encifher_Swaps": "Приватний обмін SOL/USDC -> ZEC за допомогою Encrypt.trade",
  "site/Using_Zcash/Faucets": "Крани",
  "site/Using_Zcash/Memos": "Нотатки",
  "site/Using_Zcash/Metamask_Snap": "Посібник з інтеграції MetaMask Zcash Snap",
  "site/Using_Zcash/Mobile_Top_Ups": "Поповнення мобільного рахунку за допомогою Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Некастодіальні біржі",
  "site/Using_Zcash/Payment_Processors": "Платіжні процесори Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "URI запиту платежу Zcash",
  "site/Using_Zcash/Recovering_Funds": "Відновлення коштів у гаманці Zcash",
  "site/Using_Zcash/Shielded_Pools": "Пули вартості Zcash",
  "site/Using_Zcash/Solswap": "Як обміняти на ZEC у Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Місця, де можна витратити ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Транзакції",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Що таке TEX-адреси Zcash?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Посібник з майнінгу Zcash: приєднання до майнінг-пулу з особистим обладнанням",
  "site/Using_Zcash/Zcash_Mining_Pools": "Пули для майнінгу Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Посібники для творців",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI-інструменти: генерація тексту, зображень, відео, аудіо (онлайн)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI-інструменти (локальні, офлайн)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Трансляція для спільноти за допомогою VDO.Ninja та OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Швидкий старт: створення Zcon Highlights",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "P2P обмін файлами за допомогою IPFS і Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Налаштування прямих трансляцій",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Опублікуйте сайт в IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Розміщення GitHub-репозиторію через IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Генерація та переклад відеосубтитрів",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Блоги спільноти",
  "site/Zcash_Community/Community_Links": "Посилання спільноти Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Консультативна панель спільноти Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Розміщення Github-репозиторію через IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Опублікуйте вебсайт в IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Безпека екосистеми Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Глобальні амбасадори Zcash",
  "site/Zcash_Community/Zcash_Governance": "Огляд фінансування та управління Zcash",
  "site/Zcash_Community/Zcash_Media": "Медіа Zcash",
  "site/Zcash_Community/Zcash_Podcasts": "Подкасти",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Ретроактивні гранти, керовані власниками монет",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Захід)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Гранти спільноти Zcash",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Від нуля до нульового розголошення: протокол CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "Від нуля до нульового розголошення: Хеш-функції",
  "site/Zcash_Social_Media/Lelantus": "Від нуля до нульового розголошення: протокол Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Від нуля до Zero Knowledge: Мнемонічні сід-фрази",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Підсумки епізодів ZK Podcast",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Подкаст Shielded Transactions від Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Подкаст Zero Knowledge",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Подкаст The Zcash Podcast на Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Подкаст Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Подкаст Zcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "Подкаст PGP для крипто",
  "site/Zcash_Social_Media/TEEs": "Від нуля до нульового розголошення: довірені середовища виконання (TEE)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Від нуля до нульового розголошення: Transparent vs Shielded Transactions і Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Від нуля до нульового розголошення | Освітня серія",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Full Nodes",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Вузли легких гаманців Zcash",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Постквантова безпека в Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Key",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Протокол атестації ZAP1",
  "site/Zcash_Tech/Zaino": "Індексатор Zaino",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Синхронізація гаманця Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Системні вимоги та налаштування мережі для Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP і ZK-SNARKs",
  "site/Zcash_Use_Cases/About": "Використовуйте Zcash у реальному світі",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Приймайте платежі як продавець за допомогою Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Налаштування приватності для фрилансерів із Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Налаштування приватності для журналістів із Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Ведення обліку із shielded ZEC",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Керуйте приватною спільнотною скарбницею за допомогою Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Отримуйте пожертви приватно за допомогою Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Надсилайте гроші, не пов’язуючи їх зі своєю особою",
  "site/contribute/Community_Infrastructure": "Фреймворк інфраструктури спільноти ZecHub",
  "site/contribute/Contributing_Guide": "Участь у ZecHub",
  "site/contribute/Help_build_ZecHub": "Допоможіть розбудовувати ZecHub",
  "site/contribute/Style_Guide": "Посібник зі стилю ZecHub",
  "site/contribute/ZecHub_DAO": "DAO ZecHub",
  "site/contribute/ZecWeekly_Newsletter": "Розсилка ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Розгортання zcashd в Akash через Console",
  "site/guides/Akash_Network_Zebra": "Як запустити Zebra в Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server із підтримкою Zcash: повний посібник зі встановлення та інтеграції",
  "site/guides/Blockchain_Explorers": "Оглядачі блокчейну",
  "site/guides/Brave_Wallet_Guide": "Як надсилати й отримувати захищений Zcash (ZEC) за допомогою Brave Wallet: покроковий посібник із конфіденційності",
  "site/guides/Free2Z_Livestreaming": "Прямі трансляції на Free2Z",
  "site/guides/Free2z_Live": "Free2z: Налаштування акаунта + посібник зі стримів наживо",
  "site/guides/Hardened_Zebrad": "Захищений повний вузол Zebra",
  "site/guides/Keystone_Zashi": "Посібник користувача Keystone Zashi",
  "site/guides/Maya_Protocol": "Децентралізована біржа Maya",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Посібник з міграції: від zcashd до Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Мій перший Zcash: робочий зошит",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: посібник із повного вузла zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd із Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Посібник із запуску Zebra на Raspberry Pi 4",
  "site/guides/ShapeShift_Zcash": "ShapeShift і Zcash: децентралізована торгівля з пріоритетом приватності",
  "site/guides/Using_ZEC_Privately": "Використання ZEC приватно",
  "site/guides/Using_ZEC_in_DeFi": "Використання Zcash у DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Візуалізація адрес Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Візуалізація мережі Zcash",
  "site/guides/Ywallet_FROST_Demo": "Демо Ywallet FROST",
  "site/guides/Zcash_Devtool": "Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Пропозиції щодо вдосконалення Zcash",
  "site/guides/Zenith_Installation": "Встановлення повновузлового GUI-гаманця Zenith",
  "site/guides/Zero-Knowledge_vs_Decoys": "Нульове розголошення знань проти систем на основі приманок",
  "site/guides/Zgo_Payment_Processor": "Платіжний процесор ZGo: приймання Zcash без кастодіального зберігання",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Посібник із мультипідпису в Zkool",
  "site/guides/coinholder_log_parser/help": "Фільтр журналу виборів",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Демонстрація FROST у Ywallet",
  "site/guides/multisigdemo/MultiSigDemo": "Демо MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "День 3 воркшопу",
  "site/tutorials/Exchanges": "Біржі Zcash",
  "site/tutorials/Full_Node_Tutorials": "Підручники з Full Node",
  "site/tutorials/Using_Zcash": "Посібники з використання Zcash",
  "site/tutorials/Wallet_Tutorials": "Посібники з гаманців Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Екрановані розсилки",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
