// AUTO-GENERATED — ee page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesEe: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Nya Siwo Wobia Enuenu",
  "site/Glossary_and_FAQs/Gallery": "Zcash Wallpaper ƒe Nukpɔƒe",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash Agbalẽdzraɖoƒe",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA Hardware Dɔwɔnuwo",
  "site/Privacy_Tools/Arti_Tor": "Arti: Dzidzime si kplɔe ɖo Tor Asitsalawo le Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS ƒe dɔwɔwɔ",
  "site/Privacy_Tools/Namada_Protocol": "Namada ƒe Ðoɖowɔɖi",
  "site/Privacy_Tools/PGP_Encryption": "Adzamenyawo Gbɔkpɔkpɔ Nyui Dzeani (PGP) .",
  "site/Privacy_Tools/Penumbra": "Penumbra ƒe agbalẽ",
  "site/Privacy_Tools/Secure_Messengers": "Dɔla Siwo Le Dedie",
  "site/Privacy_Tools/Shade_Protocol": "Vɔvɔli ƒe Ðoɖowɔɖi",
  "site/Privacy_Tools/Tor_and_I2P": "Nusita Ameŋunyatakakawo Ŋuti Nyatakaka Le Vevie",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN ƒe dɔwɔwɔ",
  "site/Privacy_Tools/Web_Browsers": "Nyatakakadzraɖoƒewo ƒe Nyatakakadzraɖoƒewo",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash Integration of Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada Ameŋunyatakakawo Ŋuti Nuwɔna Nyuitɔwo",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Viviti ƒe Akpa la Ðeɖe Ðe Go: Mɔzɔzɔ le Central Bank Digital Currency (CBDC) Odyssey me le Ganyawo ƒe Vɔvɔliwo Me",
  "site/Research/Social_Media_Data_Collection": "Hadomegbenɔnɔ Ŋuti Nyatakakawo Nuƒoƒoƒu",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Tracking Gbãtɔ On-kɔsɔkɔsɔ & Hadome Dzesiwo na Zcash (ZEC) .",
  "site/Research/ZK_Shielded_Asset_Platforms": "Sidzedze Zero Nunɔamesiwo ƒe Mɔ̃wo",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Alesi Zcash ƒe Asitsatsa Si Wotsɔ Akpoxɔnu Wɔe Wɔa Dɔe Le Nyateƒee",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Agble Siwo Seɖoƒe Seɖoƒe Le: Xexlẽdzesiwo ƒe Ðoɖo Si Me Nyawo Ɣaɣla Le",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Elliptic Curves: Afisi Wodzi Zcash ƒe Safuiwo Kple Adzɔgbeɖeɖewo Le",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing Kple Ðokuitsɔtsɔna: Akunyawɔwɔ ƒe Agbalẽkotoku si Wotre Nu",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Merkle Atiwo: Alesi Blockchain Ðoa ŋku Nuŋlɔɖi Ðesiaɖe Dzii",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Sidzedze Zero-Kpeɖodziwo: Ðo kpe edzi be Èto Eteƒe Evɔ Mègagblɔ Nusitae O",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "The Shielded Protocol, Nuwuwu vaseɖe Nuwuwu",
  "site/Start_Here/Developer_Resources": "Dɔwɔlawo ƒe Dɔwɔnuwo",
  "site/Start_Here/Development_Fund": "Zcash ƒe Ŋgɔyiyi ƒe Gaxɔ",
  "site/Start_Here/Network_Upgrades": "Zcash Network ƒe Ðɔɖɔɖowo",
  "site/Start_Here/New_User_Guide": "Zcash Zãla Yeye ƒe Mɔfiame",
  "site/Start_Here/Using_This_Wiki": "Wiki sia zazã",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash ƒe Gɔmeɖosewo",
  "site/Start_Here/What_is_ZecHub": "Nukae nye ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash ƒe Gɔmeɖosewo",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash ƒe Gɔmeɖosewo",
  "site/Start_Here/Zcash_Resources": "Zcash Dɔwɔnuwo",
  "site/Using_Zcash/Blockchain_Explorers": "Blockchain ƒe Nukulawo",
  "site/Using_Zcash/Buying_ZEC": "Zcash xɔxɔ",
  "site/Using_Zcash/Creators_and_Tips": "Zcash Dɔwɔnuwo na Wɔlawo: Tipping & Profile Platforms",
  "site/Using_Zcash/Custodial_Exchanges": "Custodial Exchanges",
  "site/Using_Zcash/Encifher_Swaps": "Ame ŋutɔ ƒe SOL/USDC -> ZEC Trɔtrɔ Zã Encrypt.trade",
  "site/Using_Zcash/Faucets": "Pɔmpiwo",
  "site/Using_Zcash/Memos": "Nuŋlɔɖiwo",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap ƒe Ðekawɔwɔ Mɔfiame",
  "site/Using_Zcash/Mobile_Top_Ups": "Asitelefon Dzi Top-up Zã Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial Exchanges",
  "site/Using_Zcash/Payment_Processors": "Zcash Fexexe Ŋuti Dɔwɔlawo",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash Fexexe Biabia URIwo",
  "site/Using_Zcash/Recovering_Funds": "Zcash Gakotoku ƒe Gaxɔmenɔnɔ",
  "site/Using_Zcash/Shielded_Pools": "Zcash Asixɔxɔ Tawo",
  "site/Using_Zcash/Solswap": "Alesi Nàɖɔli ZEC le Phantom Wallet me",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Teƒe Siwo Woazã ZEC",
  "site/Using_Zcash/Testnet": "Zcash Dodokpɔ ƒe Nyatakakadzraɖoƒe",
  "site/Using_Zcash/Transactions": "Adzɔnuwo ƒe asitsatsa",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Nukae Nye Zcash TEX Adrɛswo?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash Mining Guide: Tomenukuƒe ƒe Ƒuƒoƒo kple Ame ŋutɔ ƒe Hardware",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash Tomenukuƒewo",
  "site/Using_Zcash/zimppy": "Zimppy.xyz ƒe agbalẽ",
  "site/ZFAV_Club/Guides_for_Creators": "Mɔfiamewo na Wɔlawo",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI dɔwɔnuwo: Nuŋɔŋlɔ, Nɔnɔmetata, Video, Odio wɔwɔ (le Internet dzi)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI dɔwɔnuwo (nutoa me, esiwo mele Internet dzi o) .",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Nutoa me Gbeƒãɖeɖe to VDO.Ninja kple OBS Studio zazã me",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Dzedze Kaba: Zcon ƒe Nya Veviwo Wɔwɔ",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "P2P Faɛl Mamã kple IPFS kple Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Livestream ƒe Ðoɖowɔwɔ",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Ta Nyatakakadzraɖoƒe aɖe ɖe IPFS dzi",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Subɔ GitHub Repo kple IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Video ƒe tanyawo ƒe dzidzime kple gbegɔmeɖeɖe",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Nutoa me Blogwo",
  "site/Zcash_Community/Community_Links": "Zcash Community Links",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk ƒe hadzidzi si nye Zero",
  "site/Zcash_Community/ZCAP": "Zcash Nutome Aɖaŋuɖoha",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Subɔ Github Repo kple IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Ta Nyatakakadzraɖoƒe aɖe ɖe IPFS dzi",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash Nutoa me ƒe Dedienɔnɔ",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash Xexeame Katã ƒe Dutanyanyuigblɔlawo",
  "site/Zcash_Community/Zcash_Governance": "Zcash Gadodo & Dziɖuɖu ƒe Kpɔɖeŋu",
  "site/Zcash_Community/Zcash_Media": "Zcash Nyadzɔdzɔgblɔmɔnuwo",
  "site/Zcash_Community/Zcash_Podcasts": "Podcastwo ƒe nyawo",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes ƒe nyawo",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Gakpekpeɖeŋunana Siwo Wotsɔna Ðoa Nu Megbee Si Gakuxɔlawo Ðo Mɔ Ðo",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Ganyawo Ŋuti Nyatakakawo Ŋuti Dɔwɔƒe (FPF) .",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright ƒe nyawo",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Zero vaseɖe Zero Sidzedze: CryptoNote ƒe Ðoɖowɔɖi",
  "site/Zcash_Social_Media/Hash_Functions": "Zero vaseɖe Zero Sidzedze: Hash Dɔwɔnawo",
  "site/Zcash_Social_Media/Lelantus": "Sidzedze Zero vaseɖe Zero: Lelantus ƒe Ðoɖowɔɖi",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Sidzedze Zero va ɖo Zero: Nuku ƒe Nyagbe Siwo Wotsɔna Ŋkuɖoa Nui",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast Episode ƒe Kpuienyawo",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Shielded Transactions Podcast si Forsight Institute wɔ",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Sidzedze Zero Podcast",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Zcash Podcast si le Digital Cash Network dzi",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z ƒe Podcast la",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast ƒe Podcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP na Crypto Podcast",
  "site/Zcash_Social_Media/TEEs": "Sidzedze Zero vaseɖe Zero: Amewuwu ƒe Nɔnɔme Siwo Dzi Woka Ðo (TEEs) .",
  "site/Zcash_Social_Media/Zcash_Addresses": "Zero vaseɖe Zero Sidzedze: Transparent vs Shielded Transactions & Adrɛs Siwo Wowɔ Ðeka",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero vaseɖe Zero Sidzedze | Hehenana ƒe Nyatakakawo",
  "site/Zcash_Tech/FROST": "FROST ƑE NUÐEÐEŊUTI",
  "site/Zcash_Tech/Full_Nodes": "Nodes Blibowo",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Kekeli ƒe Nuŋlɔɖiwo",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Atadi ƒe Ðoɖowɔwɔ",
  "site/Zcash_Tech/Post_Quantum_Security": "Dedienɔnɔ le Quantum megbe le Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Safuiwo Kpɔkpɔ",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 Ðaseɖiɖi ƒe Ðoɖowɔɖi",
  "site/Zcash_Tech/Zaino": "Zaino ƒe Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash ƒe Nunɔamesi Siwo Wokpɔna",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash Gakotoku ƒe Ðoɖowɔwɔ",
  "site/Zcash_Tech/Zebra_Full_Node": "System ƒe Nudidiwo kple Network ƒe Ðoɖowɔwɔ na Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS ƑE NUÐEÐEŊUTI",
  "site/Zcash_Use_Cases/About": "Zã Zcash le Xexeme Nyateƒetɔ me",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accept Payments as a Merchant with Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Freelancer Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Journalist Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Nuŋlɔɖiwo wɔwɔ kple ZEC si wotsɔ akpoxɔnu wɔe",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Run a Private Community Treasury with Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Receive Donations Privately with Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Send Money Without Linking Your Identity",
  "site/contribute/Community_Infrastructure": "ZecHub Nutome Dɔwɔƒewo ƒe Dɔwɔɖoɖo",
  "site/contribute/Contributing_Guide": "Nudzɔdzɔ na ZecHub",
  "site/contribute/Help_build_ZecHub": "Kpe asi ɖe ZecHub Tutu Ŋu",
  "site/contribute/Style_Guide": "ZecHub ƒe Atsyã Mɔfiame",
  "site/contribute/ZecHub_DAO": "ZecHub DAO ƒe amegã",
  "site/contribute/ZecWeekly_Newsletter": "ZecKwasiɖa sia Kwasiɖa ƒe Nyadzɔdzɔgbalẽ",
  "site/guides/Akash_Network_Zcashd": "Deploying zcashd to Akash via Console",
  "site/guides/Akash_Network_Zebra": "Alesi woawɔ Zebra le Akash Network dzi",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche ƒe Tɔdzisasrã Dzĩ",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server kple Zcash Kpekpeɖeŋu: Bliboe ƒe Ðoɖowɔwɔ kple Ðekawɔwɔ Mɔfiame",
  "site/guides/Blockchain_Explorers": "Blockchain ƒe Nukulawo",
  "site/guides/Brave_Wallet_Guide": "Alesi Nàɖo Shielded Zcash (ZEC) ɖa ahaxɔe kple Brave Wallet: Afɔɖeɖe ɖesiaɖe ƒe Ameŋunyatakakawo Ŋuti Mɔfiame",
  "site/guides/Free2Z_Livestreaming": "Livestreaming le Free2Z dzi",
  "site/guides/Free2z_Live": "Free2z: Akɔntabubu ƒe ɖoɖowɔwɔ + Livestream ƒe nufiame",
  "site/guides/Hardened_Zebrad": "Zebra Sesẽe Blibo Node",
  "site/guides/Keystone_Zashi": "Keystone Zashi Zãla ƒe Mɔfiame",
  "site/guides/Maya_Protocol": "Mayatɔwo ƒe Asitsatsa le Dɔwɔƒewo",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Ʋuʋu ƒe Mɔfiame: Tso zcashd dzi yi Zebrad/Zallet dzi",
  "site/guides/My_First_Zcash_Workbook": "Nye Zcash Dɔwɔgbalẽ Gbãtɔ",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: zcashd Node ƒe mɔfiame blibo aɖe",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd kple Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4 Mɔfiame na Zebra Duƒuƒu",
  "site/guides/ShapeShift_Zcash": "ShapeShift kple Zcash: Adzamenyawo-Gbãtɔ Decentralized Asitsatsa",
  "site/guides/Using_ZEC_Privately": "ZEC zazã, le ame ŋutɔ gbɔ",
  "site/guides/Using_ZEC_in_DeFi": "Zcash zazã le DeFi me",
  "site/guides/Visualizing_Zcash_Addresses": "Zcash Adrɛswo Kpɔkpɔ le susu me",
  "site/guides/Visualizing_the_Zcash_Network": "Zcash Network la kpɔkpɔ le susu me",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST ƒe wɔwɔfia",
  "site/guides/Zcash_Devtool": "Zcash Devtool ƒe dɔwɔnua",
  "site/guides/Zcash_Improvement_Proposals": "Zcash ƒe Ŋgɔyiyi ƒe Aɖaŋuɖoɖowo",
  "site/guides/Zenith_Installation": "Zenith GUI Blibo Node Gakotoku ƒe Ðoɖowɔwɔ",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Sidzedze vs Decoy si wotu ɖe Systems dzi",
  "site/guides/Zgo_Payment_Processor": "ZGo Fexexe Dɔwɔƒe: Zcash Xɔxɔ Vidzikpɔkpɔ Manɔmee",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig Mɔfiame",
  "site/guides/coinholder_log_parser/help": "Tiatiawɔblɔɖe ƒe Nyatakakadzraɖoƒe",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST ƒe wɔwɔfia",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig ƒe wɔwɔfia",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Dɔwɔƒe ƒe Ŋkeke 3 lia",
  "site/tutorials/Exchanges": "Zcash ƒe Asitɔtrɔwo",
  "site/tutorials/Full_Node_Tutorials": "Node Nufiame Blibowo",
  "site/tutorials/Using_Zcash": "Nufiamewo na Zcash Zazã",
  "site/tutorials/Wallet_Tutorials": "Zcash Gakotoku ƒe Nufiamewo",
  "site/tutorials/shieldedNewsletter/readme": "Nyadzɔdzɔgbalẽ Siwo Wotsɔ Akpoxɔnu Wɔe",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta ƒe xexlẽme",
};
