// AUTO-GENERATED — sw page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesSw: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Maswali Yanayoulizwa Mara Nyingi",
  "site/Glossary_and_FAQs/Gallery": "Zcash Wallpaper Gallery",
  "site/Glossary_and_FAQs/Zcash_Library": "Maktaba ya Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA Vifaa vya vifaa",
  "site/Privacy_Tools/Arti_Tor": "Arti: Kizazi kijacho Tor mteja katika kutu",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Itifaki ya Namada",
  "site/Privacy_Tools/PGP_Encryption": "Faragha Nzuri Sana (PGP)",
  "site/Privacy_Tools/Penumbra": "Kivuli",
  "site/Privacy_Tools/Secure_Messengers": "Wajumbe Wenye Kutegemeka",
  "site/Privacy_Tools/Shade_Protocol": "Shade Itifaki",
  "site/Privacy_Tools/Tor_and_I2P": "Kwa Nini Faragha Ni ya Maana",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Vivinjari vya Mtandao",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash Ushirikiano wa Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada faragha Mazoea Bora",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Kufunua Upande wa Giza: Kuzunguka Fedha ya Dijiti ya Benki Kuu (CBDC) Odyssey Kati ya Vivuli vya Fedha",
  "site/Research/Social_Media_Data_Collection": "Kukusanya Takwimu za Media ya Jamii",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Kufuatilia mapema On-chain & Social Signals kwa Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Zero maarifa mali majukwaa",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Jinsi Usafirishaji wa Zcash Unavyofanya Kazi",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Finite Fields: Nambari System Cryptography Anaishi Katika",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Elliptic Curves: Ambapo Zcash ya funguo na ahadi ni kuzaliwa",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Kushiriki na ahadi: bahasha ya kichawi iliyofungwa",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Miti ya Merkle: Jinsi blockchain inakumbuka kila noti",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Uthibitisho wa Ujuzi-Zero: Kuthibitisha Wewe ni haki bila kusema kwa nini",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Itifaki Iliyohifadhiwa, Mwisho kwa Mwisho",
  "site/Start_Here/Developer_Resources": "Watengenezaji Resources",
  "site/Start_Here/Development_Fund": "Zcash Mfuko wa Maendeleo",
  "site/Start_Here/Network_Upgrades": "Zcash Network Upgrades",
  "site/Start_Here/New_User_Guide": "Zcash Mwongozo New User",
  "site/Start_Here/Using_This_Wiki": "Kutumia Wiki hii",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash Msingi",
  "site/Start_Here/What_is_ZecHub": "ZecHub ni nini?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash Msingi",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash Msingi",
  "site/Start_Here/Zcash_Resources": "Zcash Rasilimali",
  "site/Using_Zcash/Blockchain_Explorers": "Wachunguzi wa blockchain",
  "site/Using_Zcash/Buying_ZEC": "Kupata Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Zcash Tools for Creators: Tipping & Profile Platforms (Zana za Zcash kwa Watengenezaji: Vipengee na Majukwaa ya Profile)",
  "site/Using_Zcash/Custodial_Exchanges": "Custodial Exchanges",
  "site/Using_Zcash/Encifher_Swaps": "Private SOL/USDC -> ZEC Swap Using Encrypt.trade",
  "site/Using_Zcash/Faucets": "Mabomba",
  "site/Using_Zcash/Memos": "Memo",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap Mwongozo wa Ushirikiano",
  "site/Using_Zcash/Mobile_Top_Ups": "Simu ya Mkono Kuongeza Kutumia Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial Exchanges",
  "site/Using_Zcash/Payment_Processors": "Zcash Malipo Processors",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash Malipo ya Ombi URI",
  "site/Using_Zcash/Recovering_Funds": "Zcash Wallet Fund Ufufuzi",
  "site/Using_Zcash/Shielded_Pools": "Zcash Thamani Pools",
  "site/Using_Zcash/Solswap": "Jinsi ya kubadilishana kwa ZEC katika Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Maeneo ya Kutumia ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Shughuli",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Ni nini Zcash TEX Anwani?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash Mining Guide: Kujiunga na madini pool na vifaa binafsi",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash Mining Maziwa",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Miongozo kwa Waumbaji",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI zana: Nakala, Picha, Video, Audio kuzalisha (online)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI zana (kijijini, nje ya mtandao)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Community Broadcasting kutumia VDO.Ninja na OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Quick Start: Kujenga Zcon Highlights",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "Ushirikiano wa faili ya P2P na IPFS na Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Kuweka LiveStream",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Kuchapisha Site juu ya IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Kutumikia GitHub Repo na IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Kizazi cha video ya subtitle na tafsiri",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Blogu za Jumuiya",
  "site/Zcash_Community/Community_Links": "Zcash Community Links",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Jopo la Ushauri wa Jumuiya ya Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Kutumikia Github Repo na IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Kuchapisha Website juu ya IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash Ecosystem Usalama",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash Global Mabalozi",
  "site/Zcash_Community/Zcash_Governance": "Zcash Funding & Utawala Maelezo ya jumla",
  "site/Zcash_Community/Zcash_Media": "Zcash Media",
  "site/Zcash_Community/Zcash_Podcasts": "Podcasts",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Sauti za Zcon",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Mikopo ya Retroactive inayoelekezwa kwa Mmiliki wa Sarafu",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Msingi wa Faragha ya Fedha (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Zero hadi Zero Maarifa: CryptoNote Itifaki",
  "site/Zcash_Social_Media/Hash_Functions": "Zero kwa Zero Maarifa: Hash Kazi",
  "site/Zcash_Social_Media/Lelantus": "Zero hadi Zero Maarifa: Lelantus Itifaki",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Zero hadi Zero Maarifa: Mnemonic Seed Maneno",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast Kipindi Muhtasari",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Shielded Transactions Podcast na Taasisi ya Forsight",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Maarifa Zero Podcast",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Zcash Podcast kwenye Mtandao wa Fedha za Dijiti",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z Podcast",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP kwa Crypto Podcast",
  "site/Zcash_Social_Media/TEEs": "Zero kwa Zero Maarifa: Trusted Utekelezaji Mazingira (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Zero hadi Zero Maarifa: Uwazi dhidi ya Shielded Transactions & Unified Anwani",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero kwa Zero Maarifa. Series Elimu",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nodes kamili",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Nodes Lightwallet",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Post-Quantum Usalama katika Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Kuangalia funguo",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 uthibitisho Itifaki",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Mali",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash Wallet Syncing",
  "site/Zcash_Tech/Zebra_Full_Node": "Mahitaji ya Mfumo na Configuration Network kwa Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Tumia Zcash katika Dunia Halisi",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accept Payments as a Merchant with Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Freelancer Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Journalist Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Kuweka kumbukumbu na ZEC ulinzi",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Run a Private Community Treasury with Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Receive Donations Privately with Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Send Money Without Linking Your Identity",
  "site/contribute/Community_Infrastructure": "ZecHub Jamii Miundombinu Mfumo",
  "site/contribute/Contributing_Guide": "Kuchangia ZecHub",
  "site/contribute/Help_build_ZecHub": "Kusaidia Kujenga ZecHub",
  "site/contribute/Style_Guide": "ZecHub Mwongozo Style",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly jarida",
  "site/guides/Akash_Network_Zcashd": "Kupeleka zcashd kwa Akash kupitia Console",
  "site/guides/Akash_Network_Zebra": "Jinsi ya kuendesha Zebra juu ya Mtandao Akash",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server na Zcash Support: Full Ufungaji na ushirikiano Guide",
  "site/guides/Blockchain_Explorers": "Wachunguzi wa blockchain",
  "site/guides/Brave_Wallet_Guide": "Jinsi ya kutuma na kupokea Zcash Shielded (ZEC) na Brave Wallet: Mwongozo wa faragha wa hatua kwa hatua",
  "site/guides/Free2Z_Livestreaming": "Streaming moja kwa moja kwenye Free2Z",
  "site/guides/Free2z_Live": "Free2z: Usanidi wa Akaunti + Mafunzo ya Kuishi",
  "site/guides/Hardened_Zebrad": "Mdudu wa Zebra Aliyefanywa Mgumu",
  "site/guides/Keystone_Zashi": "Keystone Zashi User Guide",
  "site/guides/Maya_Protocol": "Maya Decentralized Kubadilishana",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Mwongozo wa uhamiaji: Kutoka zcashd kwa Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Kitabu Changu cha Kwanza cha Kazi cha Zcash",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: a  zcashd  Full node mwongozo",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd na Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4 Mwongozo kwa Running Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift na Zcash: Faragha-Kwanza Decentralized Trading",
  "site/guides/Using_ZEC_Privately": "Kutumia ZEC, binafsi",
  "site/guides/Using_ZEC_in_DeFi": "Kutumia Zcash katika DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Kuona Anwani za Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Kuona Network Zcash",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST demo",
  "site/guides/Zcash_Devtool": "Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Mapendekezo ya Uboreshaji wa Zcash",
  "site/guides/Zenith_Installation": "Zenith GUI Full Node Wallet Ufungaji",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Ujuzi dhidi ya Decoy mifumo ya msingi",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: Kukubali Zcash Bila Uhifadhi",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad) ((zaino) ((zingo-cli)",
  "site/guides/Zkool_Multisig": "Mwongozo wa Zkool Multisig",
  "site/guides/coinholder_log_parser/help": "Kichujio cha Kumbukumbu ya Uchaguzi",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST demo",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig Demo",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Warsha Siku ya 3",
  "site/tutorials/Exchanges": "Kubadilishana Zcash",
  "site/tutorials/Full_Node_Tutorials": "Full Node Mafunzo",
  "site/tutorials/Using_Zcash": "Tutorials kwa ajili ya kutumia Zcash",
  "site/tutorials/Wallet_Tutorials": "Zcash Wallet Mafunzo",
  "site/tutorials/shieldedNewsletter/readme": "Barua za Habari Zilizohifadhiwa",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
