// AUTO-GENERATED — hi page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesHi: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "अक्सर पूछे जाने वाले प्रश्न",
  "site/Glossary_and_FAQs/Gallery": "Zcash Wallpaper Gallery",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash Library",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA हार्डवेयर डिवाइस",
  "site/Privacy_Tools/Arti_Tor": "Arti: Rust में अगली पीढ़ी का Tor Client",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada Protocol",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "सुरक्षित मैसेंजर",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "गोपनीयता क्यों महत्वपूर्ण है",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Web Browsers",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash द्वारा Zcash Orchard का इंटीग्रेशन",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada गोपनीयता के लिए सर्वोत्तम व्यवहार",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "अंधेरे पक्ष का खुलासा: वित्तीय छायाओं के बीच Central Bank Digital Currency (CBDC) की यात्रा को समझना",
  "site/Research/Social_Media_Data_Collection": "सोशल मीडिया डेटा संग्रह",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Zcash (ZEC) के लिए शुरुआती ऑन-chain और सोशल संकेतों का ट्रैक रखना",
  "site/Research/ZK_Shielded_Asset_Platforms": "Zero Knowledge एसेट प्लेटफ़ॉर्म",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "एक Shielded Zcash लेन-देन वास्तव में कैसे काम करता है",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "सांत क्षेत्र: वह संख्या-प्रणाली जिसमें क्रिप्टोग्राफी रहती है",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "एलिप्टिक कर्व्स: जहाँ Zcash की Keys और Commitments जन्म लेते हैं",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing और Commitments: जादुई सीलबंद लिफाफा",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Merkle Trees: blockchain हर नोट को कैसे याद रखता है",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Zero-Knowledge Proofs: बिना यह बताए कि क्यों, यह साबित करना कि आप सही हैं",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Shielded Protocol, शुरू से अंत तक",
  "site/Start_Here/Developer_Resources": "डेवलपर संसाधन",
  "site/Start_Here/Development_Fund": "Zcash विकास निधि",
  "site/Start_Here/Network_Upgrades": "Zcash Network Upgrades",
  "site/Start_Here/New_User_Guide": "Zcash नए उपयोगकर्ता मार्गदर्शिका",
  "site/Start_Here/Using_This_Wiki": "इस Wiki का उपयोग",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash की मूल बातें",
  "site/Start_Here/What_is_ZecHub": "ZecHub क्या है?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash की मूल बातें",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash की मूल बातें",
  "site/Start_Here/Zcash_Resources": "Zcash संसाधन",
  "site/Using_Zcash/Blockchain_Explorers": "Blockchain Explorers",
  "site/Using_Zcash/Buying_ZEC": "Zcash प्राप्त करना",
  "site/Using_Zcash/Creators_and_Tips": "रचनाकारों के लिए Zcash Tools: Tipping और Profile Platforms",
  "site/Using_Zcash/Custodial_Exchanges": "कस्टोडियल एक्सचेंज",
  "site/Using_Zcash/Encifher_Swaps": "Encrypt.trade का उपयोग करके निजी SOL/USDC -> ZEC स्वैप",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "मेमो",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap एकीकरण मार्गदर्शिका",
  "site/Using_Zcash/Mobile_Top_Ups": "Zcash का उपयोग करके मोबाइल टॉप-अप",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial एक्सचेंज",
  "site/Using_Zcash/Payment_Processors": "Zcash भुगतान प्रोसेसर",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash भुगतान अनुरोध URIs",
  "site/Using_Zcash/Recovering_Funds": "Zcash वॉलेट फंड रिकवरी",
  "site/Using_Zcash/Shielded_Pools": "Zcash वैल्यू पूल्स",
  "site/Using_Zcash/Solswap": "Phantom Wallet में ZEC के लिए Swap कैसे करें",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "ZEC खर्च करने की जगहें",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "लेनदेन",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Zcash TEX पते क्या हैं?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash माइनिंग गाइड: व्यक्तिगत हार्डवेयर के साथ एक माइनिंग पूल में शामिल होना",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash माइनिंग पूल्स",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "निर्माताओं के लिए मार्गदर्शन",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI उपकरण: पाठ, छवि, वीडियो, ऑडियो बनाने (ऑनलाइन)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI उपकरण (स्थानीय, ऑफ़लाइन)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "समुदाय ब्रॉडकास्टिंग VDO.Ninja और OBS Studio के माध्यम से",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "शुरूआत: Zcon हाइलाइट्स बनाना",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "IPFS और Brave ब्राउज़र के साथ P2P फ़ाइल साझा करें",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "लाइव स्ट्रीमिंग के सेटअप",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "IPFS पर एक साइट प्रकाशित करें",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "IPFS के साथ GitHub रिपॉज़िटरी सेवा",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "वीडियो सबटाइटल उत्पन्न करें और अनुवाद करें",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "समुदाय ब्लॉग",
  "site/Zcash_Community/Community_Links": "Zcash समुदाय लिंक",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash समुदाय परामर्श बोर्ड",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "IPFS के साथ गिटहब रिपॉज़िटरी सर्व करें",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "IPFS पर एक वेबसाइट प्रकाशित करें",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash प्रणाली सुरक्षा",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash वैश्विक संचारक",
  "site/Zcash_Community/Zcash_Governance": "Zcash वित्तीय संसाधन एवं प्रशासन का सारांश",
  "site/Zcash_Community/Zcash_Media": "Zcash मीडिया",
  "site/Zcash_Community/Zcash_Podcasts": "पॉडकास्ट",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "कॉइनहोल्डर-निर्देशित पश्चात्प्रदान अनुदान",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "वित्तीय गोपनीयता की संस्थान (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV क्लब",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash समुदाय अनुदान",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "शून्य से ज्ञानहीनता के प्रमाण: क्रिप्टोनोट प्रोटोकॉल",
  "site/Zcash_Social_Media/Hash_Functions": "शून्य से जीरो काउंटलेस: हैश फंक्शन",
  "site/Zcash_Social_Media/Lelantus": "जीरो से ज़ेरो कॉनोव्हेंस: Lelantus प्रोटोकॉल",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Zero से Zero Knowledge तक: Mnemonic Seed Phrases",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK पॉडकास्ट एपिसोड समरेज़",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "छिपी हुई लेनदेन पॉडकास्ट, Forsight Institute द्वारा",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "जीरो कॉनोविडेंस पॉडकास्ट",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "डिजिटल कैश नेटवर्क पर Zcash पॉडकास्ट",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "The Z2Z Podcast",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast पॉडकास्ट",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "क्रिप्टो के लिए PGP पॉडकास्ट",
  "site/Zcash_Social_Media/TEEs": "जीरो से ज़ेरो कॉनोविशन: ट्रस्टेड एक्सीक्यूशन एंवाइरनमेंट (TEE)",
  "site/Zcash_Social_Media/Zcash_Addresses": "शून्य से ज्ञानहीनता तक: प्रसारित बर्ख़ार के विपरीत छिपे हुए लेनदेन & एकीकृत पते",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "जीरो से जीरो कॉनोवलेंस | शैक्षिक श्रृंखला",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "पूर्ण नोड",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Lightwallet Nodes",
  "site/Zcash_Tech/Pepper_Sync": "जिंगो 2.0 - पेपर सिंक",
  "site/Zcash_Tech/Post_Quantum_Security": "क्वांटम सुरक्षा में Zcash",
  "site/Zcash_Tech/Viewing_Keys": "दृश्य कुंजियाँ",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 प्रमाणन प्रोटोकॉल",
  "site/Zcash_Tech/Zaino": "Zaino इंडेक्सर",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash शील्डेड एसेट्स",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash वॉलेट सिंक्रनाइज़ेशन",
  "site/Zcash_Tech/Zebra_Full_Node": "Zebra के लिए प्रणाली आवश्यकता और नेटवर्क संfiguration",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "वास्तविक दुनिया में Zcash के उपयोग",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "व्यापारी के रूप में Zcash से भुगतान स्वीकृत करें",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "फ्रीलांसर के लिए Zcash के साथ गोपनीयता सेटअप",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "पत्रकार के लिए गोपनीयता सेटअप Zcash के साथ",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "शील्डेड ZEC के साथ रिकॉर्ड बनाएँ",
  "site/Zcash_Use_Cases/Private_Community_treasury": "एक निजी समुदाय कोष Zcash के साथ चलाएं",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Zcash के साथ अपनी डोनेशन निजी रूप से प्राप्त करें",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "अपनी पहचान के साथ धन भेजें",
  "site/contribute/Community_Infrastructure": "ZecHub कम्युनिटी इन्फ्रास्ट्रक्चर फ्रेमवर्क",
  "site/contribute/Contributing_Guide": "ZecHub में योगदान",
  "site/contribute/Help_build_ZecHub": "ZecHub बनाने में मदद करें",
  "site/contribute/Style_Guide": "ZecHub शैली मार्गदर्शिका",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly न्यूज़लेटर",
  "site/guides/Akash_Network_Zcashd": "Akash के माध्यम से Console पर zcashd तैनात करना",
  "site/guides/Akash_Network_Zebra": "Akash Network पर Zebra कैसे चलाएँ",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "Zcash सपोर्ट के साथ BTCPay Server: पूर्ण इंस्टॉलेशन और इंटीग्रेशन गाइड",
  "site/guides/Blockchain_Explorers": "Blockchain Explorers",
  "site/guides/Brave_Wallet_Guide": "Brave Wallet के साथ Shielded Zcash (ZEC) कैसे भेजें और प्राप्त करें: चरण-दर-चरण गोपनीयता मार्गदर्शिका",
  "site/guides/Free2Z_Livestreaming": "Free2Z पर Livestreaming",
  "site/guides/Free2z_Live": "Free2z: अकाउंट सेटअप + Livestream ट्यूटोरियल",
  "site/guides/Hardened_Zebrad": "सुदृढ़ीकृत Zebra Full Node",
  "site/guides/Keystone_Zashi": "Keystone Zashi उपयोगकर्ता मार्गदर्शिका",
  "site/guides/Maya_Protocol": "Maya विकेन्द्रीकृत एक्सचेंज",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "माइग्रेशन गाइड: zcashd से Zebrad/Zallet तक",
  "site/guides/My_First_Zcash_Workbook": "मेरा पहला Zcash कार्यपुस्तिका",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: एक zcashd Full node गाइड",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "Zingo के साथ RPi5 Zebra Lightwalletd",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Zebra चलाने के लिए Raspberry Pi 4 गाइड",
  "site/guides/ShapeShift_Zcash": "ShapeShift और Zcash: गोपनीयता-प्रथम विकेंद्रीकृत ट्रेडिंग",
  "site/guides/Using_ZEC_Privately": "ZEC का निजी रूप से उपयोग",
  "site/guides/Using_ZEC_in_DeFi": "DeFi में Zcash का उपयोग",
  "site/guides/Visualizing_Zcash_Addresses": "Zcash पतों का दृश्यात्मक समझना",
  "site/guides/Visualizing_the_Zcash_Network": "Zcash नेटवर्क का विज़ुअलाइज़ेशन",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST डेमो",
  "site/guides/Zcash_Devtool": "Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Zcash सुधार प्रस्ताव",
  "site/guides/Zenith_Installation": "Zenith GUI फुल नोड वॉलेट इंस्टॉलेशन",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Knowledge बनाम Decoy आधारित सिस्टम",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: कस्टडी छोड़े बिना Zcash स्वीकार करना",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig गाइड",
  "site/guides/coinholder_log_parser/help": "चुनाव लॉग फ़िल्टर",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST डेमो",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig डेमो",
  "site/guides/workshops/zcashContributorWorkshopDay3": "कार्यशाला दिवस 3",
  "site/tutorials/Exchanges": "Zcash एक्सचेंज",
  "site/tutorials/Full_Node_Tutorials": "Full Node ट्यूटोरियल्स",
  "site/tutorials/Using_Zcash": "Zcash उपयोग करने के लिए ट्यूटोरियल्स",
  "site/tutorials/Wallet_Tutorials": "Zcash Wallet ट्यूटोरियल्स",
  "site/tutorials/shieldedNewsletter/readme": "Shielded न्यूज़लेटर",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 बीटा",
};
