// AUTO-GENERATED — zh page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `zh` locale. Regenerate with
// scratchpad/gen_page_titles_loc.py after adding/retitling translated pages.
export const pageTitlesZh: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "常见问题",
  "site/Glossary_and_FAQs/Gallery": "Zcash 壁纸画廊",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash 资料库",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA 硬件设备",
  "site/Privacy_Tools/Arti_Tor": "Arti：下一代 Rust Tor 客户端",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada Protocol",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "安全即时通讯工具",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "为什么隐私很重要",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN 与 dVPN",
  "site/Privacy_Tools/Web_Browsers": "Web Browsers",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash 集成 Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada 隐私最佳实践",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "揭开黑暗面：在金融阴影中穿行于中央银行数字货币（CBDC）的奥德赛",
  "site/Research/Social_Media_Data_Collection": "社交媒体数据收集",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "跟踪 Zcash (ZEC) 早期链上与社交信号",
  "site/Research/ZK_Shielded_Asset_Platforms": "零知识资产平台",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "一笔 Shielded Zcash 交易实际上是如何运作的",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "有限域：密码学赖以生存的数字系统",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "椭圆曲线：Zcash 的密钥与承诺诞生之地",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "哈希与承诺：神奇的密封信封",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Merkle Trees：区块链如何记住每一张 Note",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "零知识证明：证明你是对的，而无需说明原因",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "端到端的 Shielded Protocol",
  "site/Start_Here/Developer_Resources": "开发者资源",
  "site/Start_Here/Development_Fund": "Zcash 开发基金",
  "site/Start_Here/Network_Upgrades": "Zcash 网络升级",
  "site/Start_Here/New_User_Guide": "Zcash 新用户指南",
  "site/Start_Here/Using_This_Wiki": "使用本 Wiki",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash 基础",
  "site/Start_Here/What_is_ZecHub": "什么是 ZecHub？",
  "site/Start_Here/ZEC_Use_Cases": "Zcash 基础知识",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash 基础",
  "site/Start_Here/Zcash_Resources": "Zcash 资源",
  "site/Using_Zcash/Blockchain_Explorers": "区块链浏览器",
  "site/Using_Zcash/Buying_ZEC": "获取 Zcash",
  "site/Using_Zcash/Creators_and_Tips": "面向创作者的 Zcash 工具：打赏与个人资料平台",
  "site/Using_Zcash/Custodial_Exchanges": "托管交易所",
  "site/Using_Zcash/Encifher_Swaps": "使用 Encrypt.trade 进行私密的 SOL/USDC -> ZEC 兑换",
  "site/Using_Zcash/Faucets": "水龙头",
  "site/Using_Zcash/Memos": "备忘录",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap 集成指南",
  "site/Using_Zcash/Mobile_Top_Ups": "使用 Zcash 进行手机话费充值",
  "site/Using_Zcash/Non-Custodial_Exchanges": "非托管交易所",
  "site/Using_Zcash/Payment_Processors": "Zcash 支付处理器",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash 支付请求 URI",
  "site/Using_Zcash/Recovering_Funds": "Zcash 钱包资金恢复",
  "site/Using_Zcash/Shielded_Pools": "Zcash 价值池",
  "site/Using_Zcash/Solswap": "如何在 Phantom Wallet 中兑换 ZEC",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "可使用 ZEC 消费的地方",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "交易",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "什么是 Zcash TEX 地址？",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash 挖矿指南：使用个人硬件加入矿池",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash 矿池",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "创作者指南",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI 工具：文本、图像、视频、音频生成（在线）",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI 工具（本地、离线）",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "使用 VDO.Ninja 和 OBS Studio 进行社区直播",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "快速开始：创建 Zcon 精彩片段",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "使用 IPFS 和 Brave Browser 进行 P2P 文件共享",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "直播设置",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "在 IPFS 上发布网站",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "使用 IPFS 提供 GitHub 仓库",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "视频字幕生成与翻译",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "社区博客",
  "site/Zcash_Community/Community_Links": "Zcash 社区链接",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash 社区咨询小组",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "使用 IPFS 提供 Github 仓库",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "在 IPFS 上发布网站",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash 生态安全",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash 全球大使",
  "site/Zcash_Community/Zcash_Governance": "Zcash 资金与治理概览",
  "site/Zcash_Community/Zcash_Media": "Zcash Media",
  "site/Zcash_Community/Zcash_Podcasts": "播客",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Coinholder-Directed Retroactive Grants",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company（落幕）",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash 社区资助",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "从零到零知识：CryptoNote 协议",
  "site/Zcash_Social_Media/Hash_Functions": "从 Zero 到 Zero Knowledge：哈希函数",
  "site/Zcash_Social_Media/Lelantus": "从 Zero 到 Zero Knowledge：Lelantus Protocol",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "从零到零知识：助记词种子短语",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast 剧集摘要",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Forsight Institute 的 Shielded Transactions 播客",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "零知识播客",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Digital Cash Network 上的 The Zcash Podcast",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z 播客",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast 播客",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "Crypto 的 PGP 播客",
  "site/Zcash_Social_Media/TEEs": "从零到零知识：可信执行环境（TEEs）",
  "site/Zcash_Social_Media/Zcash_Addresses": "从零到零知识：Transparent 与 Shielded 交易及 Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "从零到零知识 | 教育系列",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "全节点",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash 轻钱包节点",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Zcash 中的后量子安全",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Key",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 证明协议",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash 屏蔽资产",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash 钱包同步",
  "site/Zcash_Tech/Zebra_Full_Node": "Zebra 的系统要求与网络配置",
  "site/Zcash_Tech/zk_SNARKS": "ZKP 与 ZK-SNARKs",
  "site/Zcash_Use_Cases/About": "在现实世界中使用 Zcash",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "作为商家使用 Zcash 接受付款",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "使用 Zcash 的自由职业者隐私设置",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "使用 Zcash 的记者隐私配置",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "使用屏蔽 ZEC 保存记录",
  "site/Zcash_Use_Cases/Private_Community_treasury": "使用 Zcash 运行私密的社区金库",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "使用 Zcash 私密接收捐赠",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "在不关联身份的情况下发送资金",
  "site/contribute/Community_Infrastructure": "ZecHub 社区基础设施框架",
  "site/contribute/Contributing_Guide": "为 ZecHub 做贡献",
  "site/contribute/Help_build_ZecHub": "帮助建设 ZecHub",
  "site/contribute/Style_Guide": "ZecHub 风格指南",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly Newsletter",
  "site/guides/Akash_Network_Zcashd": "通过 Console 将 zcashd 部署到 Akash",
  "site/guides/Akash_Network_Zebra": "如何在 Akash Network 上运行 Zebra",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "支持 Zcash 的 BTCPay Server：完整安装与集成指南",
  "site/guides/Blockchain_Explorers": "区块链浏览器",
  "site/guides/Brave_Wallet_Guide": "如何使用 Brave Wallet 发送和接收屏蔽式 Zcash (ZEC)：一步步掌握隐私交易",
  "site/guides/Free2Z_Livestreaming": "在 Free2Z 上进行直播",
  "site/guides/Free2z_Live": "Free2z：账户设置 + 直播教程",
  "site/guides/Hardened_Zebrad": "加固的 Zebra 全节点",
  "site/guides/Keystone_Zashi": "Keystone Zashi 用户指南",
  "site/guides/Maya_Protocol": "Maya 去中心化交易所",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "迁移指南：从 zcashd 到 Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "我的第一本 Zcash 练习手册",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4：zcashd 全节点指南",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "搭配 Zingo 的 RPi5 Zebra Lightwalletd",
  "site/guides/Raspberry_pi_4_Zebra_Node": "在 Raspberry Pi 4 上运行 Zebra 指南",
  "site/guides/ShapeShift_Zcash": "ShapeShift 与 Zcash：隐私优先的去中心化交易",
  "site/guides/Using_ZEC_Privately": "私密地使用 ZEC",
  "site/guides/Using_ZEC_in_DeFi": "在 DeFi 中使用 Zcash",
  "site/guides/Visualizing_Zcash_Addresses": "可视化 Zcash 地址",
  "site/guides/Visualizing_the_Zcash_Network": "可视化 Zcash 网络",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST 演示",
  "site/guides/Zcash_Devtool": "Zcash 开发工具",
  "site/guides/Zcash_Improvement_Proposals": "Zcash 改进提案",
  "site/guides/Zenith_Installation": "Zenith GUI 全节点钱包安装",
  "site/guides/Zero-Knowledge_vs_Decoys": "零知识与基于诱饵的系统对比",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor：在不托管资金的情况下接受 Zcash",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool 多重签名指南",
  "site/guides/coinholder_log_parser/help": "选举日志过滤器",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST 演示",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig 演示",
  "site/guides/workshops/zcashContributorWorkshopDay3": "工作坊 第 3 天",
  "site/tutorials/Exchanges": "Zcash 交易所",
  "site/tutorials/Full_Node_Tutorials": "Full Node 教程",
  "site/tutorials/Using_Zcash": "使用 Zcash 的教程",
  "site/tutorials/Wallet_Tutorials": "Zcash 钱包教程",
  "site/tutorials/shieldedNewsletter/readme": "屏蔽新闻简报",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 测试版",
};
