// AUTO-GENERATED — ja page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesJa: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "よくある質問",
  "site/Glossary_and_FAQs/Gallery": "Zcash ワールドペーパー ギャラリー",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash ライブラリ",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2要素認証用ハードウェアデバイス",
  "site/Privacy_Tools/Arti_Tor": "Arti: Rustで構築された次世代のTorクライアント",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada プロトコル",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "ペンンブラ",
  "site/Privacy_Tools/Secure_Messengers": "セキュアメッセンジャーアプリ",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "プライバシーがなぜ重要なのか",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "ブラウザ",
  "site/Research/Dash_Zcash_Orchard_Integration": "DashのZcash Orchard統合",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada プライバシーのベストプラクティス",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "暗黒面の解明：金融の影の中で中央銀行デジタル通貨（CBDC）のオディッセイをナビゲートする",
  "site/Research/Social_Media_Data_Collection": "SNSデータの収集",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "ゼカッシュ（ZEC）の初期オンチェーンおよびソーシャル信号の追跡",
  "site/Research/ZK_Shielded_Asset_Platforms": "零知識資産プラットフォーム",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "シールドされたZcash取引の実際の仕組み",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "有限体: 暗号が生きる数の体系",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "楕円曲線: Zcashの鍵とコミットメントが生まれる場所",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "ハッシュとコミットメント：魔法の封筒",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "マーチェルツリー: ブロックチェーンがノートをすべて記憶する仕組み",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "零知識証明: 正しいことを示すにもかかわらず、理由を言わない方法",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "シールドプロトコル、端から端まで",
  "site/Start_Here/Developer_Resources": "開発者向けリソース",
  "site/Start_Here/Development_Fund": "Zcash開発基金",
  "site/Start_Here/Network_Upgrades": "Zcashネットワークアップグレード",
  "site/Start_Here/New_User_Guide": "Zcash 新規ユーザーのガイド",
  "site/Start_Here/Using_This_Wiki": "このWikiの使い方",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcashの基礎知識",
  "site/Start_Here/What_is_ZecHub": "ZecHubとは？",
  "site/Start_Here/ZEC_Use_Cases": "Zcashの基礎知識",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcashの基礎知識",
  "site/Start_Here/Zcash_Resources": "Zcash リソース",
  "site/Using_Zcash/Blockchain_Explorers": "ブロックチェーンエクスプローラー",
  "site/Using_Zcash/Buying_ZEC": "Zcashの入手方法",
  "site/Using_Zcash/Creators_and_Tips": "Zcashクリエイター向けツール：チップ & プロフィールプラットフォーム",
  "site/Using_Zcash/Custodial_Exchanges": "所有者付き取引所",
  "site/Using_Zcash/Encifher_Swaps": "暗号化されたSOL/USDC → ZEC スワップ方法（Encrypt.tradeを使用）",
  "site/Using_Zcash/Faucets": "Faucet（無料配布サービス）",
  "site/Using_Zcash/Memos": "メモ",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap 統合ガイド",
  "site/Using_Zcash/Mobile_Top_Ups": "Zcashを使用したモバイルチャージ",
  "site/Using_Zcash/Non-Custodial_Exchanges": "非信託型取引所",
  "site/Using_Zcash/Payment_Processors": "Zcash 支払い処理プラットフォーム",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash支払いリクエストURI",
  "site/Using_Zcash/Recovering_Funds": "Zcashウォレット資金の回復",
  "site/Using_Zcash/Shielded_Pools": "Zcash バリューポール",
  "site/Using_Zcash/Solswap": "Phantom WalletでZECに交換する方法",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "ZECを支払える場所",
  "site/Using_Zcash/Testnet": "Zcash テストネット",
  "site/Using_Zcash/Transactions": "トランザクション",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "ZcashのTEXアドレスとは？",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcashマイニングガイド: パーソナルハードウェアでマイニングプールに参加する方法",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcashマイニングプール",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "クリエイター向けガイド",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AIツール: テキスト、画像、動画、音声生成（オンライン）",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AIツール（ローカル、オフライン）",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "VDO.NinjaとOBS Studioを使用したコミュニティ放送",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "クイックスタート: Zconハイライトの作成",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "IPFSとBraveブラウザを使ったP2Pファイル共有",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "ライブ配信のセットアップ",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "IPFS 上でサイトを公開する",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "IPFSを使用してGitHubリポジトリをホストする",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "ビデオの字幕生成と翻訳",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "コミュニティブログ",
  "site/Zcash_Community/Community_Links": "Zcash コミュニティリンク",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash Community Advisory Panel",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "IPFSを使用してGithubリポジトリをホストする",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "IPFS 上にウェブサイトを公開する",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcashエコシステムのセキュリティ",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash グローバルアンバサダー",
  "site/Zcash_Community/Zcash_Governance": "Zcashの資金調達とガバナンス概要",
  "site/Zcash_Community/Zcash_Media": "Zcash メディア",
  "site/Zcash_Community/Zcash_Podcasts": "ポッドキャスト",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "コインホルダー主導の後払い助成金プログラム",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "財務プライバシー財団 (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAVクラブ",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "ゼロからゼロ知識：CryptoNoteプロトコル",
  "site/Zcash_Social_Media/Hash_Functions": "ゼロからゼロ知識: ハッシュ関数",
  "site/Zcash_Social_Media/Lelantus": "ゼロからゼロ知識：Lelantusプロトコル",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "ゼロからゼロ知識へ: ニーモニック・シードフレーズ",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK ポッドキャストエピソード要約",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Forsight InstituteによるShielded Transactionsポッドキャスト",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "ゼロ知識ポッドキャスト",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "デジタルキャッシュネットワークにおけるZcashポッドキャスト",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z ポッドキャスト",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast ポッドキャスト",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "クリプト用PGP ポッドキャスト",
  "site/Zcash_Social_Media/TEEs": "ゼロからゼロ知識：信頼された実行環境（TEE）",
  "site/Zcash_Social_Media/Zcash_Addresses": "ゼロからゼロ知識へ: Transparent vs Shielded Transactions と Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zeroからゼロ知識へ | 教育シリーズ",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "フルノード",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash ライットウォレットノード",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "量子コンピュータに対するZcashのセキュリティ対策",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 認証プロトコル",
  "site/Zcash_Tech/Zaino": "Zaino インデクサー",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets（ZSA）",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcashウォレットの同期",
  "site/Zcash_Tech/Zebra_Full_Node": "Zebraのシステム要件とネットワーク構成",
  "site/Zcash_Tech/zk_SNARKS": "ZKPとZK-SNARKS",
  "site/Zcash_Use_Cases/About": "実世界でZcashを使用する",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "商家としてZcashで支払いを受け取る",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "フリーランスのプライバシー設定方法（Zcashを使用して）",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "ジャーナリスト向けのプライバシー設定とZcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "シールドされたZECの記録の保持",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Zcashを使用してプライベートなコミュニティ財産を運用する",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Zcashで寄付をプライバシー保護して受け取る",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "身分をリンクせずに送金",
  "site/contribute/Community_Infrastructure": "ZecHub コミュニティインフラフレームワーク",
  "site/contribute/Contributing_Guide": "ZecHubへの貢献",
  "site/contribute/Help_build_ZecHub": "ZecHubの構築にご協力ください",
  "site/contribute/Style_Guide": "ZecHub スタイルガイド",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly ニュースレター",
  "site/guides/Akash_Network_Zcashd": "Akash経由でコンソールを使用してzcashdを展開する",
  "site/guides/Akash_Network_Zebra": "Akashネットワーク上でZebraを実行する方法",
  "site/guides/Avalanche_RedBridge": "Zcash アバランチ RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "Zcash 対応の BTCPay Server: 完全インストールと統合ガイド",
  "site/guides/Blockchain_Explorers": "ブロックチェーンエクスプローラー",
  "site/guides/Brave_Wallet_Guide": "Brave WalletでシールドされたZcash (ZEC) を送受信する方法：ステップごとのプライバシーガイド",
  "site/guides/Free2Z_Livestreaming": "Free2Zでのライブ配信",
  "site/guides/Free2z_Live": "Free2Z: アカウントの作成＋ライブ配信チュートリアル",
  "site/guides/Hardened_Zebrad": "ハードニングされたZebraフルノード",
  "site/guides/Keystone_Zashi": "ケーストーン Zashi ユーザー・ガイド",
  "site/guides/Maya_Protocol": "マヤ分散型取引所",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "マイグレーションガイド: zcashd から Zebrad/Zallet へ",
  "site/guides/My_First_Zcash_Workbook": "はじめてのZcashワークブック",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: zcashd フルノードガイド",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd with Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4 上での Zebra の実行ガイド",
  "site/guides/ShapeShift_Zcash": "ShapeShiftとZcash: プライバシーを重視した分散型取引",
  "site/guides/Using_ZEC_Privately": "ZECをプライバシー保護して使用する",
  "site/guides/Using_ZEC_in_DeFi": "Zcash を DeFi で使用する",
  "site/guides/Visualizing_Zcash_Addresses": "Zcash アドレスの視覚化",
  "site/guides/Visualizing_the_Zcash_Network": "Zcashネットワークの可視化",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST デモ",
  "site/guides/Zcash_Devtool": "Zcash Devtool とは",
  "site/guides/Zcash_Improvement_Proposals": "Zcash Improvement Proposals",
  "site/guides/Zenith_Installation": "Zenith GUI フルノードウォレットのインストール",
  "site/guides/Zero-Knowledge_vs_Decoys": "零知識証明とダミーに基づくシステムの比較",
  "site/guides/Zgo_Payment_Processor": "ZGo決済処理：Zcashを預金なしで受け取る",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig ガイド",
  "site/guides/coinholder_log_parser/help": "選挙ログフィルタ",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST デモ",
  "site/guides/multisigdemo/MultiSigDemo": "マルチシグデモ",
  "site/guides/workshops/zcashContributorWorkshopDay3": "ワークショップ Day 3",
  "site/tutorials/Exchanges": "Zcash取引所",
  "site/tutorials/Full_Node_Tutorials": "フルノードチュートリアル",
  "site/tutorials/Using_Zcash": "Zcashの使用に関するチュートリアル",
  "site/tutorials/Wallet_Tutorials": "Zcashウォレットチュートリアル",
  "site/tutorials/shieldedNewsletter/readme": "シールドされたニュースレター",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 ベータ版",
};
