// AUTO-GENERATED — pt page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `pt` locale. Regenerate with
// scratchpad/gen_page_titles_loc.py after adding/retitling translated pages.
export const pageTitlesPt: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Perguntas Frequentes",
  "site/Glossary_and_FAQs/Gallery": "Galeria de Papéis de Parede do Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Biblioteca Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Dispositivos de hardware 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti: O Cliente Tor de Próxima Geração em Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Protocolo Namada",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Mensageiros Seguros",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Por que a Privacidade Importa",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Navegadores Web",
  "site/Research/Dash_Zcash_Orchard_Integration": "Integração do Dash com Orchard da Zcash",
  "site/Research/Namada_Privacy_and_Best_Practices": "Melhores Práticas de Privacidade da Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Revelando o Lado Sombrio: Navegando pela Odisseia das Moedas Digitais de Banco Central (CBDCs) em Meio às Sombras Financeiras",
  "site/Research/Social_Media_Data_Collection": "Coleta de Dados nas Redes Sociais",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Rastreando Sinais Iniciais On-chain e Sociais para Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Plataformas de Ativos com Conhecimento Zero",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Como uma Transação Shielded de Zcash Realmente Funciona",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Corpos Finitos: O Sistema Numérico em que a Criptografia Vive",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Curvas Elípticas: Onde Nascem as Chaves e os Compromissos da Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing e Commitments: O Envelope Selado Mágico",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Árvores de Merkle: Como o Blockchain Se Lembra de Cada Nota",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Provas de Conhecimento Zero: Provando que Você Está Certo Sem Dizer Por Quê",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "O Protocolo Shielded, de Ponta a Ponta",
  "site/Start_Here/Developer_Resources": "Recursos para Desenvolvedores",
  "site/Start_Here/Development_Fund": "Fundo de Desenvolvimento Zcash",
  "site/Start_Here/Network_Upgrades": "Atualizações de Rede do Zcash",
  "site/Start_Here/New_User_Guide": "Guia para Novos Usuários de Zcash",
  "site/Start_Here/Using_This_Wiki": "Usando esta Wiki",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Fundamentos da Zcash",
  "site/Start_Here/What_is_ZecHub": "O que é o ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Noções Básicas de Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Noções básicas de Zcash",
  "site/Start_Here/Zcash_Resources": "Recursos de Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Exploradores de Blockchain",
  "site/Using_Zcash/Buying_ZEC": "Obtendo Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Ferramentas Zcash para Criadores: Plataformas de Gorjetas e Perfis",
  "site/Using_Zcash/Custodial_Exchanges": "Exchanges com Custódia",
  "site/Using_Zcash/Encifher_Swaps": "Troca privada de SOL/USDC -> ZEC usando Encrypt.trade",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "Memorandos",
  "site/Using_Zcash/Metamask_Snap": "Guia de Integração do MetaMask Zcash Snap",
  "site/Using_Zcash/Mobile_Top_Ups": "Recarga de celular usando Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Exchanges Non-Custodial",
  "site/Using_Zcash/Payment_Processors": "Processadores de Pagamento Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "URIs de Solicitação de Pagamento Zcash",
  "site/Using_Zcash/Recovering_Funds": "Recuperação de Fundos de Carteiras Zcash",
  "site/Using_Zcash/Shielded_Pools": "Pools de Valor do Zcash",
  "site/Using_Zcash/Solswap": "Como trocar por ZEC na Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Lugares para Gastar ZEC",
  "site/Using_Zcash/Testnet": "Testnet da Zcash",
  "site/Using_Zcash/Transactions": "Transações",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "O que são endereços TEX do Zcash?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Guia de Mineração de Zcash: Entrando em um Pool de Mineração com Hardware Pessoal",
  "site/Using_Zcash/Zcash_Mining_Pools": "Pools de Mineração de Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Guias para Criadores",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Ferramentas de IA: geração de texto, imagem, vídeo e áudio (online)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Ferramentas de IA (locais, offline)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Transmissão Comunitária usando VDO.Ninja e OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Início Rápido: Criando Destaques do Zcon",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "Compartilhamento de arquivos P2P com IPFS e Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Configuração de transmissão ao vivo",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Publicar um Site no IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Servir Repositório GitHub com IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Geração e tradução de legendas de vídeo",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Blogs da Comunidade",
  "site/Zcash_Community/Community_Links": "Links da Comunidade Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Painel Consultivo da Comunidade Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Servir repositório Github com IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Publicar um Site no IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Segurança do Ecossistema Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Embaixadores Globais do Zcash",
  "site/Zcash_Community/Zcash_Governance": "Visão Geral do Financiamento e da Governança do Zcash",
  "site/Zcash_Community/Zcash_Media": "Zcash Media",
  "site/Zcash_Community/Zcash_Podcasts": "Podcasts",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Subsídios Retroativos Direcionados por Coinholders",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Do Zero ao Conhecimento Zero: Protocolo CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "Do Zero ao Conhecimento Zero: Funções Hash",
  "site/Zcash_Social_Media/Lelantus": "Do Zero ao Conhecimento Zero: Protocolo Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Do Zero ao Conhecimento Zero: Frases-semente Mnemônicas",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Resumos de Episódios do ZK Podcast",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Podcast Shielded Transactions do Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Podcast Zero Knowledge",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "O Podcast Zcash na Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "O Podcast Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Podcast Zcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "Podcast PGP para Cripto",
  "site/Zcash_Social_Media/TEEs": "Do Zero ao Conhecimento Zero: Trusted Execution Environments (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Do Zero ao Conhecimento Zero: Transações Transparentes vs Blindadas e Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero a Conhecimento Zero | Série Educacional",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nós Completos",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Lightwallet Nodes",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Segurança Pós-Quântica no Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Protocolo de Atestação ZAP1",
  "site/Zcash_Tech/Zaino": "Indexador Zaino",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Ativos Blindados da Zcash",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Sincronização de Carteiras Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Requisitos do sistema e configuração de rede para o Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Use Zcash no Mundo Real",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Aceite Pagamentos como Comerciante com Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Configuração de Privacidade para Freelancers com Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Configuração de Privacidade para Jornalistas com Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Mantendo registros com ZEC blindado",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Gerencie um Tesouro Comunitário Privado com Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Receba doações de forma privada com Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Envie Dinheiro Sem Vincular Sua Identidade",
  "site/contribute/Community_Infrastructure": "Estrutura de Infraestrutura Comunitária do ZecHub",
  "site/contribute/Contributing_Guide": "Contribuindo para o ZecHub",
  "site/contribute/Help_build_ZecHub": "Ajude a construir o ZecHub",
  "site/contribute/Style_Guide": "Guia de Estilo do ZecHub",
  "site/contribute/ZecHub_DAO": "DAO do ZecHub",
  "site/contribute/ZecWeekly_Newsletter": "Newsletter ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Implantando zcashd no Akash via Console",
  "site/guides/Akash_Network_Zebra": "Como executar o Zebra na Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server com Suporte a Zcash: Guia Completo de Instalação e Integração",
  "site/guides/Blockchain_Explorers": "Exploradores de Blockchain",
  "site/guides/Brave_Wallet_Guide": "Como Enviar e Receber Zcash (ZEC) Blindado com a Brave Wallet: Um Guia de Privacidade Passo a Passo",
  "site/guides/Free2Z_Livestreaming": "Transmissão ao vivo no Free2Z",
  "site/guides/Free2z_Live": "Free2z: Configuração de conta + tutorial de transmissão ao vivo",
  "site/guides/Hardened_Zebrad": "Nó Completo Zebra Endurecido",
  "site/guides/Keystone_Zashi": "Guia do Usuário do Keystone Zashi",
  "site/guides/Maya_Protocol": "Exchange Descentralizada Maya",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Guia de Migração: De zcashd para Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Meu Primeiro Caderno de Exercícios do Zcash",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: um guia de nó completo zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd com Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Guia do Raspberry Pi 4 para Executar Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift e Zcash: Negociação Descentralizada com Privacidade em Primeiro Lugar",
  "site/guides/Using_ZEC_Privately": "Usando ZEC, de forma privada",
  "site/guides/Using_ZEC_in_DeFi": "Usando Zcash em DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Visualizando Endereços Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Visualizando a Rede Zcash",
  "site/guides/Ywallet_FROST_Demo": "Demonstração de FROST no Ywallet",
  "site/guides/Zcash_Devtool": "A Devtool do Zcash",
  "site/guides/Zcash_Improvement_Proposals": "Propostas de Melhoria do Zcash",
  "site/guides/Zenith_Installation": "Instalação da Carteira de Nó Completo Zenith GUI",
  "site/guides/Zero-Knowledge_vs_Decoys": "Conhecimento Zero vs Sistemas baseados em Iscas",
  "site/guides/Zgo_Payment_Processor": "Processador de Pagamentos ZGo: Aceitando Zcash Sem Custódia",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Guia de Multisig do Zkool",
  "site/guides/coinholder_log_parser/help": "Filtro de Log de Eleição",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Demonstração do FROST no Ywallet",
  "site/guides/multisigdemo/MultiSigDemo": "Demonstração de MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Dia 3 do Workshop",
  "site/tutorials/Exchanges": "Corretoras de Zcash",
  "site/tutorials/Full_Node_Tutorials": "Tutoriais de Full Node",
  "site/tutorials/Using_Zcash": "Tutoriais para Usar Zcash",
  "site/tutorials/Wallet_Tutorials": "Tutoriais de Carteiras Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Newsletters Blindadas",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
