// AUTO-GENERATED — ig page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesIg: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Ajụjụ Ndị A Na-ajụkarị",
  "site/Glossary_and_FAQs/Gallery": "Zcash Wallpaper Gallery",
  "site/Glossary_and_FAQs/Zcash_Library": "Ọbá akwụkwọ Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA Ngwaọrụ Ngwaọrụ",
  "site/Privacy_Tools/Arti_Tor": "Arti: Onye ahịa Tor na-esote ọgbọ na Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Nkwekọrịta Namada",
  "site/Privacy_Tools/PGP_Encryption": "Ezigbo Nzuzo (PGP)",
  "site/Privacy_Tools/Penumbra": "Ọchịchịrị",
  "site/Privacy_Tools/Secure_Messengers": "Ndị Ozi A Tụkwasịrị Obi",
  "site/Privacy_Tools/Shade_Protocol": "Ụkpụrụ Shade",
  "site/Privacy_Tools/Tor_and_I2P": "Ihe Mere Nzuzo Ji Dị Mkpa",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Ihe nchọgharị weebụ",
  "site/Research/Dash_Zcash_Orchard_Integration": "Ntinye Dash nke Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada Nzuzo Omume Kasị Mma",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Igosipụta akụkụ gbara ọchịchịrị: Ịgagharị na Central Bank Digital Currency (CBDC) Odyssey n'etiti Onyunyo Ego",
  "site/Research/Social_Media_Data_Collection": "Nchịkọta Data Mgbasa Ozi",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Ịchọpụta Early On-chain & Social Signals maka Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Zero Ihe Ọmụma Asset Platforms",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Otu Azụmaahịa Zcash E Chebere na-arụ ọrụ n'ezie",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Ogige ndị nwere njedebe: Usoro ọnụọgụgụ nke Cryptography bi na ya",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Elliptic Curves: Ebe a mụrụ igodo na nkwa nke Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Nkọwapụta na Nkwekọrịta: Envelopu E Ji Ime Anwansi Mechie",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Osisi Merkle: Otu Blockchain si echeta Nkọwa Ọ bụla",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Ihe Akaebe Na-enweghị Ihe Ọmụma: Igosi na I Kwere Eziokwu n'Ekwughị Ihe Mere I Ji Kwere",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Usoro Nkwekọrịta E Chebere, Site ná Mmalite Ruo ná Ngwụsị",
  "site/Start_Here/Developer_Resources": "Akụrụngwa Onye Mmepụta",
  "site/Start_Here/Development_Fund": "Ego mmepe Zcash",
  "site/Start_Here/Network_Upgrades": "Nwelite netwọk Zcash",
  "site/Start_Here/New_User_Guide": "Ntuziaka Onye Ọrụ Ọhụrụ Zcash",
  "site/Start_Here/Using_This_Wiki": "Iji Wiki a",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Ihe ndị bụ isi nke Zcash",
  "site/Start_Here/What_is_ZecHub": "Gịnị bụ ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Ihe ndị bụ isi nke Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Ihe ndị bụ isi nke Zcash",
  "site/Start_Here/Zcash_Resources": "Akụrụngwa Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Ndị na-enyocha Blockchain",
  "site/Using_Zcash/Buying_ZEC": "Inweta Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Ngwaọrụ Zcash maka ndị okike: Tipping & Profile Platforms",
  "site/Using_Zcash/Custodial_Exchanges": "Custodial Exchanges",
  "site/Using_Zcash/Encifher_Swaps": "Private SOL/USDC -> ZEC Swap Iji Encrypt.trade",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "Ihe ncheta",
  "site/Using_Zcash/Metamask_Snap": "Ntuziaka MetaMask Zcash Snap Integration",
  "site/Using_Zcash/Mobile_Top_Ups": "Ntinye ekwentị site na iji Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial Exchanges",
  "site/Using_Zcash/Payment_Processors": "Ndị na-arụ ọrụ ịkwụ ụgwọ Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash Ịkwụ Ụgwọ Arịrịọ URI",
  "site/Using_Zcash/Recovering_Funds": "Iweghachite ego Zcash Wallet",
  "site/Using_Zcash/Shielded_Pools": "Zcash Value Pools",
  "site/Using_Zcash/Solswap": "Otu esi agbanwe maka ZEC na Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Ebe Ị Ga-eji ZEC Mee Ihe",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Mmekọrịta",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Gịnị Bụ Adreesị Zcash TEX?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash Mining Guide: Isonyere na Ngwuputa Ngwá Ọrụ na Personal Hardware",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash Mining Pools",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Akwụkwọ Nduzi Maka Ndị Na-emepụta Ihe",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Ngwaọrụ AI: Ederede, Ihe oyiyi, Video, Audio na-emepụta (online)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Ngwá ọrụ AI (mpaghara, offline)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Mgbasa ozi obodo na-eji VDO.Ninja na OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Mmalite ngwa ngwa: Ịmepụta Zcon Highlights",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "Ịkekọrịta faịlụ P2P na IPFS na Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Ntọala nke Live Stream",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Bipute saịtị na IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Na-eje ozi GitHub Repo na IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Ntughari na ntụgharị vidiyo",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Blọọgụ Obodo",
  "site/Zcash_Community/Community_Links": "Zcash Community Links",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash Community Advisory Panel",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Na-eje ozi Github Repo na IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Bipute Weebụsaịtị na IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Nchebe nke Zcash Ecosystem",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Ndị nnọchi anya Zcash Global",
  "site/Zcash_Community/Zcash_Governance": "Zcash Funding & Governance Nchịkọta",
  "site/Zcash_Community/Zcash_Media": "Zcash Mgbasa Ozi",
  "site/Zcash_Community/Zcash_Podcasts": "Podcasts",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Ụda olu",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Onyinye Ego Na-eduzi Ndị Na-ahụ Maka Mkpụrụ ego",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Ụlọ Ọrụ Nzuzo Ego (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Ihe Ọmụma Na-aga n'Ihu: Usoro CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "Ihe Ọmụma Na-aga n'Ihu: Ọrụ Hash",
  "site/Zcash_Social_Media/Lelantus": "Ihe Ọmụma Na-aga n'Ihu: Usoro Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Ihe Ọmụma Na-aga n'Ihu: Mnemonic Seed Phrases",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast Nchịkọta Ihe Omume",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Mgbasa Ozi Azụmaahịa E Chebere site na Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Podcast Ọmụma efu",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Zcash Podcast na Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Podcast nke Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP maka Crypto Podcast",
  "site/Zcash_Social_Media/TEEs": "Ihe Ọmụma Na-enweghị Ihe Ọ Bụla: Ebe A Tụkwasịrị Obi (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Ihe Ọmụma Na-enweghị Ihe Ọ Bụla: Mmekọrịta Transparent vs Shielded & Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero to Zero Knowledge. Usoro Nkuzi",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nọmba zuru ezu",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Lightwallet Nodes",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Nchekwa Post-Quantum na Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Igodo Nlele",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 Nkwekọrịta Asambodo",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Akụrụngwa Echebe",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Mmekọrịta obere akpa Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Ihe ndị a chọrọ n'aka usoro na nhazi netwọk maka Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Jiri Zcash na Real World",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accept Payments as a Merchant with Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Freelancer Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Journalist Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Idebe ndekọ na ZEC echekwara",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Run a Private Community Treasury with Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Receive Donations Privately with Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Send Money Without Linking Your Identity",
  "site/contribute/Community_Infrastructure": "ZecHub Community Infrastructure Framework (Njikọ Nrụpụta Ihe nke Obodo)",
  "site/contribute/Contributing_Guide": "Inye aka na ZecHub",
  "site/contribute/Help_build_ZecHub": "Nyere Aka Wulite ZecHub",
  "site/contribute/Style_Guide": "Ntuziaka Ụdị ZecHub",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "Akwụkwọ akụkọ ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Ntinye nke zcashd na Akash site na Console",
  "site/guides/Akash_Network_Zebra": "Otu esi agba ọsọ Zebra na Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server na Nkwado Zcash: Ntuziaka Ntinye na Njikọ zuru ezu",
  "site/guides/Blockchain_Explorers": "Ndị na-enyocha Blockchain",
  "site/guides/Brave_Wallet_Guide": "Otu esi eziga ma nata Zcash echedoro (ZEC) na Brave Wallet: Ntuziaka Nzuzo Nzọụkwụ Nzọ ụkwụ",
  "site/guides/Free2Z_Livestreaming": "Na-ebi ndụ na Free2Z",
  "site/guides/Free2z_Live": "Free2z: Ntọala Akaụntụ + LiveStream nkuzi",
  "site/guides/Hardened_Zebrad": "Zebra siri ike Full Node",
  "site/guides/Keystone_Zashi": "Keystone Zashi Ntuziaka Onye Ọrụ",
  "site/guides/Maya_Protocol": "Maya Decentralized Exchange",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Ntuziaka Mbugharị: Site na zcashd ruo Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Akwụkwọ Ọrụ Zcash Mbụ M",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: a zcashd Ntuziaka zuru oke",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd na Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Ntuziaka Raspberry Pi 4 maka ịgba ọsọ Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift na Zcash: Nzuzo-Nke Mbụ Decentralized Trading",
  "site/guides/Using_ZEC_Privately": "Iji ZEC, na nzuzo",
  "site/guides/Using_ZEC_in_DeFi": "Iji Zcash na DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Ịhụ Adreesị Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Ichepụta Netwọk Zcash",
  "site/guides/Ywallet_FROST_Demo": "Ihe ngosi Ywallet FROST",
  "site/guides/Zcash_Devtool": "Ngwaọrụ Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Nkwupụta Mmezi Zcash",
  "site/guides/Zenith_Installation": "Zenith GUI Full Node Wallet Ntinye",
  "site/guides/Zero-Knowledge_vs_Decoys": "Ihe Ọmụma efu vs Decoy based Systems",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: Ịnabata Zcash na-enweghị Nchebe",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad) ((zaino) ((zingo-cli)",
  "site/guides/Zkool_Multisig": "Ntuziaka Zkool Multisig",
  "site/guides/coinholder_log_parser/help": "Nchịkọta Ntuli Aka",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ihe ngosi Ywallet FROST",
  "site/guides/multisigdemo/MultiSigDemo": "Ihe ngosi MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Ụbọchị nke 3 nke Nzukọ Ọmụmụ Ihe",
  "site/tutorials/Exchanges": "Mgbanwe Zcash",
  "site/tutorials/Full_Node_Tutorials": "Ntuziaka Nhazi zuru ezu",
  "site/tutorials/Using_Zcash": "Nkuzi maka iji Zcash",
  "site/tutorials/Wallet_Tutorials": "Nkuzi obere akpa Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Akwụkwọ Akụkọ Ndị E Chebere",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
