// AUTO-GENERATED — de page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `de` locale. Regenerate with
// scratchpad/gen_page_titles_loc.py after adding/retitling translated pages.
export const pageTitlesDe: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Häufig gestellte Fragen",
  "site/Glossary_and_FAQs/Gallery": "Zcash Hintergrundbilder-Galerie",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash-Bibliothek",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA-Hardwaregeräte",
  "site/Privacy_Tools/Arti_Tor": "Arti: Der Tor-Client der nächsten Generation in Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada Protocol",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Sichere Messenger",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Warum Privatsphäre wichtig ist",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Webbrowser",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash-Integration von Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Bewährte Datenschutzpraktiken für Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Die dunkle Seite enthüllen: Die Odyssee der digitalen Zentralbankwährung (CBDC) inmitten finanzieller Schatten navigieren",
  "site/Research/Social_Media_Data_Collection": "Sammlung von Social-Media-Daten",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Verfolgung früher On-Chain- und sozialer Signale für Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Zero-Knowledge-Asset-Plattformen",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Wie eine abgeschirmte Zcash-Transaktion tatsächlich funktioniert",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Endliche Körper: Das Zahlensystem, in dem Kryptographie lebt",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Elliptische Kurven: Wo Zcashs Schlüssel und Commitments entstehen",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing und Commitments: Der magisch versiegelte Umschlag",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Merkle-Bäume: Wie die Blockchain sich jede Note merkt",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Zero-Knowledge-Proofs: Beweisen, dass du recht hast, ohne zu sagen, warum",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Das Shielded Protocol, von Anfang bis Ende",
  "site/Start_Here/Developer_Resources": "Ressourcen für Entwickler",
  "site/Start_Here/Development_Fund": "Zcash Development Fund",
  "site/Start_Here/Network_Upgrades": "Zcash Netzwerk-Upgrades",
  "site/Start_Here/New_User_Guide": "Zcash Leitfaden für neue Nutzer",
  "site/Start_Here/Using_This_Wiki": "Verwendung dieses Wikis",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash-Grundlagen",
  "site/Start_Here/What_is_ZecHub": "Was ist ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash-Grundlagen",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash-Grundlagen",
  "site/Start_Here/Zcash_Resources": "Zcash-Ressourcen",
  "site/Using_Zcash/Blockchain_Explorers": "Blockchain-Explorer",
  "site/Using_Zcash/Buying_ZEC": "Zcash erwerben",
  "site/Using_Zcash/Creators_and_Tips": "Zcash-Tools für Creator: Trinkgeld- und Profilplattformen",
  "site/Using_Zcash/Custodial_Exchanges": "Verwahrende Börsen",
  "site/Using_Zcash/Encifher_Swaps": "Privater SOL/USDC -> ZEC-Swap mit Encrypt.trade",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "Memos",
  "site/Using_Zcash/Metamask_Snap": "Anleitung zur Integration von MetaMask Zcash Snap",
  "site/Using_Zcash/Mobile_Top_Ups": "Handy-Guthaben mit Zcash aufladen",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial Börsen",
  "site/Using_Zcash/Payment_Processors": "Zcash-Zahlungsabwickler",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash-Zahlungsanforderungs-URIs",
  "site/Using_Zcash/Recovering_Funds": "Wiederherstellung von Geldern in Zcash Wallets",
  "site/Using_Zcash/Shielded_Pools": "Zcash Wertpools",
  "site/Using_Zcash/Solswap": "Wie man in der Phantom Wallet gegen ZEC tauscht",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Orte, an denen man ZEC ausgeben kann",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Transaktionen",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Was sind Zcash TEX-Adressen?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash Mining-Leitfaden: Beitritt zu einem Mining-Pool mit eigener Hardware",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash Mining Pools",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Leitfäden für Kreative",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "KI-Tools: Text-, Bild-, Video- und Audio-Generierung (online)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI-Tools (lokal, offline)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Community-Broadcasting mit VDO.Ninja und OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Schnellstart: Zcon Highlights erstellen",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "P2P-Dateifreigabe mit IPFS und dem Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Livestream-Einrichtung",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Eine Website auf IPFS veröffentlichen",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "GitHub-Repo mit IPFS bereitstellen",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Erstellung und Übersetzung von Video-Untertiteln",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Community-Blogs",
  "site/Zcash_Community/Community_Links": "Zcash Community-Links",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash Community Advisory Panel",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "GitHub-Repository mit IPFS bereitstellen",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Eine Website auf IPFS veröffentlichen",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Sicherheit des Zcash-Ökosystems",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash Global Ambassadors",
  "site/Zcash_Community/Zcash_Governance": "Überblick über Finanzierung und Governance von Zcash",
  "site/Zcash_Community/Zcash_Media": "Zcash-Medien",
  "site/Zcash_Community/Zcash_Podcasts": "Podcasts",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Coinholder-Directed Retroactive Grants",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Von Null zu Zero Knowledge: CryptoNote-Protokoll",
  "site/Zcash_Social_Media/Hash_Functions": "Zero to Zero Knowledge: Hashfunktionen",
  "site/Zcash_Social_Media/Lelantus": "Von Null zu Zero Knowledge: Lelantus-Protokoll",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Von Null zu Zero Knowledge: Mnemonische Seed-Phrasen",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Zusammenfassungen der ZK Podcast-Episoden",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Shielded Transactions Podcast von Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Zero Knowledge Podcast",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Der Zcash Podcast im Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Der Z2Z Podcast",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP für den Krypto-Podcast",
  "site/Zcash_Social_Media/TEEs": "Von Null zu Zero Knowledge: Vertrauenswürdige Ausführungsumgebungen (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Von Null zu Zero Knowledge: Transparente vs. Shielded-Transaktionen & Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero bis Zero Knowledge | Bildungsreihe",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Full Nodes",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Lightwallet-Knoten",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Post-Quantum-Sicherheit in Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 Attestierungsprotokoll",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash Wallet-Synchronisierung",
  "site/Zcash_Tech/Zebra_Full_Node": "Systemanforderungen und Netzwerkkonfiguration für Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Zcash in der realen Welt nutzen",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Zahlungen als Händler mit Zcash akzeptieren",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Datenschutz-Setup für Freelancer mit Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Datenschutz-Setup für Journalisten mit Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Aufzeichnungen mit shielded ZEC führen",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Eine private Community-Treasury mit Zcash betreiben",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Spenden privat mit Zcash empfangen",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Geld senden, ohne deine Identität zu verknüpfen",
  "site/contribute/Community_Infrastructure": "ZecHub Community Infrastructure Framework",
  "site/contribute/Contributing_Guide": "Zu ZecHub beitragen",
  "site/contribute/Help_build_ZecHub": "Hilf mit, ZecHub aufzubauen",
  "site/contribute/Style_Guide": "ZecHub-Stilrichtlinie",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly-Newsletter",
  "site/guides/Akash_Network_Zcashd": "Bereitstellung von zcashd auf Akash über die Console",
  "site/guides/Akash_Network_Zebra": "So führst du Zebra im Akash Network aus",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server mit Zcash-Unterstützung: Vollständige Installations- und Integrationsanleitung",
  "site/guides/Blockchain_Explorers": "Blockchain-Explorer",
  "site/guides/Brave_Wallet_Guide": "So sendest und empfängst du abgeschirmtes Zcash (ZEC) mit Brave Wallet: Eine Schritt-für-Schritt-Anleitung für Privatsphäre",
  "site/guides/Free2Z_Livestreaming": "Livestreaming auf Free2Z",
  "site/guides/Free2z_Live": "Free2z: Kontoeinrichtung + Livestream-Tutorial",
  "site/guides/Hardened_Zebrad": "Gehärteter Zebra Full Node",
  "site/guides/Keystone_Zashi": "Keystone Zashi Benutzerhandbuch",
  "site/guides/Maya_Protocol": "Maya Dezentrale Börse",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Migrationsleitfaden: Von zcashd zu Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Mein erstes Zcash-Arbeitsbuch",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: ein zcashd-Full-Node-Leitfaden",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd mit Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4 Leitfaden zum Ausführen von Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift und Zcash: Datenschutzorientierter dezentraler Handel",
  "site/guides/Using_ZEC_Privately": "ZEC privat verwenden",
  "site/guides/Using_ZEC_in_DeFi": "Zcash in DeFi verwenden",
  "site/guides/Visualizing_Zcash_Addresses": "Visualisierung von Zcash-Adressen",
  "site/guides/Visualizing_the_Zcash_Network": "Visualisierung des Zcash-Netzwerks",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST-Demo",
  "site/guides/Zcash_Devtool": "Das Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Zcash Improvement Proposals",
  "site/guides/Zenith_Installation": "Installation der Zenith GUI Full Node Wallet",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Knowledge vs. Decoy-basierte Systeme",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: Zcash ohne Verwahrung akzeptieren",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig-Anleitung",
  "site/guides/coinholder_log_parser/help": "Wahlprotokoll-Filter",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST-Demo",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig-Demo",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Workshop-Tag 3",
  "site/tutorials/Exchanges": "Zcash-Börsen",
  "site/tutorials/Full_Node_Tutorials": "Full Node-Tutorials",
  "site/tutorials/Using_Zcash": "Tutorials zur Verwendung von Zcash",
  "site/tutorials/Wallet_Tutorials": "Zcash Wallet-Tutorials",
  "site/tutorials/shieldedNewsletter/readme": "Geschützte Newsletter",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
