// AUTO-GENERATED — ak page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesAk: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Nsɛm a Wɔtaa Bisa",
  "site/Glossary_and_FAQs/Gallery": "Zcash Wallpaper Nneɛma a Wɔde Yɛ Nneɛma",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash Nhomakorabea",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA Hardware Mfiri a Wɔde Di Dwuma",
  "site/Privacy_Tools/Arti_Tor": "Arti: Awo Ntoatoaso a Edi Hɔ Tor Client wɔ Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS a wɔde yɛ adwuma",
  "site/Privacy_Tools/Namada_Protocol": "Namada Nsɛm a Wɔahyehyɛ",
  "site/Privacy_Tools/PGP_Encryption": "Nsɛm a Wɔde Sie (PGP) .",
  "site/Privacy_Tools/Penumbra": "Penumbra na ɔkyerɛwee",
  "site/Privacy_Tools/Secure_Messengers": "Abɔfoɔ a Wɔwɔ Ahobammɔ",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol no ho nhyehyɛe",
  "site/Privacy_Tools/Tor_and_I2P": "Nea Enti a Kokoam Nsɛm Ho Hia",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN na ɛyɛ adwuma",
  "site/Privacy_Tools/Web_Browsers": "Wɛbsaet Browser ahorow",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash Integration of Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada Kokoam Nsɛm Nneyɛe Pa",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Esum Afã a Wɔda no Adi: Central Bank Digital Currency (CBDC) Odyssey no a Wɔbɛfa Sikasɛm Sunsuma Mu",
  "site/Research/Social_Media_Data_Collection": "Social Media Data a Wɔaboaboa Ano",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Tracking Mfiase On-nkɔnsɔnkɔnsɔn & Social Nsɛnkyerɛnne ma Zcash (ZEC) .",
  "site/Research/ZK_Shielded_Asset_Platforms": "Zero Nimdeɛ Agyapadeɛ Nhyiamu",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Sɛnea Shielded Zcash Transaction Yɛ Adwuma Ankasa",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Finite Fields: Nnɔmba Nhyehyɛe a Cryptography Te Ase Wɔ Mu",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Elliptic Curves: Baabi a Wɔwo Zcash Safoa ne Bɔhyɛ ahorow",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing ne Bɔhyɛ ahorow: The Magic Sealed Envelope",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Merkle Nnua: Sɛnea Blockchain Kae Biribiara a Wɔahyɛ no nsow",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Adanse a Nimdeɛ Nni Mu: Sɛ Wobɛkyerɛ sɛ Wo Teɛ a Worenka Nea Enti a Enti",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "The Shielded Protocol, Awiei kosi Awiei",
  "site/Start_Here/Developer_Resources": "Nneɛma a Wɔde Yɛ Nneɛma",
  "site/Start_Here/Development_Fund": "Zcash Nkɔsoɔ Fotoɔ",
  "site/Start_Here/Network_Upgrades": "Zcash Network Nkɔsoɔ a Wɔayɛ",
  "site/Start_Here/New_User_Guide": "Zcash Foforo a Wɔde Di Dwuma Nkyerɛkyerɛmu",
  "site/Start_Here/Using_This_Wiki": "Wiki yi a wode redi dwuma",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash Mfitiaseɛ",
  "site/Start_Here/What_is_ZecHub": "Dɛn ne ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash Mfitiaseɛ",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash Mfitiaseɛ",
  "site/Start_Here/Zcash_Resources": "Zcash Nneɛma a Wɔde Yɛ Adwuma",
  "site/Using_Zcash/Blockchain_Explorers": "Blockchain Nhwehwɛmufo",
  "site/Using_Zcash/Buying_ZEC": "Zcash a wobenya",
  "site/Using_Zcash/Creators_and_Tips": "Zcash Nnwinnade ma Adebɔfo: Tipping & Profile Platforms",
  "site/Using_Zcash/Custodial_Exchanges": "Custodial Exchanges",
  "site/Using_Zcash/Encifher_Swaps": "SOL/USDC a ɛyɛ kokoam -> ZEC Swap a wode Encrypt.trade Di Dwuma",
  "site/Using_Zcash/Faucets": "Faucets a wɔde yɛ adwuma",
  "site/Using_Zcash/Memos": "Memos a wɔde kyerɛw nsɛm",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap Nkabom Akwankyerɛ",
  "site/Using_Zcash/Mobile_Top_Ups": "Mobile Top-up a Wɔde Zcash Di Dwuma",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial Exchanges",
  "site/Using_Zcash/Payment_Processors": "Zcash Nneɛma a Wɔde Tua Ka",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash Katua Abisade URI ahorow",
  "site/Using_Zcash/Recovering_Funds": "Zcash Wallet Sikakorabea a Wɔsan Yɛ",
  "site/Using_Zcash/Shielded_Pools": "Zcash Botae a Wɔde Yɛ Adwuma",
  "site/Using_Zcash/Solswap": "Sɛnea wobɛsesa ZEC wɔ Phantom Wallet mu",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Mmeae a Wɔde Di Dwuma ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet a Wɔde Yɛ Adwuma",
  "site/Using_Zcash/Transactions": "Nkitahodi ahorow",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Dɛn Ne Zcash TEX Address ahorow?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash Mining Guide: Sɛ wode Ankorankoro Hardware bɛka Mining Pool ho",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash Mining Atare a Wɔde Tu Fam",
  "site/Using_Zcash/zimppy": "Zimppy.xyz na ɔkyerɛwee",
  "site/ZFAV_Club/Guides_for_Creators": "Akwankyerɛ a Wɔde Ma Adebɔfo",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI nnwinnade: Nsɛm, Mfonini, Video, Ɔdio a wɔyɛ (intanɛt so) .",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI nnwinnade (ɛhɔnom, offline) .",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Mpɔtam Hɔ Broadcasting a wɔde VDO.Ninja ne OBS Studio di dwuma",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Mfiase Ntɛm: Yɛrebɔ Zcon Nsɛntitiriw",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "P2P Fael Kyɛfa ne IPFS ne Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Livestream Nhyehyɛe",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Twerɛ Wɛbsaet bi wɔ IPFS so",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Som GitHub Repo ne IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Video subtitle awo ntoatoaso ne nkyerɛase",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Mpɔtam hɔ Blogs",
  "site/Zcash_Community/Community_Links": "Zcash Community Links",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk a ɛyɛ Zero a ɛyɛ Zero",
  "site/Zcash_Community/ZCAP": "Zcash Mpɔtam Hɔ Afotufoɔ Kuo",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Som Github Repo ne IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Twerɛ Wɛbsaet bi wɔ IPFS so",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash Abɔde a Nkwa Wom Ahobammɔ",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash Wiase Nyinaa Aban Nnanmusini",
  "site/Zcash_Community/Zcash_Governance": "Zcash Sikasɛm & Aban Ho Nsɛm a Wɔahyehyɛ",
  "site/Zcash_Community/Zcash_Media": "Zcash Nsɛm ho amanneɛbɔfo",
  "site/Zcash_Community/Zcash_Podcasts": "Podcast ahorow a wɔde di dwuma",
  "site/Zcash_Community/Zcon_Archive": "Zcon na ɔkyerɛwee",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes na ɔkyerɛwee",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Coinholder-Directed Retroactive Ntoboa a Wɔde Ma",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Sikasɛm mu Nsɛm a Wɔde Siesie Nsɛm Ho Fapem (FPF) .",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright na ɔkyerɛwee",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Nimdeɛ a ɛwɔ Zero kosi Zero: CryptoNote Protocol",
  "site/Zcash_Social_Media/Hash_Functions": "Zero to Zero Nimdeɛ: Hash Dwumadi ahorow",
  "site/Zcash_Social_Media/Lelantus": "Nimdeɛ a Ɛwɔ Zero kosi Zero: Lelantus Protocol",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Nimdeɛ Zero kosi Zero: Mnemonic Aba Nsɛmfua",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast Episode Nsɛm a Wɔaboaboa Ano",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Shielded Transactions Podcast a Forsight Asoɛe na ɛyɛe",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Zero Nimdeɛ Podcast",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Zcash Podcast a ɛwɔ Digital Cash Network so no",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z Podcast no na ɛyɛ adwuma",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast a Wɔde Di Dwuma",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP a wɔde yɛ Crypto Podcast",
  "site/Zcash_Social_Media/TEEs": "Nimdeɛ a Ɛwɔ Zero kosi Zero: Nneɛma a Wɔde Di Dwuma a Wogye Di (TEEs) .",
  "site/Zcash_Social_Media/Zcash_Addresses": "Zero to Zero Nimdeɛ: Transparent vs Shielded Transactions & Address a Wɔaka abom",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero to Zero Nimdeɛ | Nhomasua Ntoatoaso",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nodes a Ɛyɛ Pɛ",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Kanea a Wɔde Yɛ Adwuma",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Ɛmo a wɔde yɛ Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Akwantuo akyi Ahobanbɔ wɔ Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Nneɛma a Wɔde Hwɛ",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 Adansedi Nhyehyɛe",
  "site/Zcash_Tech/Zaino": "Zaino Indexer a ɔkyerɛwee",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Agyapadeɛ",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash Sikakorabea Syncing",
  "site/Zcash_Tech/Zebra_Full_Node": "System Ahwehwɛde ne Network Nsiesiei ma Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS NKYERƐKYERƐMU",
  "site/Zcash_Use_Cases/About": "Fa Zcash di dwuma wɔ Wiase Ankasa no mu",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accept Payments as a Merchant with Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Freelancer Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Journalist Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Kyerɛwtohɔ a wɔde ZEC a wɔabɔ ho ban no sie",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Run a Private Community Treasury with Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Receive Donations Privately with Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Send Money Without Linking Your Identity",
  "site/contribute/Community_Infrastructure": "ZecHub Mpɔtam Hɔ Nnwuma Nhyehyɛeɛ",
  "site/contribute/Contributing_Guide": "Ɔreboa ZecHub",
  "site/contribute/Help_build_ZecHub": "Boa ma Wɔkyekye ZecHub",
  "site/contribute/Style_Guide": "ZecHub Style Akwankyerɛ",
  "site/contribute/ZecHub_DAO": "ZecHub DAO na ɔkyerɛwee",
  "site/contribute/ZecWeekly_Newsletter": "ZecNnawɔtwe Nnawɔtwe Nsɛmma Nhoma",
  "site/guides/Akash_Network_Zcashd": "Wɔde zcashd rekɔ Akash denam Console so",
  "site/guides/Akash_Network_Zebra": "Sɛnea wɔyɛ Zebra wɔ Akash Network so",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge a ɛwɔ hɔ no",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server a Zcash Mmoa: Installation ne Integration Akwankyerɛ a Edi Mu",
  "site/guides/Blockchain_Explorers": "Blockchain Nhwehwɛmufo",
  "site/guides/Brave_Wallet_Guide": "Sɛnea Wɔde Brave Wallet Kɔma na Wogye Shielded Zcash (ZEC): Anamɔn biara a Wɔde Siesie Nsɛm Ho Akwankyerɛ",
  "site/guides/Free2Z_Livestreaming": "Livestreaming wɔ Free2Z so",
  "site/guides/Free2z_Live": "Free2z: Akontaabu nhyehyɛe + Livestream nkyerɛkyerɛ",
  "site/guides/Hardened_Zebrad": "Hardened Zebra Full Node",
  "site/guides/Keystone_Zashi": "Keystone Zashi Dwumadie Nkyerɛkyerɛmu",
  "site/guides/Maya_Protocol": "Mayafo Nsesaeɛ a Wɔde Di Dwuma",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Tukɔ Akwankyerɛ: Efi zcashd kɔ Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Me Zcash Adwuma Nhoma a Edi Kan",
  "site/guides/Nym_VPN": "Nym VPN na ɛwɔ hɔ",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: zcashd Node akwankyerɛ a edi mũ",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd a wɔde Zingo ahyɛ mu",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4 Guide for Running Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift ne Zcash: Kokoamsɛm-Aguadi a Edi Kan a Wɔde Di Dwuma wɔ Decentralized",
  "site/guides/Using_ZEC_Privately": "ZEC a wode bedi dwuma, wɔ kokoam",
  "site/guides/Using_ZEC_in_DeFi": "Zcash a wode bedi dwuma wɔ DeFi mu",
  "site/guides/Visualizing_Zcash_Addresses": "Zcash Address ahorow a wobɛyɛ wɔ w’adwenem",
  "site/guides/Visualizing_the_Zcash_Network": "Zcash Network no a wobɛhwɛ wɔ w’adwenem",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST ho ɔyɛkyerɛ",
  "site/guides/Zcash_Devtool": "Zcash Devtool no na ɛyɛ adwuma",
  "site/guides/Zcash_Improvement_Proposals": "Zcash Nkɔsoɔ Ho Nsusuiɛ",
  "site/guides/Zenith_Installation": "Zenith GUI Full Node Sikakorabea a Wɔde Siesie",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Nimdeɛ vs Decoy a egyina Systems so",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: Gye Zcash a Wonnye Nhwɛso",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig Akwankyerɛ",
  "site/guides/coinholder_log_parser/help": "Abatow ho Nsɛm a Wɔahyehyɛ",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST ho ɔyɛkyerɛ",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig Demo a Wɔde Kyerɛkyerɛ",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Adwumayɛbea Da a ɛto so 3",
  "site/tutorials/Exchanges": "Zcash Nneɛma a Wɔde Sesa Nneɛma",
  "site/tutorials/Full_Node_Tutorials": "Node Nkyerɛkyerɛ a Edi Mu",
  "site/tutorials/Using_Zcash": "Nkyerɛkyerɛ a ɛfa Zcash a Wɔde Di Dwuma Ho",
  "site/tutorials/Wallet_Tutorials": "Zcash Wallet Nkyerɛkyerɛmu",
  "site/tutorials/shieldedNewsletter/readme": "Nsɛm ho amanneɛbɔ nkrataa a wɔabɔ ho ban",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta na ɛwɔ hɔ",
};
