// AUTO-GENERATED — tr page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesTr: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Sıkça Sorulan Sorular",
  "site/Glossary_and_FAQs/Gallery": "Zcash Duvar Kağıdı Galerisi",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash Kütüphanesi",
  "site/Privacy_Tools/2FA_Hardware_Devices": "2FA Donanım Cihazları",
  "site/Privacy_Tools/Arti_Tor": "Arti: Rust ile Yeni Nesil Tor İstemcisi",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada Protocol",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Güvenli Mesajlaşma Uygulamaları",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Gizlilik Neden Önemlidir",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Web Tarayıcıları",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash'in Zcash Orchard Entegrasyonu",
  "site/Research/Namada_Privacy_and_Best_Practices": "Namada Gizlilik için En İyi Uygulamalar",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Karanlık Yüzü Ortaya Çıkarmak: Finansal Gölgeler Arasında Merkez Bankası Dijital Parası (CBDC) Yolculuğunda İlerlemek",
  "site/Research/Social_Media_Data_Collection": "Sosyal Medya Veri Toplama",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Zcash (ZEC) için Erken On-chain ve Sosyal Sinyallerin Takibi",
  "site/Research/ZK_Shielded_Asset_Platforms": "Sıfır Bilgi Varlık Platformları",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Korumalı Bir Zcash İşlemi Aslında Nasıl Çalışır?",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Sonlu Alanlar: Kriptografinin İçinde Yaşadığı Sayı Sistemi",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Eliptik Eğriler: Zcash'nin Anahtarlarının ve Taahhütlerinin Doğduğu Yer",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing ve Taahhütler: Sihirli Mühürlü Zarf",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Merkle Ağaçları: Blockchain Her Notu Nasıl Hatırlar?",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Sıfır Bilgi Kanıtları: Nedenini Söylemeden Haklı Olduğunu Kanıtlamak",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Korumalı Protokol, Uçtan Uca",
  "site/Start_Here/Developer_Resources": "Geliştirici Kaynakları",
  "site/Start_Here/Development_Fund": "Zcash Geliştirme Fonu",
  "site/Start_Here/Network_Upgrades": "Zcash Ağ Yükseltmeleri",
  "site/Start_Here/New_User_Guide": "Zcash Yeni Kullanıcı Rehberi",
  "site/Start_Here/Using_This_Wiki": "Bu Wiki Nasıl Kullanılır",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Zcash Temelleri",
  "site/Start_Here/What_is_ZecHub": "ZecHub nedir?",
  "site/Start_Here/ZEC_Use_Cases": "Zcash Temelleri",
  "site/Start_Here/Zcash_Monetary_Policy": "Zcash Temelleri",
  "site/Start_Here/Zcash_Resources": "Zcash Kaynakları",
  "site/Using_Zcash/Blockchain_Explorers": "Blockchain Gezgini",
  "site/Using_Zcash/Buying_ZEC": "Zcash Edinme",
  "site/Using_Zcash/Creators_and_Tips": "İçerik Üreticileri için Zcash Araçları: Bahşiş ve Profil Platformları",
  "site/Using_Zcash/Custodial_Exchanges": "Saklamalı Borsalar",
  "site/Using_Zcash/Encifher_Swaps": "Encrypt.trade Kullanarak Özel SOL/USDC -> ZEC Takası",
  "site/Using_Zcash/Faucets": "Faucet'ler",
  "site/Using_Zcash/Memos": "Notlar",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap Entegrasyon Rehberi",
  "site/Using_Zcash/Mobile_Top_Ups": "Zcash Kullanarak Mobil Kontör Yükleme",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Saklamasız Borsalar",
  "site/Using_Zcash/Payment_Processors": "Zcash Ödeme İşlemcileri",
  "site/Using_Zcash/Payment_Request_URIs": "Zcash Ödeme Talebi URI'leri",
  "site/Using_Zcash/Recovering_Funds": "Zcash Cüzdanı Fon Kurtarma",
  "site/Using_Zcash/Shielded_Pools": "Zcash Değer Havuzları",
  "site/Using_Zcash/Solswap": "Phantom Wallet'ta ZEC ile Nasıl Takas Yapılır",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Places to Spend ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testneti",
  "site/Using_Zcash/Transactions": "İşlemler",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Zcash TEX Adresleri Nedir?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Zcash Madencilik Rehberi: Kişisel Donanımla Bir Madencilik Havuzuna Katılmak",
  "site/Using_Zcash/Zcash_Mining_Pools": "Zcash Madencilik Havuzları",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "İçerik Üreticileri için Rehberler",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "AI araçları: Metin, Görsel, Video, Ses üretimi (çevrimiçi)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "AI araçları (yerel, çevrimdışı)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "VDO.Ninja ve OBS Studio kullanarak Community Yayını",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Hızlı Başlangıç: Zcon Öne Çıkanlarını Oluşturma",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "IPFS ve Brave Browser ile P2P Dosya Paylaşımı",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Canlı Yayın Kurulumu",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "IPFS Üzerinde Bir Site Yayınlama",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "GitHub Repo'sunu IPFS ile Sunma",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Video altyazısı oluşturma ve çeviri",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Topluluk Blogları",
  "site/Zcash_Community/Community_Links": "Zcash Topluluk Bağlantıları",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Zcash Topluluk Danışma Paneli",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Github Repo’sunu IPFS ile Sunma",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "IPFS Üzerinde Bir Web Sitesi Yayınlama",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Zcash Ekosistem Güvenliği",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Zcash Küresel Elçileri",
  "site/Zcash_Community/Zcash_Governance": "Zcash Fonlama ve Yönetişim Genel Bakışı",
  "site/Zcash_Community/Zcash_Media": "Zcash Medyası",
  "site/Zcash_Community/Zcash_Podcasts": "Podcastler",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Coinholder-Directed Retroactive Grants",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Kapanış)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Açık Geliştirme Laboratuvarı)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Sıfırdan Sıfır Bilgiye: CryptoNote Protokolü",
  "site/Zcash_Social_Media/Hash_Functions": "Sıfırdan Sıfır Bilgiye: Hash Fonksiyonları",
  "site/Zcash_Social_Media/Lelantus": "Sıfırdan Sıfır Bilgiye: Lelantus Protokolü",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Zero'dan Sıfır Bilgiye: Anımsatıcı Tohum İfadeleri",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast Epizot Sumarları",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Forsight Institute tarafından hazırlanan Shielded Transactions Podcast'i",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Zero Knowledge Podcast",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Digital Cash Network'te The Zcash Podcast",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Z2Z Podcast",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "Kripto için PGP Podcast'i",
  "site/Zcash_Social_Media/TEEs": "Sıfırdan Sıfır Bilgiye: Trusted Execution Environments (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Sıfırdan Sıfır Bilgiye: Transparent vs Shielded İşlemler ve Unified Address",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Sıfırdan Sıfır Bilgiye | Eğitim Serisi",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Full Nodes",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Zcash Lightwallet Düğümleri",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Zcash'te Kuantum Sonrası Güvenlik",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "ZAP1 Tasdik Protokolü",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Zcash Cüzdan Senkronizasyonu",
  "site/Zcash_Tech/Zebra_Full_Node": "Zebra için Sistem Gereksinimleri ve Ağ Yapılandırması",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Zcash'ı Gerçek Dünyada Kullanın",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Bir Satıcı Olarak Zcash ile Ödeme Kabul Etme",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Zcash ile Serbest Çalışan Gizlilik Kurulumu",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Zcash ile Gazeteci Gizlilik Kurulumu",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Shielded ZEC ile kayıt tutmak",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Zcash ile Özel Bir Topluluk Hazinesi Yönetin",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Zcash ile Bağışları Gizli Olarak Alın",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Kimliğinizi Bağlantılandırmadan Para Gönderin",
  "site/contribute/Community_Infrastructure": "ZecHub Topluluk Altyapı Çerçevesi",
  "site/contribute/Contributing_Guide": "ZecHub’a Katkıda Bulunmak",
  "site/contribute/Help_build_ZecHub": "ZecHub'ı Geliştirmeye Yardım Edin",
  "site/contribute/Style_Guide": "ZecHub Stil Rehberi",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "ZecWeekly Bülteni",
  "site/guides/Akash_Network_Zcashd": "zcashd'yi Akash Üzerinden Konsol ile Dağıtma",
  "site/guides/Akash_Network_Zebra": "Akash Network üzerinde Zebra nasıl çalıştırılır",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "Zcash Desteği ile BTCPay Server: Tam Kurulum ve Entegrasyon Rehberi",
  "site/guides/Blockchain_Explorers": "Blockchain Gezgini Araçları",
  "site/guides/Brave_Wallet_Guide": "Brave Wallet ile Shielded Zcash (ZEC) Gönderme ve Alma: Adım Adım Gizlilik Rehberi",
  "site/guides/Free2Z_Livestreaming": "Free2Z'de Canlı Yayın",
  "site/guides/Free2z_Live": "Free2z: Hesap kurulumu + Canlı yayın eğitimi",
  "site/guides/Hardened_Zebrad": "Güçlendirilmiş Zebra Tam Düğümü",
  "site/guides/Keystone_Zashi": "Keystone Zashi Kullanım Kılavuzu",
  "site/guides/Maya_Protocol": "Maya Merkeziyetsiz Borsası",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Geçiş Rehberi: zcashd'den Zebrad/Zallet'e",
  "site/guides/My_First_Zcash_Workbook": "İlk Zcash Çalışma Kitabım",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: bir zcashd Tam düğüm rehberi",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "Zingo ile RPi5 Zebra Lightwalletd",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Zebra Çalıştırmak için Raspberry Pi 4 Rehberi",
  "site/guides/ShapeShift_Zcash": "ShapeShift ve Zcash: Gizlilik Öncelikli Merkeziyetsiz Ticaret",
  "site/guides/Using_ZEC_Privately": "ZEC'i özel olarak kullanma",
  "site/guides/Using_ZEC_in_DeFi": "DeFi'de Zcash Kullanımı",
  "site/guides/Visualizing_Zcash_Addresses": "Zcash Adreslerini Görselleştirme",
  "site/guides/Visualizing_the_Zcash_Network": "Zcash Ağını Görselleştirme",
  "site/guides/Ywallet_FROST_Demo": "Ywallet FROST demosu",
  "site/guides/Zcash_Devtool": "Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Zcash Improvement Proposals",
  "site/guides/Zenith_Installation": "Zenith GUI Tam Düğüm Cüzdan Kurulumu",
  "site/guides/Zero-Knowledge_vs_Decoys": "Sıfır Bilgi ve Yem Tabanlı Sistemler",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: Emanet Olmadan Zcash Kabul Etmek",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig Rehberi",
  "site/guides/coinholder_log_parser/help": "Seçim Günlüğü Filtresi",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Ywallet FROST demosu",
  "site/guides/multisigdemo/MultiSigDemo": "MultiSig Demosu",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Atölye Günü 3",
  "site/tutorials/Exchanges": "Zcash Borsaları",
  "site/tutorials/Full_Node_Tutorials": "Tam Düğüm Eğitimleri",
  "site/tutorials/Using_Zcash": "Zcash Kullanımı İçin Eğitimler",
  "site/tutorials/Wallet_Tutorials": "Zcash Cüzdan Eğitimleri",
  "site/tutorials/shieldedNewsletter/readme": "Shielded Haber Bültenleri",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
