// AUTO-GENERATED — yo page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesYo: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Àwọn Ìbéèrè Tí Àwọn Èèyàn Máa Ń Béèrè",
  "site/Glossary_and_FAQs/Gallery": "Àwòrán àwòrán ògiri Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Ìkówèésí Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Àwọn Ẹ̀rọ 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti: Ẹ̀rọ-ìmọ̀ràn Tor Ìran Tẹ̀lé ní Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS (Àdàkọ:Àwọn ojúewé)",
  "site/Privacy_Tools/Namada_Protocol": "Àgbékalẹ̀ Namada",
  "site/Privacy_Tools/PGP_Encryption": "Ìpamọ́ tó dára gan-an (PGP)",
  "site/Privacy_Tools/Penumbra": "Àárín òkùnkùn",
  "site/Privacy_Tools/Secure_Messengers": "Àwọn Ońṣẹ́ Tó Dúró Ṣinṣin",
  "site/Privacy_Tools/Shade_Protocol": "Àkọsílẹ̀ Òjìji",
  "site/Privacy_Tools/Tor_and_I2P": "Ìdí Tó Fi Ṣe Pàtàkì Pé Kí Wọ́n Má Ṣe Jẹ́ Káwọn Èèyàn Mọ",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN àti dVPN",
  "site/Privacy_Tools/Web_Browsers": "Àwọn aṣàwákiri orí ayélujára",
  "site/Research/Dash_Zcash_Orchard_Integration": "Dash Integration of Zcash Orchard (Ìkójọpọ ìsọ̀rí)",
  "site/Research/Namada_Privacy_and_Best_Practices": "Àwọn Ìṣe Ààbò Àṣírí Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Ṣíṣí Ìhòòhò Ìhà Òkùnkùn: Ṣíṣàmúlò Owó-ìpamọ́ Oníṣòwò (CBDC) Láàárín Àwọn Òjìji Ìnáwó",
  "site/Research/Social_Media_Data_Collection": "Gbigba Awọn data Media Awujọ",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Ṣiṣayẹwo Awọn ifihan agbara Early On-chain & Social fun Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Awọn iru ẹrọ ohun-ini Imọ-ara Zero",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Bí Àdánwò Zcash tí a Ṣójútó Ṣe Ń Ṣiṣẹ Lóòótọ́",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Awọn aaye ti o pari: Awọn nọmba Awọn eto Cryptography ngbe ni",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Awọn Ikun Elliptic: Ibi ti Awọn bọtini ati Awọn adehun Zcash ti bi",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Ṣíṣàmúlò àti Ìpinnu: Àpótí tí a fi Òǹtẹ́lẹ̀ dì",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Àwọn Igi Merkle: Bí Blockchain ṣe máa ń rántí gbogbo nóòtì",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Àwọn Ẹ̀rí Tí Kò Ní Ìmọ̀kan: Fífi Hàn Pé Òótọ́ Lo Sọ Láìsọ Ìdí",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Ìlànà Ààbò, Láti Ìbẹ̀rẹ̀ Dé Ìparí",
  "site/Start_Here/Developer_Resources": "Àwọn Ìpèsè fún Olùgbéejáde",
  "site/Start_Here/Development_Fund": "Ìpèsè fún ìdàgbàsókè Zcash",
  "site/Start_Here/Network_Upgrades": "Àwọn Àtúnṣe sí Ìpínlẹ̀ Zcash",
  "site/Start_Here/New_User_Guide": "Itọsọna Olumulo Zcash Tuntun",
  "site/Start_Here/Using_This_Wiki": "Lílo Wiki yìí",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Àwọn Ìlànà Zcash",
  "site/Start_Here/What_is_ZecHub": "Kí ni ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Àwọn Ìlànà Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Àwọn Ìlànà Zcash",
  "site/Start_Here/Zcash_Resources": "Awọn orisun Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Àwọn Olùwádìí Blockchain",
  "site/Using_Zcash/Buying_ZEC": "Gbígba Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Awọn irinṣẹ Zcash fun Awọn Ẹlẹda: Tipping & Profile Platforms",
  "site/Using_Zcash/Custodial_Exchanges": "Custodial Exchanges",
  "site/Using_Zcash/Encifher_Swaps": "Private SOL/USDC -> ZEC Swap Lilo Encrypt.trade",
  "site/Using_Zcash/Faucets": "Awọn faucets",
  "site/Using_Zcash/Memos": "Àwọn ìwé ìrántí",
  "site/Using_Zcash/Metamask_Snap": "MetaMask Zcash Snap Integration Guide[àtúnṣe  àtúnṣe àmìọ̀rọ̀]",
  "site/Using_Zcash/Mobile_Top_Ups": "Àtúnṣe orí ẹ̀rọ alágbèéká nípasẹ̀ Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Non-Custodial Exchanges",
  "site/Using_Zcash/Payment_Processors": "Àwọn Ẹ̀rọ Ìṣiṣẹ́ Ìsanwó Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "Awọn URI Ibeere isanwo Zcash",
  "site/Using_Zcash/Recovering_Funds": "Gbigba pada Owo apo apamọwọ Zcash",
  "site/Using_Zcash/Shielded_Pools": "Àwọn Àkójọ Iye Zcash",
  "site/Using_Zcash/Solswap": "Bá a ṣe lè pààrọ̀ ZEC nínú Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Àwọn Ibi Tó Yẹ Kó O Ti Lo Owó ZEC",
  "site/Using_Zcash/Testnet": "Ìdánwò Zcash",
  "site/Using_Zcash/Transactions": "Àwọn Àdéhùn",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Kí Ni Àwọn Adirẹsi Zcash TEX?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Itọsọna iwakusa Zcash: Darapọ mọ adagun iwakusa pẹlu ohun elo ara ẹni",
  "site/Using_Zcash/Zcash_Mining_Pools": "Àwọn Ìpínlẹ̀ Ìwakùsà Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz - Àwọn ojúewé wọ̀nyí jápọ̀ mọ́",
  "site/ZFAV_Club/Guides_for_Creators": "Àwọn Atọ́nà fún Àwọn Oníṣẹ̀dá",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Awọn irinṣẹ AI: Text, Image, Video, Audio generating (online)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Awọn irinṣẹ AI (ti agbegbe, ti ko ni asopọ)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Ìpolongo Ìsọfúnni nípa Ìpínlẹ̀ ní lílo VDO.Ninja àti OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Ìbẹ̀rẹ̀ Yára: Ṣídá Àwọn Àkọsílẹ̀ Zcon",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "P2P File Sharing pẹlu IPFS ati Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Ìtòlẹ́sẹẹsẹ ìsọfúnni tí ó wà láàyè",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Tẹ Àwòrán kan jáde lórí IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Ṣiṣẹ Repo GitHub pẹlu IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Ṣiṣẹda atunkọ fidio ati itumọ",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Àwọn Ìkànnì Àwùjọ",
  "site/Zcash_Community/Community_Links": "Zcash Community Links",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Àkọlé àwòrán Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Ìgbìmọ̀ Onímọ̀ràn Ìjọ Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Ṣiṣẹ Repo Github pẹlu IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Tẹ Àwòrán Ìkànnì kan lórí IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Ààbò Ìpínlẹ̀ Ọ̀rọ̀-ayé Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Àwọn Aṣojú Àgbáyé Zcash",
  "site/Zcash_Community/Zcash_Governance": "Ìfúnná owó àti Ìdarí Zcash",
  "site/Zcash_Community/Zcash_Media": "Ìròyìn Zcash",
  "site/Zcash_Community/Zcash_Podcasts": "Àwọn ìgbóhùnsáfẹ́",
  "site/Zcash_Community/Zcon_Archive": "Zcon (ìmọ̀)",
  "site/Zcash_Community/Zcon_Vozes": "Àwọn ohùn Zcon",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Awọn Ifunni ti o wa ni Titọ si Olutọju-Iṣura",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Ẹgbẹ́ Ìdáàbòbò Ìpamọ́-Ọ̀rọ̀-Iṣuna (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Olóyè",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Ìmọ̀ láti òfo dé òfo: Ìlànà CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "Ìmọ̀ Nẹ́rẹ́ sí Nẹ̀rẹ́: Àwọn Àṣiṣẹ́ Hash",
  "site/Zcash_Social_Media/Lelantus": "Ìmọ̀ Nẹ́rẹ́ sí Nẹ̀rẹ́: Àgbékalẹ̀ Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Ìmọ̀ Àìmọ̀: Àwọn Ọ̀rọ̀-Òwe tí a fi ń ṣe àtúnyẹ̀wò",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "ZK Podcast Ìpínlẹ̀ Ìtàn",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Àwọn Àdéhùn Ìpamọ́ tí Ilé-Iṣẹ́ Forsight ṣe",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Ìsọfúnni Òye-Kò-Láti-Ohun",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Àkọlé àwòrán Zcash Podcast lórí ẹ̀rọ-ayélujára Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Àkọlé àwòrán Z2Z Podcast",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast (Àdàkọ)",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP fún Crypto Podcast",
  "site/Zcash_Social_Media/TEEs": "Imọ-ara-ara si-ara: Awọn agbegbe Iṣẹ Igbẹkẹle (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Imọ-ara-ara: Awọn Iṣowo Transparent vs Shielded & Awọn adirẹsi Ajọpọ",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Ìmọ̀ Láti Nítòsí Nítòòsí.",
  "site/Zcash_Tech/FROST": "FROST [ìyẹn ìrì dídì]",
  "site/Zcash_Tech/Full_Nodes": "Àwọn Nódù Pípé",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Awọn Nọ́ọ̀dù Zcash Lightwallet",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Ààbò Post-Quantum nínú Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Àwọn Kókó Ìwòran",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Àkọsílẹ̀ Ìjẹ́rìí ZAP1",
  "site/Zcash_Tech/Zaino": "Àkọsílẹ̀ Zaino",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Awọn ohun-ini Zcash Shielded",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Ṣiṣẹpọ apamọwọ Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Awọn ibeere eto ati iṣeto nẹtiwọọki fun Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP àti ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Lo Zcash ní Ayé Òtítọ́",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accept Payments as a Merchant with Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Freelancer Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Journalist Privacy Setup with Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Títẹ̀síwájú àkọsílẹ̀ pẹ̀lú ZEC tí a fi ààbò bo",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Run a Private Community Treasury with Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Receive Donations Privately with Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Send Money Without Linking Your Identity",
  "site/contribute/Community_Infrastructure": "Àlàfo Ìpèsè Ìpínlẹ̀ Ìlú ZecHub",
  "site/contribute/Contributing_Guide": "Ṣíṣèrànwọ́ sí ZecHub",
  "site/contribute/Help_build_ZecHub": "Ran Àwòrán ZecHub",
  "site/contribute/Style_Guide": "Atọ́nà Ọ̀nà ZecHub",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "Ìwé ìròyìn ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Gbigba zcashd si Akash nipasẹ Iṣakoso",
  "site/guides/Akash_Network_Zebra": "Bii o ṣe le ṣiṣẹ Zebra lori Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge ì í ì ë ¤",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server pẹlu Atilẹyin Zcash: Itọsọna fifi sori ẹrọ ati isopọpọ ni kikun",
  "site/guides/Blockchain_Explorers": "Àwọn Olùwádìí Blockchain",
  "site/guides/Brave_Wallet_Guide": "Bii o ṣe le firanṣẹ ati Gbigba Zcash ti o ni aabo (ZEC) pẹlu Brave Wallet: Itọsọna Asiri Igbesẹ-ni-Igbesọ kan",
  "site/guides/Free2Z_Livestreaming": "Àkọsílẹ̀ gbígbóná lórí Free2Z",
  "site/guides/Free2z_Live": "Free2z: Ṣiṣeto akọọlẹ + Itọsọna Live Stream",
  "site/guides/Hardened_Zebrad": "Àwọn Ẹranko Zebra Tí Wọ́n Ti Gbé Ga",
  "site/guides/Keystone_Zashi": "Atọ́nà Olùṣàmúlò Keystone Zashi",
  "site/guides/Maya_Protocol": "Maya Decentralized Exchange (Àdàpòsòpò Àkànlò)",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Itọsọna Iṣilọ: Lati zcashd si Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Ìwé-ìṣiṣẹ́ Zcash Mi Àkọ́kọ́",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: a zcashd Ìtọ́sọ́nà gbogbo-nọ́ọ̀dù",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd pẹlu Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Raspberry Pi 4 Itọsọna fun Ṣiṣẹ Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift àti Zcash: Ìpamọ́-Kọ́kọ́ Ìṣòwò Àkànṣe",
  "site/guides/Using_ZEC_Privately": "Lílò ZEC, ní ìdákọ́ńkọ́",
  "site/guides/Using_ZEC_in_DeFi": "Lílo Zcash nínú DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Fífi ojú wo àwọn Adirẹsi Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Ṣíṣe àwòrán Ìpínlẹ̀ Zcash",
  "site/guides/Ywallet_FROST_Demo": "Àkọlé àwòrán Ywallet FROST",
  "site/guides/Zcash_Devtool": "Ohun èlò ìjìnlẹ̀ Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Àwọn Àbá fún Àtúnṣe Zcash",
  "site/guides/Zenith_Installation": "Zenith GUI Full Node Wallet ìfi sori ẹrọ",
  "site/guides/Zero-Knowledge_vs_Decoys": "Ìmòye Òní lòdì sí Àwọn Ẹ̀rọ Tí Ó Gbé Orí Ìdẹkùn Lárugẹ",
  "site/guides/Zgo_Payment_Processor": "Olùṣiṣẹ́ Ìsanwó ZGo: Gbígba Zcash Láìsí Ìtọ́jú",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Zkool Multisig Guide",
  "site/guides/coinholder_log_parser/help": "Àtòjọ ìdìbò",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Àkọlé àwòrán Ywallet FROST",
  "site/guides/multisigdemo/MultiSigDemo": "Àwòfiṣàpẹẹrẹ MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Ọjọ́ Kẹta Ìdániléèwé",
  "site/tutorials/Exchanges": "Awọn paṣipaarọ Zcash",
  "site/tutorials/Full_Node_Tutorials": "Àwọn Ẹ̀kọ́-ẹ̀rọ-nọ́ọ̀dù Kíkún",
  "site/tutorials/Using_Zcash": "Awọn ẹkọ fun Lilo Zcash",
  "site/tutorials/Wallet_Tutorials": "Àwọn Ẹ̀kọ́-ọ̀nà Ìpamọ́ Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Àwọn Ìwé Ìròyìn tí a Ṣójútó",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Bẹta",
};
