// AUTO-GENERATED — es page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `es` locale. Regenerate with
// scratchpad/gen_page_titles_loc.py after adding/retitling translated pages.
export const pageTitlesEs: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Preguntas Frecuentes",
  "site/Glossary_and_FAQs/Gallery": "Galería de fondos de pantalla de Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Biblioteca de Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Dispositivos de hardware para 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti: El cliente Tor de nueva generación en Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada Protocol",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Mensajeros seguros",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Por qué importa la privacidad",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN y dVPN",
  "site/Privacy_Tools/Web_Browsers": "Navegadores web",
  "site/Research/Dash_Zcash_Orchard_Integration": "Integración de Dash de Zcash Orchard",
  "site/Research/Namada_Privacy_and_Best_Practices": "Mejores prácticas de privacidad de Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Revelando el lado oscuro: navegando la odisea de las Monedas Digitales de Banco Central (CBDC) en medio de las sombras financieras",
  "site/Research/Social_Media_Data_Collection": "Recolección de datos en redes sociales",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Seguimiento de las primeras señales on-chain y sociales para Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Plataformas de Activos de Conocimiento Cero",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Cómo funciona realmente una transacción blindada de Zcash",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Campos finitos: el sistema numérico en el que vive la criptografía",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Curvas elípticas: donde nacen las claves y los compromisos de Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing y Compromisos: El sobre sellado mágico",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Árboles de Merkle: Cómo la Blockchain Recuerda Cada Nota",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Pruebas de conocimiento cero: demostrar que tienes razón sin decir por qué",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "El Protocolo Blindado, de extremo a extremo",
  "site/Start_Here/Developer_Resources": "Recursos para desarrolladores",
  "site/Start_Here/Development_Fund": "Fondo de Desarrollo de Zcash",
  "site/Start_Here/Network_Upgrades": "Actualizaciones de la Red Zcash",
  "site/Start_Here/New_User_Guide": "Guía para nuevos usuarios de Zcash",
  "site/Start_Here/Using_This_Wiki": "Cómo usar esta wiki",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Conceptos básicos de Zcash",
  "site/Start_Here/What_is_ZecHub": "¿Qué es ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Conceptos básicos de Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Conceptos básicos de Zcash",
  "site/Start_Here/Zcash_Resources": "Recursos de Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Exploradores de Blockchain",
  "site/Using_Zcash/Buying_ZEC": "Obtención de Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Herramientas de Zcash para Creadores: Plataformas de Propinas y Perfiles",
  "site/Using_Zcash/Custodial_Exchanges": "Exchanges con custodia",
  "site/Using_Zcash/Encifher_Swaps": "Intercambio privado de SOL/USDC -> ZEC usando Encrypt.trade",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "Memos",
  "site/Using_Zcash/Metamask_Snap": "Guía de integración de MetaMask Zcash Snap",
  "site/Using_Zcash/Mobile_Top_Ups": "Recarga móvil usando Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Exchanges no custodiales",
  "site/Using_Zcash/Payment_Processors": "Procesadores de pagos de Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "URI de solicitud de pago de Zcash",
  "site/Using_Zcash/Recovering_Funds": "Recuperación de fondos de la billetera Zcash",
  "site/Using_Zcash/Shielded_Pools": "Pools de Valor de Zcash",
  "site/Using_Zcash/Solswap": "Cómo intercambiar por ZEC en Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Lugares para gastar ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Transacciones",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "¿Qué son las direcciones TEX de Zcash?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Guía de minería de Zcash: unirse a un pool de minería con hardware personal",
  "site/Using_Zcash/Zcash_Mining_Pools": "Pools de minería de Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Guías para creadores",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Herramientas de IA: generación de texto, imagen, video y audio (en línea)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Herramientas de IA (locales, sin conexión)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Transmisión comunitaria usando VDO.Ninja y OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Inicio rápido: Crear momentos destacados de Zcon",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "Intercambio de archivos P2P con IPFS y el navegador Brave",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Configuración de transmisión en vivo",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Publicar un sitio en IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Servir repositorio de GitHub con IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Generación y traducción de subtítulos de video",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Blogs de la comunidad",
  "site/Zcash_Community/Community_Links": "Enlaces de la comunidad de Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Panel Asesor Comunitario de Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Servir un repositorio de Github con IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Publicar un sitio web en IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Seguridad del ecosistema Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Embajadores Globales de Zcash",
  "site/Zcash_Community/Zcash_Governance": "Resumen de financiación y gobernanza de Zcash",
  "site/Zcash_Community/Zcash_Media": "Medios de Zcash",
  "site/Zcash_Community/Zcash_Podcasts": "Podcasts",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Subvenciones Retroactivas Dirigidas por Coinholders",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Sunset)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/ZKAV": "Club ZKAV",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Subvenciones Comunitarias de Zcash",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "De cero a conocimiento cero: Protocolo CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "De cero a conocimiento cero: Funciones hash",
  "site/Zcash_Social_Media/Lelantus": "De cero a conocimiento cero: Protocolo Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "De cero a conocimiento cero: Frases semilla mnemotécnicas",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Resúmenes de episodios de ZK Podcast",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Podcast Shielded Transactions de Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Podcast de conocimiento cero",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "El Podcast de Zcash en Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "El Podcast Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Podcast de Zcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "Podcast PGP para Crypto",
  "site/Zcash_Social_Media/TEEs": "De cero a conocimiento cero: Entornos de Ejecución Confiables (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "De cero a conocimiento cero: Transacciones Transparentes vs Blindadas y Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "De cero al conocimiento cero | Serie educativa",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nodos completos",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Nodos Lightwallet de Zcash",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Seguridad poscuántica en Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Protocolo de Atestación ZAP1",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Activos Blindados de Zcash",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Sincronización de monederos Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Requisitos del sistema y configuración de red para Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP y ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Usa Zcash en el mundo real",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Acepta pagos como comerciante con Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Configuración de privacidad para freelancers con Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Configuración de privacidad para periodistas con Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Mantener registros con ZEC blindado",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Gestiona una tesorería comunitaria privada con Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Recibe donaciones de forma privada con Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Envía dinero sin vincular tu identidad",
  "site/contribute/Community_Infrastructure": "Marco de Infraestructura Comunitaria de ZecHub",
  "site/contribute/Contributing_Guide": "Contribuir a ZecHub",
  "site/contribute/Help_build_ZecHub": "Ayuda a construir ZecHub",
  "site/contribute/Style_Guide": "Guía de estilo de ZecHub",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "Boletín ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Despliegue de zcashd en Akash mediante Console",
  "site/guides/Akash_Network_Zebra": "Cómo ejecutar Zebra en Akash Network",
  "site/guides/Avalanche_RedBridge": "RedBridge de Zcash Avalanche",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server con soporte para Zcash: guía completa de instalación e integración",
  "site/guides/Blockchain_Explorers": "Exploradores de Blockchain",
  "site/guides/Brave_Wallet_Guide": "Cómo enviar y recibir Zcash (ZEC) blindado con Brave Wallet: una guía de privacidad paso a paso",
  "site/guides/Free2Z_Livestreaming": "Transmisión en vivo en Free2Z",
  "site/guides/Free2z_Live": "Free2z: Tutorial de configuración de cuenta + transmisión en vivo",
  "site/guides/Hardened_Zebrad": "Nodo completo de Zebra reforzado",
  "site/guides/Keystone_Zashi": "Guía del usuario de Keystone Zashi",
  "site/guides/Maya_Protocol": "Intercambio descentralizado Maya",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Guía de migración: de zcashd a Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Mi Primer Cuaderno de Zcash",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: una guía de nodo completo de zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd con Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Guía de Raspberry Pi 4 para ejecutar Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift y Zcash: comercio descentralizado con la privacidad como prioridad",
  "site/guides/Using_ZEC_Privately": "Usar ZEC de forma privada",
  "site/guides/Using_ZEC_in_DeFi": "Uso de Zcash en DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Visualizando direcciones de Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Visualización de la red de Zcash",
  "site/guides/Ywallet_FROST_Demo": "Demostración de Ywallet FROST",
  "site/guides/Zcash_Devtool": "El Devtool de Zcash",
  "site/guides/Zcash_Improvement_Proposals": "Propuestas de Mejora de Zcash",
  "site/guides/Zenith_Installation": "Instalación de la billetera de nodo completo Zenith GUI",
  "site/guides/Zero-Knowledge_vs_Decoys": "Conocimiento Cero vs sistemas basados en señuelos",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: aceptar Zcash sin custodia",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Guía de Multisig de Zkool",
  "site/guides/coinholder_log_parser/help": "Filtro de registro electoral",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Demostración de FROST en Ywallet",
  "site/guides/multisigdemo/MultiSigDemo": "Demostración de MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Día 3 del taller",
  "site/tutorials/Exchanges": "Intercambios de Zcash",
  "site/tutorials/Full_Node_Tutorials": "Tutoriales de nodos completos",
  "site/tutorials/Using_Zcash": "Tutoriales para usar Zcash",
  "site/tutorials/Wallet_Tutorials": "Tutoriales de carteras de Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Boletines protegidos",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
