// AUTO-GENERATED — Italian page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `it` locale. Regenerate with
// scratchpad/gen_page_titles.py after adding/retitling translated pages.
export const pageTitlesIt: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Domande Frequenti",
  "site/Glossary_and_FAQs/Gallery": "Galleria di Sfondi Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Zcash Library",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Dispositivi Hardware 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti: il client Tor di nuova generazione in Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Namada Protocol",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Messaggistica sicura",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Perché la Privacy è Importante",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN e dVPN",
  "site/Privacy_Tools/Web_Browsers": "Browser web",
  "site/Research/Dash_Zcash_Orchard_Integration": "Integrazione di Zcash Orchard in Dash",
  "site/Research/Namada_Privacy_and_Best_Practices": "Best practice per la privacy su Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Svelando il lato oscuro: navigare l'odissea delle Central Bank Digital Currency (CBDC) tra le ombre finanziarie",
  "site/Research/Social_Media_Data_Collection": "Raccolta dati sui social media",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Tracciare i Primi Segnali On-chain e Social per Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Piattaforme di Asset a Conoscenza Zero",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Come funziona davvero una transazione schermata di Zcash",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Campi finiti: il sistema numerico in cui vive la crittografia",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Curve Ellittiche: Dove Nascono le Chiavi e gli Impegni di Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hashing e impegni: la magica busta sigillata",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Alberi di Merkle: come la blockchain ricorda ogni nota",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Prove a conoscenza zero: dimostrare di avere ragione senza dire perché",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Il Protocollo Schermato, da Cima a Fondo",
  "site/Start_Here/Developer_Resources": "Risorse per sviluppatori",
  "site/Start_Here/Development_Fund": "Fondo di Sviluppo di Zcash",
  "site/Start_Here/Network_Upgrades": "Aggiornamenti della rete Zcash",
  "site/Start_Here/New_User_Guide": "Guida per i nuovi utenti di Zcash",
  "site/Start_Here/Using_This_Wiki": "Usare questa Wiki",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Le basi di Zcash",
  "site/Start_Here/What_is_ZecHub": "Cos'è ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Le basi di Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Nozioni di base su Zcash",
  "site/Start_Here/Zcash_Resources": "Risorse su Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Esploratori di blockchain",
  "site/Using_Zcash/Buying_ZEC": "Comprare Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Strumenti Zcash per i creatori: piattaforme per mance e profili",
  "site/Using_Zcash/Custodial_Exchanges": "Exchange Custodiali",
  "site/Using_Zcash/Encifher_Swaps": "Scambio privato SOL/USDC -> ZEC utilizzando Encrypt.trade",
  "site/Using_Zcash/Faucets": "Rubinetti",
  "site/Using_Zcash/Memos": "Memos",
  "site/Using_Zcash/Metamask_Snap": "Guida all'integrazione Zcash Snap di Metamask",
  "site/Using_Zcash/Mobile_Top_Ups": "Ricarica mobile con Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Exchange Non-Custodiali",
  "site/Using_Zcash/Payment_Processors": "Processori di pagamento Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "URI di Richiesta di Pagamento Zcash",
  "site/Using_Zcash/Recovering_Funds": "Recupero fondi dal portafoglio Zcash",
  "site/Using_Zcash/Shielded_Pools": "Le pool di valori di Zcash",
  "site/Using_Zcash/Solswap": "Come scambiare gli ZEC in Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Luoghi dove spendere ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Transazioni",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Cosa Sono gli Indirizzi TEX di Zcash?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Guida al mining di Zcash: Partecipare a un pool di mining con hardware personale",
  "site/Using_Zcash/Zcash_Mining_Pools": "Mining Pool di Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Guide per i Creatori",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Strumenti di IA: generazione di testo, immagini, video, audio (online)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Strumenti IA (locali, offline)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Trasmissioni comunitarie con VDO.Ninja e OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Guida rapida: creare i momenti salienti di Zcon",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "Condivisione File P2P con IPFS e Brave Browser",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Configurazione del Livestream",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Pubblicare un sito su IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Servire un repository GitHub con IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Generazione e traduzione dei sottotitoli dei video",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Blog della community",
  "site/Zcash_Community/Community_Links": "Link della Community di Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Pannello Consultivo della Comunità Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Servire un repository Github con IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Pubblicare un sito web su IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Sicurezza dell'Ecosistema Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Ambasciatori Globali Zcash",
  "site/Zcash_Community/Zcash_Governance": "Panoramica su Finanziamento e Governance di Zcash",
  "site/Zcash_Community/Zcash_Media": "Zcash Media",
  "site/Zcash_Community/Zcash_Podcasts": "Podcast",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Coinholder-Directed Retroactive Grants",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "Zero to Zero Knowledge: il protocollo CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "Zero to Zero Knowledge: Hash Functions",
  "site/Zcash_Social_Media/Lelantus": "Zero to Zero Knowledge: il protocollo Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "Zero to Zero Knowledge: frasi seed mnemoniche",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Riassunti degli Episodi del ZK Podcast",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Shielded Transactions Podcast del Foresight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Zero Knowledge Podcast",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "The Zcash Podcast sulla Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Il podcast Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Zcast Podcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP for Crypto Podcast",
  "site/Zcash_Social_Media/TEEs": "Zero to Zero Knowledge: Trusted Execution Environments (TEE)",
  "site/Zcash_Social_Media/Zcash_Addresses": "Zero to Zero Knowledge: transazioni trasparenti vs schermate e Unified Address",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "Zero to Zero Knowledge | Serie educativa",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nodi Completi",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Nodi Lightwallet di Zcash",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Sicurezza Post-Quantistica in Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Protocollo di attestazione ZAP1",
  "site/Zcash_Tech/Zaino": "Zaino Indexer",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Sincronizzazione del portafoglio Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Requisiti di sistema e configurazione di rete per Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP e ZK-SNARKs",
  "site/Zcash_Use_Cases/About": "Usa Zcash nel Mondo Reale",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accettare pagamenti come esercente con Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Configurazione della privacy per freelance con Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Configurazione della Privacy per Giornalisti con Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Tenere la contabilità con ZEC schermati",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Gestire una tesoreria di comunità privata con Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Ricevere donazioni in privato con Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Inviare denaro senza collegare la tua identità",
  "site/contribute/Community_Infrastructure": "ZecHub Community Infrastructure Framework",
  "site/contribute/Contributing_Guide": "Contribuire a ZecHub",
  "site/contribute/Help_build_ZecHub": "Aiuta a costruire ZecHub",
  "site/contribute/Style_Guide": "Guida di Stile di ZecHub",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "Newsletter ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Distribuire zcashd su Akash tramite Console",
  "site/guides/Akash_Network_Zebra": "Come eseguire Zebra su Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server con supporto Zcash: guida completa all'installazione e all'integrazione",
  "site/guides/Blockchain_Explorers": "Block explorer",
  "site/guides/Brave_Wallet_Guide": "Come inviare e ricevere Zcash (ZEC) schermato con Brave Wallet: una guida passo passo alla privacy",
  "site/guides/Free2Z_Livestreaming": "Livestreaming su Free2Z",
  "site/guides/Free2z_Live": "Free2z: configurazione dell'account + tutorial sul Livestream",
  "site/guides/Hardened_Zebrad": "Nodo completo Zebra rafforzato",
  "site/guides/Keystone_Zashi": "Guida utente Keystone Zashi",
  "site/guides/Maya_Protocol": "Maya Decentralised Exchange",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Guida alla migrazione: da zcashd a Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "My First Zcash Workbook",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: guida a un nodo completo zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd con Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Guida al Raspberry Pi 4 per eseguire Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift e Zcash: Trading Decentralizzato che Mette la Privacy al Primo Posto",
  "site/guides/Using_ZEC_Privately": "Usare ZEC, in privato",
  "site/guides/Using_ZEC_in_DeFi": "Usare Zcash nella DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Visualizzare gli indirizzi Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Visualizzare la rete Zcash",
  "site/guides/Ywallet_FROST_Demo": "Demo FROST con Ywallet",
  "site/guides/Zcash_Devtool": "Il Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "Zcash Improvement Proposals",
  "site/guides/Zenith_Installation": "Installazione del wallet full node con GUI Zenith",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Knowledge vs sistemi basati su decoy",
  "site/guides/Zgo_Payment_Processor": "ZGo Payment Processor: accettare Zcash senza custodia",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Guida al Multisig di Zkool",
  "site/guides/coinholder_log_parser/help": "Filtro dei log delle elezioni",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Demo FROST con Ywallet",
  "site/guides/multisigdemo/MultiSigDemo": "Demo MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Workshop Giorno 3",
  "site/tutorials/Exchanges": "Exchange Zcash",
  "site/tutorials/Full_Node_Tutorials": "Tutorial sui full node",
  "site/tutorials/Using_Zcash": "Tutorial per usare Zcash",
  "site/tutorials/Wallet_Tutorials": "Tutorial sui wallet Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Newsletter schermate",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
