// AUTO-GENERATED — ru page titles (first H1, HTML stripped) keyed by
// the SideMenu item path. Regenerate with gen_page_titles_loc.py.
export const pageTitlesRu: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Часто задаваемые вопросы",
  "site/Glossary_and_FAQs/Gallery": "Галерея обоев Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Библиотека Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Аппаратные устройства 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti: Tor-клиент нового поколения на Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Протокол Namada",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Безопасные мессенджеры",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Почему конфиденциальность важна",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN и dVPN",
  "site/Privacy_Tools/Web_Browsers": "Веб-браузеры",
  "site/Research/Dash_Zcash_Orchard_Integration": "Интеграция Zcash Orchard в Dash",
  "site/Research/Namada_Privacy_and_Best_Practices": "Лучшие практики конфиденциальности в Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Раскрывая тёмную сторону: путь по одиссее цифровой валюты центрального банка (CBDC) среди финансовых теней",
  "site/Research/Social_Media_Data_Collection": "Сбор данных в социальных сетях",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Отслеживание ранних ончейн- и социальных сигналов для Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Платформы активов с нулевым разглашением",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Как на самом деле работает shielded-транзакция Zcash",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Конечные поля: числовая система, в которой живёт криптография",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Эллиптические кривые: где рождаются ключи и коммитменты Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Хеширование и коммитменты: магический запечатанный конверт",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Деревья Меркла: как блокчейн помнит каждую note",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Доказательства с нулевым разглашением: доказываем, что вы правы, не раскрывая почему",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Shielded Protocol от начала до конца",
  "site/Start_Here/Developer_Resources": "Ресурсы для разработчиков",
  "site/Start_Here/Development_Fund": "Фонд развития Zcash",
  "site/Start_Here/Network_Upgrades": "Обновления сети Zcash",
  "site/Start_Here/New_User_Guide": "Руководство для нового пользователя Zcash",
  "site/Start_Here/Using_This_Wiki": "Как пользоваться этой Wiki",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Основы Zcash",
  "site/Start_Here/What_is_ZecHub": "Что такое ZecHub?",
  "site/Start_Here/ZEC_Use_Cases": "Основы Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Основы Zcash",
  "site/Start_Here/Zcash_Resources": "Ресурсы Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Обозреватели блокчейна",
  "site/Using_Zcash/Buying_ZEC": "Получение Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Инструменты Zcash для создателей контента: чаевые и платформы профилей",
  "site/Using_Zcash/Custodial_Exchanges": "Кастодиальные биржи",
  "site/Using_Zcash/Encifher_Swaps": "Приватный обмен SOL/USDC -> ZEC с помощью Encrypt.trade",
  "site/Using_Zcash/Faucets": "Краны",
  "site/Using_Zcash/Memos": "Memos",
  "site/Using_Zcash/Metamask_Snap": "Руководство по интеграции MetaMask Zcash Snap",
  "site/Using_Zcash/Mobile_Top_Ups": "Пополнение мобильного счёта с помощью Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Некастодиальные биржи",
  "site/Using_Zcash/Payment_Processors": "Платёжные процессоры Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "URI-запросы платежей Zcash",
  "site/Using_Zcash/Recovering_Funds": "Восстановление средств кошелька Zcash",
  "site/Using_Zcash/Shielded_Pools": "Пулы ценности Zcash",
  "site/Using_Zcash/Solswap": "Как обменять активы на ZEC в Phantom Wallet",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Места, где можно потратить ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Транзакции",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Что такое TEX-адреса Zcash?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Руководство по майнингу Zcash: подключение к майнинг-пулу с использованием личного оборудования",
  "site/Using_Zcash/Zcash_Mining_Pools": "Пулы для майнинга Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Руководства для создателей",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Инструменты искусственного интеллекта: генерация текста, изображений, видео и аудио (онлайн)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Инструменты искусственного интеллекта (локальные, оффлайн)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Общественное вещание с использованием VDO.Ninja и OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Быстрый старт: Создание Zcon Highlights",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "P2P-Обмен файлами с использованием IPFS и браузера Brave",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Настройка прямой трансляции",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Опубликование сайта на IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Размещение репозитория GitHub через IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Генерация и перевод субтитров видео",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Блоги сообщества",
  "site/Zcash_Community/Community_Links": "Ссылки сообщества Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Консультативная панель сообщества Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Размещение репозитория Github через IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Опубликуйте веб-сайт в IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Безопасность экосистемы Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Глобальные амбассадоры Zcash",
  "site/Zcash_Community/Zcash_Governance": "Обзор финансирования и управления Zcash",
  "site/Zcash_Community/Zcash_Media": "Zcash Media",
  "site/Zcash_Community/Zcash_Podcasts": "Подкасты",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Ретроактивные гранты, управляемые держателями монет",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Финансовая приватность Фонд (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/Sovright": "Sovright",
  "site/Zcash_Organizations/ZKAV": "ZKAV Club",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "От нуля до нулевого знания: Протокол CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "От нуля до знания с нулевым раскрытием: Хеш-функции",
  "site/Zcash_Social_Media/Lelantus": "От нуля до нулевого знания: протокол Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "От нуля к Zero Knowledge: мнемонические seed-фразы",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Подкаст ZK: Сводки эпизодов",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Подкаст \"Защищенные транзакции\" от Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Подкаст Zero Knowledge",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Подкаст Zcash на Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Подкаст Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Подкаст Zcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "PGP для криптовалютного подкаста",
  "site/Zcash_Social_Media/TEEs": "От нуля до нулевого знания: Доверенные среды исполнения (TEE)",
  "site/Zcash_Social_Media/Zcash_Addresses": "От нуля к Zero Knowledge: прозрачные и экранированные транзакции и Unified Addresses",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "От нуля к нулевому знанию | Образовательный курс",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Полные узлы",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Лайтвэллет-ноды Zcash",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Квантовая безопасность в Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Key",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Протокол подтверждения ZAP1",
  "site/Zcash_Tech/Zaino": "Индексер Zaino",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Защищенные активы Zcash",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Синхронизация кошелька Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Системные требования и настройка сети для Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP и ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Использование Zcash в реальном мире",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Принимайте платежи в качестве продавца с использованием Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Настройка приватности для фрилансера с использованием Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Настройка приватности для журналистов с использованием Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Ведение записей с использованием защищенных ZEC",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Управление приватным сообщественным фондом с использованием Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Получайте пожертвования в приватном порядке с помощью Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Отправляйте деньги без привязки к вашей личности",
  "site/contribute/Community_Infrastructure": "Фреймворк инфраструктуры сообщества ZecHub",
  "site/contribute/Contributing_Guide": "Участие в ZecHub",
  "site/contribute/Help_build_ZecHub": "Помогите развивать ZecHub",
  "site/contribute/Style_Guide": "Руководство по стилю ZecHub",
  "site/contribute/ZecHub_DAO": "DAO ZecHub",
  "site/contribute/ZecWeekly_Newsletter": "Рассылка ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Развёртывание zcashd в Akash через Console",
  "site/guides/Akash_Network_Zebra": "Как запустить Zebra в сети Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server с поддержкой Zcash: полное руководство по установке и интеграции",
  "site/guides/Blockchain_Explorers": "Обозреватели блокчейна",
  "site/guides/Brave_Wallet_Guide": "Как отправлять и получать защищённый Zcash (ZEC) с помощью Brave Wallet: пошаговое руководство по приватности",
  "site/guides/Free2Z_Livestreaming": "Прямые трансляции на Free2Z",
  "site/guides/Free2z_Live": "Free2z: Настройка аккаунта + руководство по прямым трансляциям",
  "site/guides/Hardened_Zebrad": "Защищённый полный узел Zebra",
  "site/guides/Keystone_Zashi": "Руководство пользователя Keystone Zashi",
  "site/guides/Maya_Protocol": "Децентрализованная биржа Maya",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Руководство по миграции: с zcashd на Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Моя первая рабочая тетрадь по Zcash",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4: руководство по полному узлу zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd с Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Руководство по запуску Zebra на Raspberry Pi 4",
  "site/guides/ShapeShift_Zcash": "ShapeShift и Zcash: децентрализованная торговля с приоритетом конфиденциальности",
  "site/guides/Using_ZEC_Privately": "Использование ZEC с сохранением приватности",
  "site/guides/Using_ZEC_in_DeFi": "Использование Zcash в DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Визуализация адресов Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Визуализация сети Zcash",
  "site/guides/Ywallet_FROST_Demo": "Демонстрация FROST в Ywallet",
  "site/guides/Zcash_Devtool": "Инструмент разработчика Zcash",
  "site/guides/Zcash_Improvement_Proposals": "Предложения по улучшению Zcash",
  "site/guides/Zenith_Installation": "Установка GUI-кошелька Zenith с полным узлом",
  "site/guides/Zero-Knowledge_vs_Decoys": "Zero Knowledge vs системы на основе decoy",
  "site/guides/Zgo_Payment_Processor": "Платёжный процессор ZGo: приём Zcash без кастодиального хранения",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Руководство по мультиподписи в Zkool",
  "site/guides/coinholder_log_parser/help": "Фильтр журнала выборов",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Демонстрация FROST в Ywallet",
  "site/guides/multisigdemo/MultiSigDemo": "Демонстрация MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "День 3 воркшопа",
  "site/tutorials/Exchanges": "Биржи Zcash",
  "site/tutorials/Full_Node_Tutorials": "Руководства по полным узлам",
  "site/tutorials/Using_Zcash": "Руководства по использованию Zcash",
  "site/tutorials/Wallet_Tutorials": "Руководства по кошелькам Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Защищённые рассылки",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
