// AUTO-GENERATED — fr page titles (first H1, HTML stripped) keyed by
// the SideMenu item path (`site/<Category>/<File>` without .md). Used to
// localize the left side-menu labels for the `fr` locale. Regenerate with
// scratchpad/gen_page_titles_loc.py after adding/retitling translated pages.
export const pageTitlesFr: Record<string, string> = {
  "site/Glossary_and_FAQs/FAQ": "Questions fréquemment posées",
  "site/Glossary_and_FAQs/Gallery": "Galerie de fonds d’écran Zcash",
  "site/Glossary_and_FAQs/Zcash_Library": "Bibliothèque Zcash",
  "site/Privacy_Tools/2FA_Hardware_Devices": "Appareils matériels 2FA",
  "site/Privacy_Tools/Arti_Tor": "Arti : le client Tor de nouvelle génération en Rust",
  "site/Privacy_Tools/GrapheneOS": "Graphene OS",
  "site/Privacy_Tools/Namada_Protocol": "Protocole Namada",
  "site/Privacy_Tools/PGP_Encryption": "Pretty Good Privacy (PGP)",
  "site/Privacy_Tools/Penumbra": "Penumbra",
  "site/Privacy_Tools/Secure_Messengers": "Messageries sécurisées",
  "site/Privacy_Tools/Shade_Protocol": "Shade Protocol",
  "site/Privacy_Tools/Tor_and_I2P": "Pourquoi la vie privée est importante",
  "site/Privacy_Tools/VPN_and_DVPN": "VPN & dVPN",
  "site/Privacy_Tools/Web_Browsers": "Navigateurs Web",
  "site/Research/Dash_Zcash_Orchard_Integration": "Intégration de Zcash Orchard par Dash",
  "site/Research/Namada_Privacy_and_Best_Practices": "Meilleures pratiques de confidentialité sur Namada",
  "site/Research/Navigating_the_Central_Bank_Digital_Currency": "Dévoiler le côté obscur : naviguer dans l’odyssée des monnaies numériques de banque centrale (CBDC) au milieu des ombres financières",
  "site/Research/Social_Media_Data_Collection": "Collecte de données sur les réseaux sociaux",
  "site/Research/Track_Early_Onchain_And_Social_Signals_for_Zcash": "Suivi des premiers signaux on-chain et sociaux pour Zcash (ZEC)",
  "site/Research/ZK_Shielded_Asset_Platforms": "Plateformes d’actifs à preuve à divulgation nulle de connaissance",
  "site/Research/zcash-foundations-series/article-0/article-0-shielded-transaction": "Comment fonctionne réellement une transaction Zcash blindée",
  "site/Research/zcash-foundations-series/article-1/article-1-finite-fields": "Corps finis : le système de nombres dans lequel vit la cryptographie",
  "site/Research/zcash-foundations-series/article-2/article-2-elliptic-curves": "Courbes elliptiques : là où naissent les clés et les engagements de Zcash",
  "site/Research/zcash-foundations-series/article-3/article-3-hashing-commitments": "Hachage et engagements : l’enveloppe magique scellée",
  "site/Research/zcash-foundations-series/article-4/article-4-merkle-trees": "Arbres de Merkle : comment la blockchain se souvient de chaque note",
  "site/Research/zcash-foundations-series/article-5/article-5-zero-knowledge-proofs": "Preuves à divulgation nulle de connaissance : prouver que vous avez raison sans dire pourquoi",
  "site/Research/zcash-foundations-series/article-6/article-6-shielded-protocol": "Le protocole shielded, de bout en bout",
  "site/Start_Here/Developer_Resources": "Ressources pour les développeurs",
  "site/Start_Here/Development_Fund": "Fonds de développement de Zcash",
  "site/Start_Here/Network_Upgrades": "Mises à niveau du réseau Zcash",
  "site/Start_Here/New_User_Guide": "Guide du nouvel utilisateur Zcash",
  "site/Start_Here/Using_This_Wiki": "Utiliser ce wiki",
  "site/Start_Here/What_is_ZEC_and_Zcash": "Les bases de Zcash",
  "site/Start_Here/What_is_ZecHub": "Qu'est-ce que ZecHub ?",
  "site/Start_Here/ZEC_Use_Cases": "Les bases de Zcash",
  "site/Start_Here/Zcash_Monetary_Policy": "Les bases de Zcash",
  "site/Start_Here/Zcash_Resources": "Ressources Zcash",
  "site/Using_Zcash/Blockchain_Explorers": "Explorateurs de blockchain",
  "site/Using_Zcash/Buying_ZEC": "Obtenir du Zcash",
  "site/Using_Zcash/Creators_and_Tips": "Outils Zcash pour les créateurs : plateformes de pourboires et de profils",
  "site/Using_Zcash/Custodial_Exchanges": "Exchanges centralisés",
  "site/Using_Zcash/Encifher_Swaps": "Échange privé SOL/USDC -> ZEC avec Encrypt.trade",
  "site/Using_Zcash/Faucets": "Faucets",
  "site/Using_Zcash/Memos": "Mémos",
  "site/Using_Zcash/Metamask_Snap": "Guide d’intégration du Snap Zcash pour MetaMask",
  "site/Using_Zcash/Mobile_Top_Ups": "Recharge mobile avec Zcash",
  "site/Using_Zcash/Non-Custodial_Exchanges": "Bourses non dépositaires",
  "site/Using_Zcash/Payment_Processors": "Processeurs de paiement Zcash",
  "site/Using_Zcash/Payment_Request_URIs": "URI de demande de paiement Zcash",
  "site/Using_Zcash/Recovering_Funds": "Récupération des fonds d’un portefeuille Zcash",
  "site/Using_Zcash/Shielded_Pools": "Pools de valeur Zcash",
  "site/Using_Zcash/Solswap": "Comment échanger contre du ZEC dans le wallet Phantom",
  "site/Using_Zcash/Spend_Zcash/Top_10_Places_to_spend_ZEC": "Endroits où dépenser des ZEC",
  "site/Using_Zcash/Testnet": "Zcash Testnet",
  "site/Using_Zcash/Transactions": "Transactions",
  "site/Using_Zcash/Transparent_Exchange_Addresses": "Que sont les adresses TEX de Zcash ?",
  "site/Using_Zcash/Zcash_Mining_Guide": "Guide du minage Zcash : rejoindre un pool de minage avec du matériel personnel",
  "site/Using_Zcash/Zcash_Mining_Pools": "Pools de minage Zcash",
  "site/Using_Zcash/zimppy": "Zimppy.xyz",
  "site/ZFAV_Club/Guides_for_Creators": "Guides pour les créateurs",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools": "Outils d’IA : génération de texte, d’images, de vidéos et d’audio (en ligne)",
  "site/ZFAV_Club/Guides_for_Creators/AI_tools_for_offline": "Outils d’IA (locaux, hors ligne)",
  "site/ZFAV_Club/Guides_for_Creators/Community_Broadcasting": "Diffusion communautaire avec VDO.Ninja et OBS Studio",
  "site/ZFAV_Club/Guides_for_Creators/Creating_Zcon_Highlights": "Démarrage rapide : créer des extraits Zcon",
  "site/ZFAV_Club/Guides_for_Creators/IPFS_File_Sharing": "Partage de fichiers P2P avec IPFS et le navigateur Brave",
  "site/ZFAV_Club/Guides_for_Creators/Livestream_Setup": "Configuration du livestream",
  "site/ZFAV_Club/Guides_for_Creators/Publish_Site_on_IPFS": "Publier un site sur IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Serve_Github_Repo_with_IPFS": "Héberger un dépôt GitHub avec IPFS",
  "site/ZFAV_Club/Guides_for_Creators/Video_Subtitle_Generation_with_Translation": "Génération et traduction de sous-titres vidéo",
  "site/Zcash_Community/Arborist_Calls": "Arborist Calls",
  "site/Zcash_Community/Community_Blogs": "Blogs de la communauté",
  "site/Zcash_Community/Community_Links": "Liens de la communauté Zcash",
  "site/Zcash_Community/Cypherpunk_Zero_NFT": "Cypherpunk Zero",
  "site/Zcash_Community/ZCAP": "Panel consultatif communautaire de Zcash",
  "site/Zcash_Community/ZFAV_Club/Guides/Github_With_IPFS": "Servir un dépôt Github avec IPFS",
  "site/Zcash_Community/ZFAV_Club/Guides/Website_On_IPFS": "Publier un site web sur IPFS",
  "site/Zcash_Community/Zcash_Ecosystem_Security": "Sécurité de l’écosystème Zcash",
  "site/Zcash_Community/Zcash_Global_Ambassadors": "Ambassadeurs mondiaux de Zcash",
  "site/Zcash_Community/Zcash_Governance": "Aperçu du financement et de la gouvernance de Zcash",
  "site/Zcash_Community/Zcash_Media": "Médias Zcash",
  "site/Zcash_Community/Zcash_Podcasts": "Podcasts",
  "site/Zcash_Community/Zcon_Archive": "Zcon",
  "site/Zcash_Community/Zcon_Vozes": "Zcon Vozes",
  "site/Zcash_Organizations/CoinHolder_Directed_Retroactive_Grants": "Subventions rétroactives dirigées par les détenteurs de jetons",
  "site/Zcash_Organizations/Electric_Coin_Company": "Electric Coin Company (Coucher de soleil)",
  "site/Zcash_Organizations/Financial_Privacy_Foundation": "Financial Privacy Foundation (FPF)",
  "site/Zcash_Organizations/Shielded_Labs": "Shielded Labs",
  "site/Zcash_Organizations/ZKAV": "Club ZKAV",
  "site/Zcash_Organizations/ZODL": "ZODL (Zcash Open Development Lab)",
  "site/Zcash_Organizations/Zcash_Community_Grants": "Zcash Community Grants",
  "site/Zcash_Organizations/Zcash_Foundation": "Zcash Foundation",
  "site/Zcash_Organizations/Zingo_Labs": "ZingoLabs",
  "site/Zcash_Social_Media/Cryptonote": "De zéro à la connaissance nulle : protocole CryptoNote",
  "site/Zcash_Social_Media/Hash_Functions": "De zéro à la connaissance nulle : fonctions de hachage",
  "site/Zcash_Social_Media/Lelantus": "De zéro à la connaissance nulle : protocole Lelantus",
  "site/Zcash_Social_Media/Mnemonic_Seed_Phrases": "De zéro à Zero Knowledge : les phrases mnémoniques de récupération",
  "site/Zcash_Social_Media/Podcasts/Podcasts": "Résumés des épisodes du ZK Podcast",
  "site/Zcash_Social_Media/Podcasts/Shielded_Transaction_Podcast": "Podcast Shielded Transactions par le Forsight Institute",
  "site/Zcash_Social_Media/Podcasts/The_ZK_Podcast": "Podcast Zero Knowledge",
  "site/Zcash_Social_Media/Podcasts/The_Zcash_Podcast": "Le podcast Zcash sur le Digital Cash Network",
  "site/Zcash_Social_Media/Podcasts/The_z2z_Podcast": "Le podcast Z2Z",
  "site/Zcash_Social_Media/Podcasts/Zcast_Podcast": "Podcast Zcast",
  "site/Zcash_Social_Media/Podcasts/pgp_for_crypto_podcast": "Podcast PGP pour la Crypto",
  "site/Zcash_Social_Media/TEEs": "De Zero à Zero Knowledge : Environnements d’exécution de confiance (TEEs)",
  "site/Zcash_Social_Media/Zcash_Addresses": "De zéro à la connaissance zéro : transactions transparentes vs protégées et Unified Address",
  "site/Zcash_Social_Media/Zero_to_Zero-knowledge": "De zéro à la connaissance nulle | Série éducative",
  "site/Zcash_Tech/FROST": "FROST",
  "site/Zcash_Tech/Full_Nodes": "Nœuds complets",
  "site/Zcash_Tech/Halo": "Halo",
  "site/Zcash_Tech/Lightwallet_Nodes": "Nœuds Lightwallet Zcash",
  "site/Zcash_Tech/Pepper_Sync": "Zingo 2.0 - Pepper Sync",
  "site/Zcash_Tech/Post_Quantum_Security": "Sécurité post-quantique dans Zcash",
  "site/Zcash_Tech/Viewing_Keys": "Viewing Keys",
  "site/Zcash_Tech/ZAP1_Attestation_Protocol": "Protocole d’attestation ZAP1",
  "site/Zcash_Tech/Zaino": "Indexeur Zaino",
  "site/Zcash_Tech/Zcash_Shielded_Assets": "Zcash Shielded Assets",
  "site/Zcash_Tech/Zcash_Wallet_Syncing": "Synchronisation des portefeuilles Zcash",
  "site/Zcash_Tech/Zebra_Full_Node": "Configuration requise du système et configuration réseau pour Zebra",
  "site/Zcash_Tech/zk_SNARKS": "ZKP & ZK-SNARKS",
  "site/Zcash_Use_Cases/About": "Utiliser Zcash dans le monde réel",
  "site/Zcash_Use_Cases/Accept_Payments_AS_A_Merchant": "Accepter des paiements en tant que commerçant avec Zcash",
  "site/Zcash_Use_Cases/Freelance_Privacy_Setup": "Configuration de confidentialité pour freelance avec Zcash",
  "site/Zcash_Use_Cases/Journalist_privacy_setup": "Configuration de confidentialité pour journalistes avec Zcash",
  "site/Zcash_Use_Cases/Keeping_Records_With_Shielded_ZEC": "Tenir des registres avec des ZEC protégés",
  "site/Zcash_Use_Cases/Private_Community_treasury": "Gérer une trésorerie communautaire privée avec Zcash",
  "site/Zcash_Use_Cases/Receive_Donations_Privately": "Recevoir des dons en privé avec Zcash",
  "site/Zcash_Use_Cases/Send_Money_Without_Linking_Identity": "Envoyer de l’argent sans lier votre identité",
  "site/contribute/Community_Infrastructure": "Cadre d’infrastructure communautaire de ZecHub",
  "site/contribute/Contributing_Guide": "Contribuer à ZecHub",
  "site/contribute/Help_build_ZecHub": "Aidez à construire ZecHub",
  "site/contribute/Style_Guide": "Guide de style ZecHub",
  "site/contribute/ZecHub_DAO": "ZecHub DAO",
  "site/contribute/ZecWeekly_Newsletter": "Newsletter ZecWeekly",
  "site/guides/Akash_Network_Zcashd": "Déployer zcashd sur Akash via Console",
  "site/guides/Akash_Network_Zebra": "Comment exécuter Zebra sur Akash Network",
  "site/guides/Avalanche_RedBridge": "Zcash Avalanche RedBridge",
  "site/guides/BTCPayServer_Zcash_Plugin": "BTCPay Server avec prise en charge de Zcash : guide complet d’installation et d’intégration",
  "site/guides/Blockchain_Explorers": "Explorateurs de blockchain",
  "site/guides/Brave_Wallet_Guide": "Comment envoyer et recevoir du Zcash (ZEC) protégé avec Brave Wallet : guide pas à pas pour la confidentialité",
  "site/guides/Free2Z_Livestreaming": "Diffusion en direct sur Free2Z",
  "site/guides/Free2z_Live": "Free2z : Configuration du compte + tutoriel de livestream",
  "site/guides/Hardened_Zebrad": "Nœud complet Zebra renforcé",
  "site/guides/Keystone_Zashi": "Guide d'utilisation de Keystone Zashi",
  "site/guides/Maya_Protocol": "Maya Decentralised Exchange",
  "site/guides/Migration_Guide_Zcashd_To_Zebrad_Zallet": "Guide de migration : de zcashd vers Zebrad/Zallet",
  "site/guides/My_First_Zcash_Workbook": "Mon premier cahier d'exercices Zcash",
  "site/guides/Nym_VPN": "Nym VPN",
  "site/guides/Raspberry_Pi_4_Full_Node": "Raspberry Pi 4 : guide d’un nœud complet zcashd",
  "site/guides/Raspberry_pi5_Zebra_Lightwalletd_Zingo": "RPi5 Zebra Lightwalletd avec Zingo",
  "site/guides/Raspberry_pi_4_Zebra_Node": "Guide du Raspberry Pi 4 pour exécuter Zebra",
  "site/guides/ShapeShift_Zcash": "ShapeShift et Zcash : le trading décentralisé axé sur la confidentialité",
  "site/guides/Using_ZEC_Privately": "Utiliser ZEC, en privé",
  "site/guides/Using_ZEC_in_DeFi": "Utiliser Zcash dans la DeFi",
  "site/guides/Visualizing_Zcash_Addresses": "Visualiser les adresses Zcash",
  "site/guides/Visualizing_the_Zcash_Network": "Visualiser le réseau Zcash",
  "site/guides/Ywallet_FROST_Demo": "Démo FROST de Ywallet",
  "site/guides/Zcash_Devtool": "Le Zcash Devtool",
  "site/guides/Zcash_Improvement_Proposals": "ZIP de Zcash Improvement Proposal",
  "site/guides/Zenith_Installation": "Installation du portefeuille de nœud complet Zenith GUI",
  "site/guides/Zero-Knowledge_vs_Decoys": "Connaissances à divulgation nulle vs systèmes basés sur des leurres",
  "site/guides/Zgo_Payment_Processor": "Processeur de paiement ZGo : accepter Zcash sans garde",
  "site/guides/Zingolib_and_Zaino_Tutorial": "Z3: (zebrad)(zaino)(zingo-cli)",
  "site/guides/Zkool_Multisig": "Guide Multisig de Zkool",
  "site/guides/coinholder_log_parser/help": "Filtre de journal des élections",
  "site/guides/frostdemo/Ywallet_FROST_Demo": "Démo FROST de Ywallet",
  "site/guides/multisigdemo/MultiSigDemo": "Démonstration MultiSig",
  "site/guides/workshops/zcashContributorWorkshopDay3": "Atelier Jour 3",
  "site/tutorials/Exchanges": "Exchanges Zcash",
  "site/tutorials/Full_Node_Tutorials": "Tutoriels sur les nœuds complets",
  "site/tutorials/Using_Zcash": "Tutoriels pour utiliser Zcash",
  "site/tutorials/Wallet_Tutorials": "Tutoriels de portefeuilles Zcash",
  "site/tutorials/shieldedNewsletter/readme": "Newsletters blindées",
  "site/tutorials/zenithserver/zenithBeta": "Zenith 0.10 Beta",
};
