// Web Push
const WEB_PUSH_VAPID_PUBLIC_KEY = process.env.NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY || '';
const WEB_PUSH_VAPID_PRIVATE_KEY = process.env.WEB_PUSH_VAPID_PRIVATE_KEY || '';
const WEB_PUSH_VAPID_SUBJECT = process.env.WEB_PUSH_VAPID_SUBJECT || '';

// MONGO_DB
const MONGO_DB_CONNECTION_STRING_DEV =
  process.env.MONGO_DB_CONNECTION_STRING_DEV || '';
const MONGO_DB_CONNECTION_STRING_PROD =
  process.env.MONGO_DB_CONNECTION_STRING_PROD || '';

export {
  MONGO_DB_CONNECTION_STRING_DEV,
  MONGO_DB_CONNECTION_STRING_PROD,
  WEB_PUSH_VAPID_PRIVATE_KEY,
  WEB_PUSH_VAPID_PUBLIC_KEY,
  WEB_PUSH_VAPID_SUBJECT,
};
